- narwhals/_arrow/series.py
- tests/expr_and_series/dt/datetime_attributes_test.py
> bug: fix pyarrow `to_date`

- docs/installation.md
> docs: update installation.md

- CONTRIBUTING.md
I think we should mention that we can test cuDF manually using a kaggle notebook. What do you think?
> doc: add note about cuDF tests in contributing guide

- narwhals/_polars/dataframe.py
- narwhals/_polars/utils.py
> fix: flaky test on polars==0.20.30

- narwhals/expr.py
- narwhals/series.py
- Closes #1229 
Diff is large but easier than what it could look like - idea is to let Namespace's accept generic, which will be Self of the class
> chore: series and expr namespaces typing with generics

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.10.0

- README.md
Hey, I'm working on a data-contracts project based on top of Narwhals and Marco over on the discord he'd consider adding it to the readme.
It's in very early stages, so I won't be offended if you'd rather not! Either way, I wanted to start building this project ages ago and pre-Narwhals it was basically impossible, so thanks for an awesome library 😁
- Closes #
> docs: Wimsey added to project list in Readme

- narwhals/utils.py
- tests/utils_test.py
> perf: pandas-like fastpath in maybe_reset_index

- narwhals/_pandas_like/dataframe.py
- narwhals/_pandas_like/group_by.py
- narwhals/_pandas_like/namespace.py
- narwhals/_pandas_like/series.py
> perf: always use copy=False when doing rename for pandas

- narwhals/_dask/dataframe.py
- narwhals/_dask/expr.py
- tests/conftest.py
> test: only test dask with partitions=2 for now

- narwhals/_pandas_like/group_by.py
- tests/frame/interchange_native_namespace_test.py
- tests/frame/schema_test.py
- tests/group_by_test.py
> test: get groupby tests passing for pandas 1.0.x

- narwhals/_arrow/dataframe.py
- narwhals/_arrow/expr.py
- narwhals/_arrow/group_by.py
- narwhals/_dask/dataframe.py
- narwhals/_dask/expr.py
- narwhals/_dask/group_by.py
- narwhals/_pandas_like/dataframe.py
- narwhals/_pandas_like/expr.py
- narwhals/_pandas_like/group_by.py
- narwhals/_polars/dataframe.py
- narwhals/_polars/group_by.py
- narwhals/dataframe.py
- narwhals/group_by.py
- tests/group_by_test.py
> feat: add drop_null_keys argument to group_by

- narwhals/_dask/dataframe.py
- narwhals/_dask/expr.py
- narwhals/_pandas_like/dataframe.py
- narwhals/_pandas_like/series.py
- narwhals/_pandas_like/utils.py
- narwhals/dataframe.py
- narwhals/series.py
- tests/frame/interchange_native_namespace_test.py
- tests/frame/unpivot_test.py
> perf: improve performance of Series.dtype and DataFrame.schema for pandas-like

- tests/frame/unpivot_test.py
- tests/group_by_test.py
> test: xfail cudf failures

- docs/requirements-docs.txt
> docs: add duckdb to docs

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.11.0

- docs/api-reference/narwhals.md
- narwhals/__init__.py
- narwhals/_arrow/dataframe.py
- narwhals/_arrow/series.py
- narwhals/_dask/dataframe.py
- narwhals/_dask/expr.py
- narwhals/_pandas_like/dataframe.py
- narwhals/stable/v1/__init__.py
- narwhals/utils.py
- tests/utils_test.py
> feat: expose `generate_temporary_column_name`

- narwhals/_pandas_like/group_by.py
- tests/group_by_test.py
> fix: Cudf groupby iter

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.11.1

- narwhals/translate.py
- tests/translate/from_native_test.py
> err: replace msg = "Please set allow_series=True" with msg = "Please set allow_series=True or series_only=True"

- narwhals/_interchange/dataframe.py
- tests/frame/interchange_schema_test.py
- tests/frame/interchange_select_test.py
> feat: support `columns` and `select` for InterchangeFrame if `_df` is present

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.12.0

- .github/dependabot.yml
- .pre-commit-config.yaml
> ci: set pre-commit autoupdate to run monthly instead of weekly

- docs/api-reference/dependencies.md
- narwhals/dependencies.py
- tests/dependencies/is_into_dataframe_test.py
> feat: add is_into_dataframe

- docs/backcompat.md
> docs: document Stable API changes

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.13.0

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.13.1

- README.md
> expand "used by"

- narwhals/expr.py
- narwhals/series.py
> docs: add note about conversion as if from utc in convert_time_zone

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.13.2

- README.md
NA
Simply adds entry in README related to Real Python Podcast's episode featuring 🦄 🐳
> docs: update README with entry in Appears on section

- mkdocs.yml
- Related issue #
- Closes #1329 
Added `enable_inventory: true` to `mkdocs.yml` to enable the inventory feature.
> enabled inventory for intersphinx

- narwhals/_pandas_like/dataframe.py
- narwhals/_pandas_like/series.py
- narwhals/series.py
- pyproject.toml
> feat: support to_list for cudf, note limitations

- README.md
They merged the PR and made a release
> docs: used by `tabmat`

- .github/workflows/downstream_tests.yml
- narwhals/expr.py
- tests/selectors_test.py
> ci: pin websockets, fixup 3.13 doctests, remove unnecessary xfail

- narwhals/_arrow/expr.py
- narwhals/_arrow/series.py
- narwhals/_dask/expr.py
- narwhals/_pandas_like/expr.py
- narwhals/_pandas_like/series.py
- narwhals/_polars/expr.py
- narwhals/_polars/series.py
- narwhals/expr.py
- narwhals/series.py
- tests/expr_and_series/replace_strict_test.py
- [Related ~~issue~~ comment](https://github.com/narwhals-dev/narwhals/pull/1327#discussion_r1833847786)
> feat: allow mapping in `replace_strict` method

- tpch/execute/q1.py
- tpch/execute/q10.py
- tpch/execute/q11.py
- tpch/execute/q12.py
- tpch/execute/q13.py
- tpch/execute/q14.py
- tpch/execute/q15.py
- tpch/execute/q16.py
- tpch/execute/q17.py
- tpch/execute/q18.py
- tpch/execute/q19.py
- tpch/execute/q2.py
- tpch/execute/q20.py
- tpch/execute/q21.py
- tpch/execute/q22.py
- tpch/execute/q3.py
- tpch/execute/q4.py
- tpch/execute/q5.py
- tpch/execute/q6.py
- tpch/execute/q7.py
- tpch/execute/q8.py
- tpch/execute/q9.py
> ci: remove dask from tpch tests

- narwhals/_arrow/namespace.py
- narwhals/_dask/namespace.py
- narwhals/_expression_parsing.py
- narwhals/_pandas_like/dataframe.py
- narwhals/_pandas_like/namespace.py
- narwhals/_pandas_like/utils.py
> chore: Rename some internals

- tests/series_only/to_list_test.py
> test: remove cuDF xfail for tests/series_only/to_list_test.py::test_to_list

- narwhals/_pandas_like/dataframe.py
- narwhals/expr.py
- narwhals/stable/v1/__init__.py
- Closes #466 
Super tiny one 🤏🏼 
With the latest (actually not so latest anymore) changes, this is _mandatory_.
> fix: remove TODO in `PandasLikeDataFrame.to_dict`

- narwhals/_dask/dataframe.py
- narwhals/_dask/expr.py
- narwhals/_dask/namespace.py
- narwhals/_dask/utils.py
> perf: replace loc with getitem in Dask

- narwhals/_dask/dataframe.py
- narwhals/_pandas_like/dataframe.py
- narwhals/_pandas_like/group_by.py
- narwhals/_pandas_like/utils.py
- tests/frame/select_test.py
- tests/utils.py
> perf: Prefer getitem instead of loc for selecting multiple columns in pandas-like

- tests/series_only/to_dummy_test.py
> test: unxfail `test_to_dummies_drop_first_na` for cudf

- docs/javascripts/extra.js
- mkdocs.yml
- Closes # https://github.com/narwhals-dev/narwhals/issues/1338
Copied from https://github.com/astral-sh/ruff/blob/main/docs/js/extra.js
> docs: Avoid copying >>> and ... from clipboard

- README.md
- docs/roadmap_and_related.md
- narwhals/_polars/expr.py
> chore: More Polars typing, update 'used by', link to roadmap

- .github/pull_request_template.md
See [comment](https://github.com/narwhals-dev/narwhals/issues/1338#issuecomment-2476158652)
> chore: suggest to add issue number in pr template

- narwhals/_arrow/utils.py
- narwhals/_dask/utils.py
- narwhals/_pandas_like/utils.py
- narwhals/expr.py
- narwhals/series.py
- tests/frame/reindex_test.py
- tests/frame/select_test.py
https://github.com/narwhals-dev/narwhals/issues/920
> feat: Improve error message when comparing Series with list literal, or when using multi-output expressions in unsupported context

- narwhals/expr.py
- narwhals/series.py
- narwhals/utils.py
> docs: Show ExprT as return type for Expr namespaces

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.14.0

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.14.1

- README.md
> docs: add vegafusion to "used by" on readme

- .github/workflows/downstream_tests.yml
> ci: temporarily pin olama

- narwhals/dependencies.py
- narwhals/stable/v1/dependencies.py
- tests/conftest.py
- tests/dependencies/is_into_dataframe_test.py
- tests/dependencies/is_into_series_test.py
- tests/dependencies/is_pandas_dataframe_test.py
- tests/dependencies/is_pandas_index_test.py
- tests/translate/to_py_scalar_test.py
> feat: make sure `from narwhals.stable.v1.dependencies` import works

- narwhals/_arrow/utils.py
- narwhals/_dask/utils.py
- narwhals/_pandas_like/utils.py
- narwhals/_polars/utils.py
- narwhals/dtypes.py
- narwhals/expr.py
- narwhals/series.py
- narwhals/utils.py
- tests/expr_and_series/cast_test.py
- tests/frame/invalid_test.py
> feat: improve error message when casting to invalid type

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.14.2

- narwhals/_arrow/utils.py
- narwhals/_dask/namespace.py
- narwhals/_pandas_like/utils.py
- narwhals/functions.py
- narwhals/stable/v1/__init__.py
- tests/frame/concat_test.py
> feat: improve `concat` error message and `concat` docs

- .github/workflows/downstream_tests.yml
- docs/api-reference/typing.md
- narwhals/stable/v1/typing.py
- narwhals/typing.py
> docs: Add docstrings with examples to types

- .github/workflows/downstream_tests.yml
- narwhals/dependencies.py
> feat: silently support Fireducks and cudf.pandas

- .github/workflows/downstream_tests.yml
- mkdocs.yml
addresses https://github.com/narwhals-dev/narwhals/pull/1375#issuecomment-2495958120
> docs: fixup copy button

- narwhals/_polars/dataframe.py
- narwhals/_polars/series.py
- narwhals/_polars/utils.py
- Closes #1416 
Adds `backend_version` parameter to `native_to_narwhals_dtype` utility in `Polars`.
> chore: add `backend_version` parameter to polars dtype translation utility

- narwhals/expr.py
- narwhals/series.py
- narwhals/stable/v1/__init__.py
Fixing up some issues highlighted in https://github.com/narwhals-dev/narwhals/pull/1448 - thanks @LiamConnors ! We'll figure out a fast way to run this in CI
> docs: fixup typing in docstrings

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.15.0

- .github/workflows/extremes.yml
- narwhals/functions.py
- narwhals/stable/v1/__init__.py
- tests/from_dict_test.py
> fix: follow left-hand-rule in index alignment in from_dict

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.15.1

- README.md
- docs/index.md
- narwhals/_arrow/series.py
- narwhals/_arrow/utils.py
- narwhals/_pandas_like/namespace.py
- narwhals/_pandas_like/series.py
- narwhals/_pandas_like/utils.py
- narwhals/functions.py
- utils/generate_zen_content.py
> chore: rename validate_column_comparand utility functions, add pep740 badge

- docs/extending.md
- narwhals/dataframe.py
- narwhals/functions.py
- narwhals/series.py
- narwhals/translate.py
> fix: Set level correctly for lazy-only implementations

- narwhals/functions.py
- narwhals/stable/v1/__init__.py
- narwhals/utils.py
- tests/frame/invalid_test.py
> feat: improve invalid concat error message

- narwhals/series.py
> docs: add return description for `Series.to_list` 

- narwhals/dtypes.py
> docs: add `Enum` dtype docstring example

- narwhals/dtypes.py
- narwhals/stable/v1/_dtypes.py
- [ x] 📝 Documentation
- [ x] Code follows style guide (ruff)
> docs: add Duration dtype docstring example

- docs/how_it_works.md
- narwhals/dataframe.py
- narwhals/expr.py
- narwhals/stable/v1/__init__.py
> chore: rename _call to _to_compliant_expr in narwhals/expr.py

- narwhals/translate.py
- tests/translate/get_native_namespace_test.py
closes https://github.com/narwhals-dev/narwhals/issues/1498
making this PR even though i'd marked it "reserved for sprint" because I need it for something else i'm working on
>  enh: get_native_namespace accepts native objects

- narwhals/dtypes.py
- Related issue #1503
- Closes #1503
> docs: Add `narwhals.dtypes.Date` docstring example

- narwhals/_arrow/dataframe.py
- narwhals/_arrow/group_by.py
- narwhals/_arrow/namespace.py
- narwhals/_arrow/series.py
- narwhals/_arrow/utils.py
- narwhals/_dask/dataframe.py
- narwhals/_dask/expr.py
- narwhals/_dask/group_by.py
- narwhals/_dask/namespace.py
- narwhals/_dask/utils.py
- narwhals/_pandas_like/dataframe.py
- narwhals/_pandas_like/utils.py
- narwhals/_polars/dataframe.py
- narwhals/_polars/namespace.py
- narwhals/_polars/series.py
- narwhals/_polars/utils.py
- narwhals/translate.py
- utils/import_check.py
> chore: remove many false positives from "ignore banned import" check

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.16.0

- docs/api-reference/expr_list.md
- docs/api-reference/series_list.md
- narwhals/_arrow/expr.py
- narwhals/_arrow/series.py
- narwhals/_arrow/utils.py
- narwhals/_pandas_like/expr.py
- narwhals/_pandas_like/series.py
- narwhals/_pandas_like/utils.py
- narwhals/_polars/expr.py
- narwhals/_polars/series.py
- narwhals/_polars/utils.py
- narwhals/expr.py
- narwhals/series.py
- tests/expr_and_series/list/len_test.py
- utils/check_api_reference.py
Introduces `ListNamespace` and only one method (`.len`) for Series and Expr.
> feat: `ListNamespace.len()` for `Expr` and `Series`

- .github/release-drafter.yml
> ci: try using "unrelease" version-template for release drafter

- .github/release-drafter.yml
> ci: fix template name

- .github/release-drafter.yml
- .github/workflows/extremes.yml
- narwhals/_pandas_like/dataframe.py
- narwhals/_pandas_like/group_by.py
- narwhals/_pandas_like/namespace.py
- narwhals/_pandas_like/series.py
- narwhals/_pandas_like/utils.py
- pyproject.toml
> ci: actually test against pandas nightly, don't filter "copy is deprecated" warnings

- narwhals/dtypes.py
- narwhals/stable/v1/_dtypes.py
- Related issue #1504 
- Closes #1504
> docs: Add a docstring example in narwhals.dtypes for Datetime

- .github/workflows/downstream_tests.yml
> ci: temporary pins to get CI green

- .github/workflows/publish_to_pypi.yml
- docs/security.md
> ci: fixup release process

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.18.0

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.18.2

- narwhals/_pandas_like/expr.py
Just a couple of very minor things I noticed when poking around the codebase.
- remove repeated variable definition from __init__
- add closing parenthesis to __repr__ string
> refactor: PandasLikeExpr __repr__ and __init__

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.18.3

- narwhals/dtypes.py
- Related issue #1501 
- Closes #1501
> docs: add docstring example for Array in narwhals.dtypes

- narwhals/stable/v1/typing.py
- narwhals/typing.py
> docs: Correct small error in IntoDataFrameT and IntoSeriesT 

- README.md
- docs/ecosystem.md
tea-tasting is a Python package for the statistical analysis of A/B tests. Since version 0.3.0 it uses Narwhals to support more dataframes. With this PR I'd like to add tea-tasting to the list of projects in the Narwhals ecosystem.
> docs: add tea-tasting to ecosystem

- tests/group_by_test.py
> test: xfail test_group_by_shift_raises for cudf

- tests/group_by_test.py
> test: fixup more cuDF xfails

- narwhals/utils.py
> chore: use set_axis in maybe_set_index

- tests/expr_and_series/arg_max_test.py
- tests/expr_and_series/arg_min_test.py
> test: xfail cudf argmin / argmax

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.18.4

- .github/workflows/downstream_tests.yml
We just merged PR for scikit-learn 1.6 compatibility and made a release
> ci: unpin scikit-learn in scikit-lego test

- .github/workflows/extremes.yml
- narwhals/_arrow/group_by.py
- narwhals/_pandas_like/group_by.py
- pyproject.toml
- tests/group_by_test.py
> fix: pandas and pyarrow were raising for repeated aggregations involving the same root name and the same aggregation function

- .github/workflows/extremes.yml
> test: minimum versions

- narwhals/_arrow/group_by.py
- narwhals/_pandas_like/group_by.py
> perf: streamline pyarrow and pandas group by agg

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.19.0

- .github/workflows/extremes.yml
- [x ] ✅ Test
- closes #1615 
- [x ] Code follows style guide (ruff)
Hi,
I have added tests for not-so-old-versions, pretty-old-versions, and nightlies. I left out random-versions because I wanted to confirm whether the test logic belongs in random_ci_pytest.yml.
If there are any issues or changes required, please let me know. Thank you!
> test: not-so-old-versions, pretty-old-versions, nightlies

- narwhals/dataframe.py
> docs: returns and arguments documentation for lazyframe class

- noxfile.py
- utils/generate_backend_completeness.py
> fix: exclude protocols in api completeness script

- docs/api-reference/typing.md
> docs: fix typing example

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.19.1

- narwhals/series.py
> docs: Add return descriptions to Series's `abs`, `alias`, `all`, `any` methods for clarity

- narwhals/_spark_like/expr.py
- narwhals/_spark_like/group_by.py
- narwhals/_spark_like/utils.py
- narwhals/typing.py
- tests/spark_like_test.py
> fix: pyspark group by with kwargs

- narwhals/series.py
- narwhals/stable/v1/__init__.py
> docs: Add more return type descriptions for Series

- narwhals/series.py
> docs: Add return type description for more series namespace

- narwhals/_arrow/dataframe.py
- narwhals/_arrow/namespace.py
- narwhals/_arrow/utils.py
- Closes #1463 
With another couple of minor changes
> chore: pyarrow do not combine chunks

- narwhals/dataframe.py
- tests/group_by_test.py
This has come up a couple of times on discord
it may be possible to support this, but i don't have time right now, so i'd say that for now let's raise a proper error message and we can revisit later if necessary
> feat: raise informative error message when grouping by expressions

- narwhals/_arrow/dataframe.py
- narwhals/_dask/expr.py
- tests/expr_and_series/is_duplicated_test.py
- tests/expr_and_series/is_unique_test.py
> fix: `is_duplicated` was returning wrong-length result for PyArrow and Dask

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.20.0

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.20.1

- narwhals/_pandas_like/utils.py
- pyproject.toml
- tests/expr_and_series/max_horizontal_test.py
- tests/expr_and_series/min_horizontal_test.py
- tests/group_by_test.py
> fix: casting to List for cudf

- narwhals/_arrow/dataframe.py
- narwhals/_dask/dataframe.py
- narwhals/_spark_like/dataframe.py
- narwhals/dataframe.py
- tests/frame/unique_test.py
- tests/spark_like_test.py
> fix: remove `maintain_order` from LazyFrame.unique

- narwhals/dataframe.py
- narwhals/series.py
- narwhals/stable/v1/__init__.py
- Related issue #1000  and #1500 
Following standardization: 
- function renaming
- use `data` for almost all input lists
- split into multiple snippet (imports, constructors, function definition, function call per each backend)
- Typing is not 100% on point TBH
> docs: `Series` method' docstrings

- utils/generate_backend_completeness.py
- Related [discord message](https://discord.com/channels/1235257048170762310/1235257049626181656/1324448945472143404)
> docs: add spark-like in backend completeness

- narwhals/_arrow/utils.py
- narwhals/_pandas_like/utils.py
- narwhals/_polars/utils.py
- tests/expr_and_series/cast_test.py
> feat: enable to cast to `Struct` dtype

- narwhals/_pandas_like/group_by.py
- narwhals/_spark_like/group_by.py
> fix: fix broken link from warning

- pyproject.toml
- tests/expr_and_series/clip_test.py
- tests/expr_and_series/lit_test.py
> test: catch some cudf failures

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.21.0

- docs/basics/dataframe_conversion.md
- utils/generate_backend_completeness.py
- Related issue #1728 
Updates `api-completeness` with `duckdb` reference
> docs: update api-completeness with `duckdb`

- tests/frame/to_arrow_test.py
- tests/frame/write_parquet_test.py
> chore: filter old pyarrow/pandas warnings we cant do anything about

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.21.1

- narwhals/utils.py
Follow up from #1744 (FYI @FBruzzesi @MarcoGorelli )
> fix: update Spark min version in `utils.py`

- narwhals/_dask/expr.py
- narwhals/_dask/group_by.py
- narwhals/_dask/namespace.py
- narwhals/_dask/selectors.py
- narwhals/_dask/utils.py
- narwhals/translate.py
> chore: dask nightly

- .github/workflows/check_tpch_queries.yml
- .github/workflows/extremes.yml
- narwhals/_duckdb/dataframe.py
- tests/frame/join_test.py
- tests/utils.py
- tpch/execute.py
> feat: implement cross-join for duckdb

- docs/css/extra.css
- [x ] 📝 Documentation
- Closes #1754 
- [x ] Code follows style guide (ruff)
I have added custom css which targets the content of the grid and it allows it to fully stretch the content area. If there are any issues, or corrections needed let me know.
> docs: Increased width for content

- narwhals/_duckdb/expr.py
- tests/expr_and_series/unary_test.py
> fix: fix skew for duckdb with fewer than 3 elements

- narwhals/_duckdb/expr_dt.py
- tests/expr_and_series/dt/datetime_attributes_test.py
> feat: DuckDB `dt.weekday`

- narwhals/_duckdb/expr_dt.py
- tests/expr_and_series/dt/datetime_attributes_test.py
> feat: DuckDB `dt.ordinal_day`

- narwhals/_duckdb/expr_dt.py
- tests/expr_and_series/dt/to_string_test.py
> feat: DuckDB `dt.to_string`

- narwhals/_duckdb/expr_dt.py
- tests/expr_and_series/dt/datetime_attributes_test.py
> feat: DuckDB `date`

- narwhals/utils.py
- tests/utils_test.py
Per comment https://github.com/narwhals-dev/narwhals/pull/1792#issuecomment-2585325971
> feat: improve error message on check_columns_exist

- narwhals/translate.py
- tests/translate/to_py_scalar_test.py
> fix: to_py_scalar was raising for decimals

- narwhals/stable/v1/__init__.py
- narwhals/stable/v1/_dtypes.py
- tests/stable_api_test.py
> docs: remove docstring examples from narwhals/stable/v1

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.22.0

- narwhals/_spark_like/namespace.py
- tests/expr_and_series/when_test.py
> feat: add support for `SparkLikeNamespace.when`

- narwhals/_arrow/namespace.py
- narwhals/_dask/namespace.py
- narwhals/_pandas_like/namespace.py
- tests/expr_and_series/when_test.py
- Closes #1722 
Definitly not too proud of this implementation
> patch: fix when-then double lit case

- narwhals/_duckdb/expr_dt.py
- tests/expr_and_series/dt/datetime_duration_test.py
> feat: add total duration methods for DuckDB

- narwhals/_spark_like/expr_str.py
- tests/expr_and_series/str/to_datetime_test.py
> feat: add pyspark str namespace `to_datetime`

- narwhals/_pandas_like/utils.py
- tests/utils.py
> test: fixup test suite for cudf.pandas

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.23.0

- narwhals/_duckdb/expr.py
- narwhals/_duckdb/expr_list.py
- narwhals/_duckdb/utils.py
- tests/conftest.py
> feat: add DuckDB `list.len` method

- narwhals/_duckdb/utils.py
- tests/expr_and_series/cast_test.py
> feat: add DuckDB `Struct` dtype

- narwhals/_duckdb/expr.py
- tests/expr_and_series/std_test.py
- tests/expr_and_series/var_test.py
- tests/group_by_test.py
> feat: allow any ddof value for duckdb `var` and `std`

- narwhals/_pandas_like/series.py
- tests/frame/interchange_native_namespace_test.py
- tests/frame/interchange_schema_test.py
- tests/frame/interchange_select_test.py
- tests/frame/interchange_to_arrow_test.py
- tests/frame/interchange_to_pandas_test.py
- tests/frame/schema_test.py
> test: skip Ibis tests if deps aren't installed, set defaults in `PandasLikeSeries.__array__` to fix cuDF is_in

- narwhals/expr.py
- tests/expr_and_series/over_test.py
> feat: raise if expression changes length in `.over()`

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.24.0

- narwhals/_arrow/dataframe.py
- narwhals/_dask/dataframe.py
- narwhals/_dask/utils.py
- narwhals/_duckdb/dataframe.py
- narwhals/_duckdb/utils.py
- narwhals/_expression_parsing.py
- narwhals/_pandas_like/dataframe.py
- narwhals/_spark_like/dataframe.py
- narwhals/_spark_like/utils.py
> chore: use positional-only arg in evaluate_into_exprs

- pyproject.toml
> chore: add "typing :: typed" classifier to pyproject.toml

- narwhals/translate.py
> chore: fix pyspark/sqlframe typo

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.24.1

- README.md
This adds pointblank to the list of projects that uses Narwhals.
> docs(README.md): add mention of pointblank project

- docs/ecosystem.md
This adds pointblank to the `ecosystem.md` file (in the Used By section).
> docs(ecosystem.md): add `pointblank` to Used By section

- narwhals/_dask/selectors.py
- narwhals/_duckdb/selectors.py
- narwhals/_pandas_like/selectors.py
- narwhals/_spark_like/selectors.py
- narwhals/selectors.py
> docs: update selectors docstrings

- README.md
- docs/pandas_like_concepts/pandas_index.md
- narwhals/_pandas_like/group_by.py
- narwhals/typing.py
- tests/conftest.py
- tests/group_by_test.py
> fix: pandas was raising when index name and column names overlapped in groupby

- narwhals/_duckdb/expr_str.py
- tests/expr_and_series/str/to_datetime_test.py
> feat: add duckdb `.str.to_datetime`

- docs/backcompat.md
- narwhals/dataframe.py
- narwhals/exceptions.py
- narwhals/stable/v1/__init__.py
> docs: Minor rendering fixups, inherit all exceptions from NarwhalsError

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.25.0

- narwhals/_arrow/expr.py
- narwhals/_arrow/expr_name.py
- narwhals/_arrow/group_by.py
- narwhals/_arrow/namespace.py
- narwhals/_arrow/series_str.py
- narwhals/_dask/expr.py
- narwhals/_dask/namespace.py
- narwhals/_duckdb/dataframe.py
- narwhals/_duckdb/expr_name.py
- narwhals/_duckdb/expr_str.py
- narwhals/_duckdb/namespace.py
- narwhals/_pandas_like/dataframe.py
- narwhals/_pandas_like/group_by.py
- narwhals/_pandas_like/namespace.py
- narwhals/_pandas_like/series.py
- narwhals/_pandas_like/utils.py
- narwhals/_polars/namespace.py
- narwhals/_spark_like/expr_name.py
- narwhals/_spark_like/namespace.py
- narwhals/dtypes.py
- narwhals/utils.py
I spiraled into using [refurb](https://github.com/dosisod/refurb) and [perflint](https://github.com/tonybaloney/perflint) after a tiny [comment](https://github.com/narwhals-dev/narwhals/pull/1918#issuecomment-2629580550) 😂
There are other tweaks we could do, but I felt like they would decrease readability
> refactor: refactoring following refurb and perflint suggestions

- narwhals/_arrow/selectors.py
- narwhals/_dask/selectors.py
- narwhals/_duckdb/selectors.py
- narwhals/_pandas_like/selectors.py
- narwhals/_spark_like/selectors.py
- narwhals/series.py
> chore: a couple of typos 🙃

- .github/workflows/downstream_tests.yml
> ci: fix plotly downstream test

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.25.1

- narwhals/_pandas_like/dataframe.py
> fix: cuDF to_numpy tests were failing

- narwhals/_arrow/dataframe.py
- tests/frame/is_duplicated_test.py
- tests/frame/is_unique_test.py
> feat: restore support of `is_duplicated` for pyarrow

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.25.2

- narwhals/stable/v1/__init__.py
- Related PR #1936
Aligns with #1936 and similar change in #1953
> fix(typing): Backport use `IntoDataFrameT` in `to_native`  to `v1`

- .github/workflows/extremes.yml
- narwhals/_arrow/dataframe.py
- narwhals/_arrow/expr.py
- narwhals/_arrow/series.py
- narwhals/_dask/dataframe.py
- narwhals/_dask/expr.py
- narwhals/_duckdb/dataframe.py
- narwhals/_duckdb/expr.py
- narwhals/_ibis/dataframe.py
- narwhals/_pandas_like/dataframe.py
- narwhals/_pandas_like/expr.py
- narwhals/_pandas_like/series.py
- narwhals/_polars/dataframe.py
- narwhals/_spark_like/dataframe.py
- narwhals/_spark_like/expr.py
- narwhals/dataframe.py
- narwhals/expr.py
- narwhals/series.py
- tests/frame/unpivot_test.py
- tests/utils.py
> chore: reduce duplication, implement more methods at the Narwhals level rather than at the compliant level, fix CI from Ibis release

- narwhals/_expression_parsing.py
- narwhals/translate.py
- narwhals/typing.py
- narwhals/utils.py
Closes #1937
- Closes  #1937
`has_native_namespace`, `is_dataframe_like` were needed to resolve all the warnings
> chore(typing): add guards `is_compliant_*` (+ friends) 

- narwhals/utils.py
Adds `_is_range_index` to fix 6 warnings
> fix(typing): resolve remaining `utils.py` warnings

- .github/workflows/downstream_tests.yml
> ci:  add Validoopsie to downstream tests

- narwhals/functions.py
> chore: shrink `functions` module docstrings

- narwhals/_arrow/dataframe.py
- narwhals/_dask/dataframe.py
- narwhals/_dask/utils.py
- narwhals/_duckdb/dataframe.py
- narwhals/_interchange/dataframe.py
- narwhals/_pandas_like/dataframe.py
- narwhals/_polars/dataframe.py
- narwhals/_spark_like/dataframe.py
- narwhals/_spark_like/expr.py
- narwhals/dataframe.py
- narwhals/functions.py
- narwhals/schema.py
- narwhals/series.py
- narwhals/translate.py
- narwhals/utils.py
- tests/utils_test.py
- Related issue #1942
- Little bit of #1942
- When combined with another change (https://github.com/narwhals-dev/narwhals/discussions/1657#discussioncomment-12054784), a lot of cases might become one-liners
- Generally, just reducing the amount of repetition
> chore: widen `parse_version` to accept packages

- .github/workflows/downstream_tests.yml
> ci: add pointblank in downstream test

- tpch/execute.py
- tpch/generate_data.py
- tpch/queries/q1.py
- tpch/queries/q10.py
- tpch/queries/q11.py
- tpch/queries/q12.py
- tpch/queries/q13.py
- tpch/queries/q14.py
- tpch/queries/q15.py
- tpch/queries/q16.py
- tpch/queries/q17.py
- tpch/queries/q18.py
- tpch/queries/q19.py
- tpch/queries/q2.py
- tpch/queries/q20.py
- tpch/queries/q21.py
- tpch/queries/q22.py
- tpch/queries/q3.py
- tpch/queries/q4.py
- tpch/queries/q5.py
- tpch/queries/q6.py
- tpch/queries/q7.py
- tpch/queries/q8.py
- tpch/queries/q9.py
> ci: validate tpch query results

- narwhals/_arrow/dataframe.py
> chore(typing): resolve `_arrow.dataframe` warnings

- narwhals/_arrow/series.py
- narwhals/_pandas_like/series.py
- narwhals/_polars/series.py
- narwhals/series.py
> chore: minor series.py fixes, dedupe a little

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.26.0

- tests/series_only/hist_test.py
> tests: skip cudf hist tests

- narwhals/_spark_like/dataframe.py
this helps us get ready for pyspark 4.0 (and also helps with running sqlframe tests locally - they're still a bit off being runnable in CI, but are getting closer)
> chore: use toArrow in PySpark 4.0+

- narwhals/_arrow/dataframe.py
- narwhals/_dask/dataframe.py
- narwhals/_dask/utils.py
- narwhals/_duckdb/dataframe.py
- narwhals/_duckdb/utils.py
- narwhals/_expression_parsing.py
- narwhals/_ibis/dataframe.py
- narwhals/_interchange/dataframe.py
- narwhals/_pandas_like/dataframe.py
- narwhals/_polars/namespace.py
- narwhals/_spark_like/dataframe.py
- narwhals/_spark_like/utils.py
- narwhals/dataframe.py
> chore: alias named expressions at narwhals level

- narwhals/_arrow/dataframe.py
- narwhals/_arrow/expr.py
- narwhals/_arrow/namespace.py
- narwhals/_arrow/series.py
- narwhals/_expression_parsing.py
- narwhals/_pandas_like/dataframe.py
- narwhals/_pandas_like/expr.py
- narwhals/_pandas_like/namespace.py
- narwhals/_pandas_like/series.py
- narwhals/_polars/namespace.py
- narwhals/dataframe.py
Feeling about 10kg lighter after this
> chore: parse series and ndarrays as expressions

- narwhals/dataframe.py
- narwhals/stable/v1/__init__.py
> chore: clean up flatten and extract

- narwhals/_arrow/namespace.py
- narwhals/_dask/namespace.py
- narwhals/_duckdb/namespace.py
- narwhals/_pandas_like/namespace.py
- narwhals/_spark_like/namespace.py
- narwhals/functions.py
- narwhals/stable/v1/__init__.py
> chore: simplify when implementation

- .github/workflows/pytest.yml
- tests/conftest.py
> ci: remove `pyspark` from Windows CI

- tests/expr_and_series/sum_horizontal_test.py
> test: add test for `sum_horizontal` with column transformation

- .github/workflows/downstream_tests.yml
Introduced in [pointblank#60](https://github.com/posit-dev/pointblank/pull/60)
> ci: update pointblank deps to test downstream in ci

- narwhals/_arrow/selectors.py
- narwhals/_dask/selectors.py
- narwhals/_duckdb/selectors.py
- narwhals/_pandas_like/selectors.py
- narwhals/_spark_like/selectors.py
- narwhals/dataframe.py
I just have to git blame myself 🥲
> fix: various typos

- pyproject.toml
Updates our config to use https://mypy.readthedocs.io/en/stable/config_file.html#confval-pretty
Example of what this looks like for some of the issues prior to (#2007) fixes:
> ci(typing): use `tool.mypy.pretty = true`

- narwhals/dependencies.py
- https://typing.readthedocs.io/en/latest/spec/narrowing.html#typeis
> chore(typing): Upgrade `TypeGuard` -> `TypeIs`

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.27.0

- .github/workflows/downstream_tests.yml
- narwhals/_arrow/series.py
- narwhals/_duckdb/expr.py
- narwhals/_pandas_like/series.py
- narwhals/expr.py
- narwhals/series.py
- tests/expr_and_series/is_in_test.py
> fix: `is_in` was raising when used with empty list

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.27.1

- narwhals/_dask/namespace.py
- narwhals/_duckdb/namespace.py
- narwhals/_pandas_like/namespace.py
- narwhals/_spark_like/namespace.py
> perf: Avoid double-parsing in concat_str

- .pre-commit-config.yaml
We're accidentally fork-bombing ourselves here
> ci: dont pass filenames to mypy in pre-commit

- CONTRIBUTING.md
- Related issue #1893
- Closes
> docs: Add standardized test failure patterns to CONTRIBUTING.md

- narwhals/_expression_parsing.py
- narwhals/expr.py
- narwhals/expr_cat.py
- narwhals/stable/v1/__init__.py
> chore: use `change_metadata_kind`

- narwhals/_expression_parsing.py
- narwhals/expr.py
> chore: use combine_metadata more

- narwhals/_expression_parsing.py
- narwhals/dataframe.py
- narwhals/expr.py
- narwhals/expr_cat.py
- narwhals/functions.py
- narwhals/selectors.py
- narwhals/stable/v1/__init__.py
- utils/check_api_reference.py
> refactor: Use real class for `ExprMetadata` 

- narwhals/_arrow/expr.py
- narwhals/_arrow/namespace.py
- narwhals/_dask/expr.py
- narwhals/_dask/namespace.py
- narwhals/_duckdb/expr.py
- narwhals/_duckdb/namespace.py
- narwhals/_pandas_like/expr.py
- narwhals/_pandas_like/namespace.py
- narwhals/_spark_like/expr.py
- narwhals/_spark_like/namespace.py
> chore(typing): Remove unused `pyright` ignores

- narwhals/_arrow/expr.py
- narwhals/_dask/dataframe.py
- narwhals/_dask/expr.py
- narwhals/_duckdb/expr.py
- narwhals/_pandas_like/dataframe.py
- narwhals/_pandas_like/expr.py
- narwhals/_pandas_like/utils.py
- narwhals/_spark_like/expr.py
- narwhals/expr.py
- narwhals/selectors.py
Either evaluate prior to defining the function, or skip converting a tuple to a list
> perf: avoid repeating constant iteration

- .github/workflows/mkdocs.yml
- CONTRIBUTING.md
- pyproject.toml
> docs: remove griffe fork to build docs

- narwhals/_dask/dataframe.py
- narwhals/_dask/expr.py
- narwhals/_dask/expr_dt.py
- narwhals/_dask/group_by.py
- narwhals/_dask/namespace.py
- narwhals/_dask/selectors.py
- narwhals/_dask/utils.py
- pyproject.toml
- https://github.com/narwhals-dev/narwhals/pull/2064#issuecomment-2676872619
Just following up some things I temporarily added to #2064.
Sadly this is about all that I can do, given the typing coverage of (https://github.com/dask/dask)
> chore(typing): Resolve `_dask` errors

- narwhals/expr_str.py
- narwhals/series_str.py
Partial implementation of the issue to:
* expr_str
* series_str
> chore: concise_docstrings (#2068)

- narwhals/_arrow/dataframe.py
- narwhals/_dask/dataframe.py
- narwhals/_dask/group_by.py
- narwhals/_dask/namespace.py
- narwhals/_dask/utils.py
- narwhals/_duckdb/dataframe.py
- narwhals/_duckdb/utils.py
- narwhals/_pandas_like/dataframe.py
- narwhals/_spark_like/dataframe.py
- narwhals/_spark_like/namespace.py
- narwhals/_spark_like/utils.py
- tests/expr_and_series/over_test.py
- tests/frame/join_test.py
- tests/frame/schema_test.py
- tests/frame/select_test.py
> perf: only validate duplicate column names when collecting for duckdb/pyspark/dask

- narwhals/_dask/dataframe.py
- narwhals/_duckdb/dataframe.py
- narwhals/_spark_like/dataframe.py
- narwhals/_spark_like/utils.py
thanks @dangotbanned for highlighting this area of improvement!
> perf: use cached property for schema/columns lazy frames

- docs/api-reference/implementation.md
- docs/api-reference/index.md
- mkdocs.yml
- https://github.com/narwhals-dev/narwhals/pull/1917#issuecomment-2631508299
- https://github.com/narwhals-dev/narwhals/pull/1917#discussion_r1941635784
> docs: add `Implementation` page

- narwhals/group_by.py
- Think this is pretty straightforward
- Tiny reduction in LOC is a bonus
> chore(typing): fix `group_by`

- docs/api-reference/expr_str.md
- docs/api-reference/series_str.md
- narwhals/_arrow/expr_str.py
- narwhals/_arrow/series_str.py
- narwhals/_dask/expr_str.py
- narwhals/_duckdb/expr_str.py
- narwhals/_pandas_like/expr_str.py
- narwhals/_pandas_like/series_str.py
- narwhals/_spark_like/expr_str.py
- narwhals/expr_str.py
- narwhals/series_str.py
- tests/expr_and_series/str/split_test.py
- tests/utils.py
* implemented without inclusive option (https://docs.pola.rs/api/python/dev/reference/expressions/api/polars.Expr.str.split.html)
* support for _arrow, _dask, _duckdb, spark_like
* support for pandas_like(pyarrow backed)
> feat: str.split (#1932)

- narwhals/_arrow/series.py
- narwhals/_duckdb/expr.py
- narwhals/_pandas_like/series.py
- narwhals/expr.py
- narwhals/series.py
- tests/expr_and_series/fill_null_test.py
> fill_null with expression

- .github/workflows/check_tpch_queries.yml
- .github/workflows/downstream_tests.yml
- narwhals/_pandas_like/expr.py
> chore: simplify pandas-like over

- narwhals/_pandas_like/expr.py
- tests/expr_and_series/over_test.py
> feat: Add support for pandas-like `.diff().over(group)`

- narwhals/_arrow/expr.py
- narwhals/_dask/expr.py
- narwhals/_duckdb/expr.py
- narwhals/_pandas_like/expr.py
- narwhals/expr.py
- Follow-up to (#2106)
- Resolves https://github.com/narwhals-dev/narwhals/pull/2106/files#r1976489510
https://github.com/narwhals-dev/narwhals/pull/2106/files#r1976617360
> Thanks for explaining @janpipek!
> 
> I was expecting the same thing there as the annotation didn't change - only the description in [#2106 (files)](https://github.com/narwhals-dev/narwhals/pull/2106/files#diff-8dbec323eb770e099734f31eb6dd160668841972f5549ea2d00779ea65853ec5)
> 
> No worries - I've opened #2129 to address it 🙂
> fix(typing): Include `Expr` in `fill_null` signature

- narwhals/_arrow/group_by.py
- narwhals/_arrow/series.py
- narwhals/_arrow/utils.py
- Noticed this code during #2130 and was very lost in what it did
- Beyond being easier to read, I'm fairly sure this gets there in fewer steps
> refactor: Simplify `ArrowGroupBy.__iter__`

- narwhals/_pandas_like/expr.py
- narwhals/_spark_like/expr.py
- narwhals/_spark_like/utils.py
- tests/expr_and_series/over_test.py
missed this in #https://github.com/narwhals-dev/narwhals/pull/2138
> fix: pass ddof down in std().over() for pandas-like

- tests/expr_and_series/over_test.py
- tests/expr_and_series/rank_test.py
- tests/frame/select_test.py
- utils/bump_version.py
> ci: get cuDF test suite green again

- narwhals/_expression_parsing.py
Seems like it was dropped in https://github.com/narwhals-dev/narwhals/pull/1614/commits/5ac8d11a28c4407afaea5fa1baef19280da45d9a
> docs: remove non-existent "args"

- narwhals/functions.py
- narwhals/stable/v1/__init__.py
> docs: Add info in `nw.when` regarding chained statements

- narwhals/_arrow/series.py
- pyproject.toml
- tests/series_only/scatter_test.py
> fix: pyarrow scatter was returning incorrect results when indices were not sorted

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.29.1

- .github/workflows/downstream_tests.yml
Due to [plotly#5019](https://github.com/plotly/plotly.py/pull/5019)
> ci: fix plotly requirement files in downstream tests

- narwhals/_pandas_like/series.py
- tests/conftest.py
> perf: simplify pandas scatter

- narwhals/_arrow/expr.py
- narwhals/_arrow/series.py
- narwhals/_dask/expr.py
- narwhals/_pandas_like/expr.py
- narwhals/_pandas_like/series.py
- narwhals/_polars/expr.py
- narwhals/_polars/series.py
- narwhals/_spark_like/expr.py
- narwhals/expr.py
- narwhals/series.py
- narwhals/typing.py
- pyproject.toml
- tests/expr_and_series/rolling_sum_test.py
> feat: add `rolling_sum` for sqlframe and pyspark

- narwhals/group_by.py
- narwhals/selectors.py
- narwhals/series_cat.py
- narwhals/series_dt.py
- narwhals/series_list.py
- narwhals/series_str.py
* series_dt
* series_cat
* series_list
* selectors
* series_str.py fix
* group_by
> docs: even more concise docstrings (#2068)

- pyproject.toml
- Pretty common to see in a `pyproject.toml`
- Helps to *demystify* the shorter codes
- Also connects some dots between currently ignored rules
- Should help in the future if those are reconsidered
CI failure is fixed by
> docs(ruff): Improve config docs

- narwhals/translate.py
- tests/translate/get_native_namespace_test.py
> feat: support passing multiple arguments positionally to get_native_namespace

- tests/expr_and_series/cum_sum_test.py
- tests/expr_and_series/rolling_sum_test.py
- tests/expr_and_series/str/to_datetime_test.py
- tests/expr_and_series/struct_/field_test.py
> test: fixup cudf failures

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.30.0

- utils/bump_version.py
> ci: update bump_version.py so it correctly pushes to stable branch

- narwhals/_arrow/dataframe.py
- narwhals/_dask/dataframe.py
- narwhals/_duckdb/dataframe.py
- narwhals/_duckdb/utils.py
- narwhals/_pandas_like/dataframe.py
- narwhals/_polars/dataframe.py
- narwhals/_spark_like/dataframe.py
- narwhals/translate.py
> chore: minor duckdb cleanup

- README.md
- docs/ecosystem.md
> docs: add metalearners to used by/ecosystem

- narwhals/functions.py
- narwhals/stable/v1/__init__.py
- narwhals/translate.py
- narwhals/typing.py
- tests/frame/invalid_test.py
- tests/translate/from_native_test.py
> fix(typing): Match lazy `@overload` in `nw.from_native(...)`

- docs/basics/dataframe_conversion.md
- narwhals/dataframe.py
- narwhals/functions.py
- narwhals/series.py
- narwhals/stable/v1/__init__.py
- tests/new_series_test.py
- tpch/execute.py
Closes #1888
- https://github.com/narwhals-dev/narwhals/pull/2218#discussion_r1997221835
- Closes #1888
> docs: replace remaining `native_namespace` refs

- tpch/execute.py
- Closes #2167 with a workaround for reading parquet files instead of using `nw.scan_parquet` directly
> test: Run TPCH with SQLFrame

- Makefile
- pyproject.toml
> chore: pin typing dependnecies

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.31.0

- .github/workflows/extremes.yml
- tests/expr_and_series/cast_test.py
> ci: skip Polars nightly if notebook is still running

- .github/workflows/mkdocs.yml
- Closes #2258
This should fix it. 🤞 @MarcoGorelli This will only be triggered by push to `main`. Can I add (temporarily) the `workflow_dispatch`trigger to run this manually to test?
> doc: fix docs CI

- .github/workflows/mkdocs.yml
- Related #2259 
Ok the test run (I didn't deploy I just run `mkdocs --help`) is green: https://github.com/narwhals-dev/narwhals/actions/runs/13979804902/job/39142325905?pr=2260
3rd time's the charm @MarcoGorelli
> docs: fix docs CI dependencies

- narwhals/_compliant/dataframe.py
- narwhals/_compliant/selectors.py
- narwhals/_dask/utils.py
- narwhals/_duckdb/utils.py
- narwhals/_expression_parsing.py
- narwhals/_spark_like/utils.py
- narwhals/exceptions.py
- narwhals/expr.py
- narwhals/functions.py
- narwhals/selectors.py
- tests/expr_and_series/clip_test.py
- tests/expr_and_series/double_selected_test.py
- tests/expr_and_series/is_between_test.py
- tests/expr_and_series/when_test.py
- tests/frame/invalid_test.py
- tests/frame/reindex_test.py
- utils/check_api_reference.py
> feat: track whether expressions are multi-output, unify error messages

- narwhals/_spark_like/expr.py
- narwhals/_spark_like/utils.py
- tests/expr_and_series/cum_max_test.py
> feat: add `cum_max` for PySpark

- narwhals/_spark_like/expr.py
- tests/expr_and_series/cum_min_test.py
> feat: add `cum_min` to PySpark

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.32.0

- narwhals/_duckdb/expr.py
- narwhals/_spark_like/expr.py
- tests/expr_and_series/cum_count_test.py
- tests/expr_and_series/cum_prod_test.py
> feat: add `cum_count` and `cum_prod` to PySpark and DuckDB

- narwhals/_polars/dataframe.py
> fix: fixup polars join version check throwing unnecessary deprecation warning for outer join

- narwhals/_arrow/dataframe.py
- tests/frame/clone_test.py
Closes #2207
- Closes #2207
- Mentioned in https://github.com/narwhals-dev/narwhals/pull/1644#issuecomment-2750891356
> feat: Add `DataFrame.clone` for `pyarrow`

- narwhals/_duckdb/expr.py
- tests/expr_and_series/arithmetic_test.py
- tests/expr_and_series/over_test.py
- tests/frame/add_test.py
> fix: use specialised duckdb functions for std_pop/std_samp/var_pop/var_samp

- narwhals/dataframe.py
- tests/expr_and_series/arithmetic_test.py
- tests/expr_and_series/over_test.py
- tests/frame/add_test.py
closes #2281
- https://github.com/narwhals-dev/narwhals/pull/2289#issuecomment-2751849474
> ci: fixup for duckdb pre 1.3

- narwhals/_compliant/expr.py
- narwhals/_dask/expr.py
- narwhals/_duckdb/expr.py
- narwhals/_spark_like/expr.py
- tests/expr_and_series/rolling_mean_test.py
> feat: add `rolling mean` for lazy backends

- narwhals/_duckdb/expr.py
- tests/expr_and_series/is_duplicated_test.py
- tests/expr_and_series/is_unique_test.py
> feat: Add `DuckDBExpr.is_unique()` method

- narwhals/functions.py
- tests/read_scan_test.py
> feat: Allow spark-like backends in `scan_csv` function

- narwhals/_compliant/expr.py
- narwhals/_dask/expr.py
- narwhals/_duckdb/expr.py
- narwhals/_spark_like/expr.py
- tests/expr_and_series/rolling_std_test.py
- tests/expr_and_series/rolling_var_test.py
> feat: add `rolling_var` and `rolling_std` for lazy backends

- CONTRIBUTING.md
> docs: Expand contributing guidelines

- tests/expr_and_series/cum_sum_test.py
This operation is supported, but we don't have a test for it
To ensure it keeps working, let's add one 
> test: add test for shift->cum_sum

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.33.0

- narwhals/_pandas_like/dataframe.py
👋 `new_column_name_to_new_column_map`
> chore: simplify `PandasLikeDataFrame.with_columns`

- tests/group_by_test.py
https://github.com/narwhals-dev/narwhals/pull/2195#discussion_r2028319526
> test: fix wrong reason in `group_by_test.py`

- narwhals/_duckdb/dataframe.py
- narwhals/_spark_like/dataframe.py
- tests/frame/unique_test.py
> enh: support `unique(keep='none')` for pyspark/sqlframe

- narwhals/_duckdb/dataframe.py
- narwhals/_duckdb/expr.py
- narwhals/_duckdb/utils.py
- narwhals/_spark_like/utils.py
> chore: use less sql for duckdb, do extra validation

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.34.0

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.34.1

- narwhals/_dask/expr.py
- narwhals/_pandas_like/expr.py
- tests/expr_and_series/over_test.py
> fix: `nw.len().over` was unnecessarily raising for pandas-like

- tests/expr_and_series/over_test.py
- tests/v1_test.py
> test: xfail cudf where necessary

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.35.0

- tests/expr_and_series/dt/convert_time_zone_test.py
- tests/expr_and_series/dt/datetime_duration_test.py
- tests/expr_and_series/dt/replace_time_zone_test.py
- tests/expr_and_series/dt/timestamp_test.py
> chore: use `pytest.skip` for dt tests which can never pass

- narwhals/_duckdb/dataframe.py
- narwhals/_duckdb/series.py
- narwhals/_duckdb/utils.py
> chore: DuckDB dtype parsing using `.id` and `.children` properties

- narwhals/_duckdb/utils.py
- tests/series_only/cast_test.py
- tests/v1_test.py
> feat: Add support for DuckDB Enum

- narwhals/_dask/dataframe.py
- narwhals/_duckdb/dataframe.py
- narwhals/_spark_like/dataframe.py
- Related [issue #\<issue number\>](https://github.com/narwhals-dev/narwhals/pull/2325#discussion_r2051684847)
- Closes #2403
> perf: cache `columns` property for lazyframe's

- narwhals/_spark_like/expr.py
- tests/expr_and_series/rank_test.py
> feat: Support for additional rank methods in spark-like

- narwhals/_pandas_like/utils.py
- tests/expr_and_series/dt/replace_time_zone_test.py
> test: update tests so cudf is green

- narwhals/_pandas_like/utils.py
- narwhals/_polars/utils.py
- narwhals/dtypes.py
- tests/dtypes_test.py
- tests/stable_api_test.py
- utils/check_api_reference.py
> perf: Delay converting categories to tuple for Enum

- tests/frame/getitem_test.py
> test: fixup test suite for cudf

- .github/workflows/downstream_tests.yml
- Related [comment](https://github.com/narwhals-dev/narwhals/pull/2427#issuecomment-2825617270)
> ci: fix pointblank downstream test

- narwhals/_dask/expr_dt.py
- narwhals/_dask/group_by.py
- narwhals/_dask/namespace.py
- narwhals/_dask/utils.py
Forgot that I resolved this in (https://github.com/narwhals-dev/narwhals/pull/2274/commits/8fd6fe7b51555b3a7ccf97f1a2dc67b0350fc4f3)
> chore: Use less confusing `dask` imports

- narwhals/_compliant/dataframe.py
- narwhals/_compliant/series.py
- narwhals/_polars/dataframe.py
- Related issue #2416
All of these are equivalent, follow-up to (#2393)
> chore(typing): Simplify some `__getitem__` annotations

- tests/group_by_test.py
> tests: un-xfail polars group by expr streaming

- .github/workflows/pytest-pyspark.yml
- .github/workflows/typing.yml
> chore: remove `setuptool<78` in CI

- narwhals/_dask/expr.py
- narwhals/_pandas_like/expr.py
- tests/expr_and_series/fill_null_test.py
> enh: Support `fill_null(strategy=...).over(order_by=...)` for pandas-like

- narwhals/_arrow/dataframe.py
- narwhals/_polars/dataframe.py
- narwhals/dependencies.py
- narwhals/typing.py
- narwhals/utils.py
Closes #2422, #2410
- Closes #2422
- Closes #2410
Wasn't expecting to fix (#2410) 😅
> chore(typing): fix `is_sized_multi_index_selector`

- tests/frame/lazy_test.py
- Related https://github.com/narwhals-dev/narwhals/pull/2432#discussion_r2063431857
We can also add future backends with less effort this way, since they're just specified in `@pytest.mark.parametrize`
> test: Simplify `test_lazy_backend`

- narwhals/utils.py
- tests/repr_test.py
> fix: fix nw.Series repr for Polars

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.37.1

- .github/workflows/downstream_tests.yml
> ci: switch from pdm to uv in tea-tasting downstream tests

- .github/workflows/downstream_tests.yml
> ci: reenable tubular tests

- tests/expr_and_series/is_finite_test.py
- tests/expr_and_series/str/to_uppercase_to_lowercase_test.py
- tests/selectors_test.py
- tpch/generate_data.py
> ci: Fix TPCH test data generation in CI

- narwhals/functions.py
- pyproject.toml
> patch: Filter `is_sparse` DeprecationWarning in test suite

- narwhals/expr_cat.py
- narwhals/expr_dt.py
- narwhals/expr_list.py
- narwhals/expr_name.py
- narwhals/expr_str.py
- narwhals/expr_struct.py
> chore: Use `_with_callable` for narwhals expr namespaces

- narwhals/dataframe.py
- narwhals/expr.py
- narwhals/functions.py
- narwhals/series.py
- narwhals/stable/v1/__init__.py
> docs: Use Google-Style admonition

- narwhals/_dask/expr_dt.py
- narwhals/_pandas_like/series_dt.py
- narwhals/_pandas_like/utils.py
- tests/expr_and_series/dt/truncate_test.py
- tests/expr_and_series/str/to_uppercase_to_lowercase_test.py
> test: cudf fixup, address pandas deprecationwarning

- narwhals/_pandas_like/dataframe.py
- narwhals/_pandas_like/series.py
- narwhals/_pandas_like/utils.py
- Closes #2490
Not sure that it makes it significantly simpler, but enough to not fail the ruff rules
> chore: Simplify `PandasLikeDataFrame.pivot`

- narwhals/_compliant/expr.py
- narwhals/_dask/expr.py
- narwhals/_duckdb/expr.py
- narwhals/_spark_like/expr.py
Nice reduction for all the lazy backends
> refactor: Add `LazyExpr.alias`

- narwhals/_spark_like/expr_dt.py
- tests/expr_and_series/dt/truncate_test.py
- tests/expr_and_series/str/to_uppercase_to_lowercase_test.py
Will close #2498
- Closes #2498
- https://github.com/narwhals-dev/narwhals/pull/2505#issuecomment-2858467509
> test: Fix `pyspark` truncate in ci

- tests/translate/from_native_test.py
> test: Ensure `from_native(...).to_native()` returns original object

- narwhals/dependencies.py
- Closes #2509
---
@MarcoGorelli not sure how to go about testing this one 🤔
> patch: Fix `is_pyspark_connect_dataframe`

- README.md
- docs/ecosystem.md
> docs: adding Validoopsie to used by

- narwhals/dependencies.py
- tests/translate/from_native_test.py
- tests/translate/narwhalify_test.py
> fix: Catch ``ImportError`` when checking for PySparkConnect

- docs/installation.md
- narwhals/__init__.py
- pyproject.toml
> release: Bump version to 1.38.2

- docs/basics/order_dependence.md
- tests/expr_and_series/unary_test.py
> ci: SQLFrame compat

- narwhals/_spark_like/dataframe.py
- narwhals/_spark_like/expr.py
- narwhals/_spark_like/utils.py
> chore: Simplify PySpark std and var

- narwhals/_duckdb/expr.py
- narwhals/_duckdb/expr_dt.py
- narwhals/_duckdb/expr_str.py
Nothing exciting here, just spotted a couple stragglers
> chore: Use `not_implemented` some more

- pyproject.toml
> release: Bump version to 1.39.0

- pyproject.toml
> release: Bump version to 1.39.1

- .github/workflows/extremes.yml
- README.md
- docs/index.md
> docs: Update docs to reflect Ibis support

- docs/ecosystem.md
> docs: Minor rewording around Ibis commparison

- tests/expr_and_series/skew_test.py
> test: add Expr.skew test

- narwhals/_spark_like/expr.py
- narwhals/functions.py
- tests/expr_and_series/skew_test.py
- [Related comment](https://github.com/narwhals-dev/narwhals/pull/2561#issuecomment-2888338995)
> fix: PySpark like tests

- .github/workflows/typing.yml
- narwhals/_expression_parsing.py
> TYP: Enforce 100% type completeness score (PyRight)

- narwhals/_arrow/expr.py
- narwhals/_compliant/expr.py
- narwhals/_dask/expr.py
- narwhals/_duckdb/expr.py
- narwhals/_ibis/expr.py
- narwhals/_pandas_like/expr.py
- narwhals/_polars/expr.py
- narwhals/_spark_like/expr.py
- Resolves 1 task for (#2525)
We could still probably rewrite this in a *more composable* way - so there's less boilerplate - but not super urgent
> chore: Redo `CompliantExpr.from_column_indices`

- docs/overhead.md
closes https://github.com/narwhals-dev/narwhals/issues/2471
> docs: Rewrite overhead section

- narwhals/_ibis/expr_str.py
- narwhals/_spark_like/expr_str.py
- narwhals/utils.py
> chore: Move `_is_naive_format` helper function into utils.py

- .github/CODE_OF_CONDUCT.md
- pyproject.toml
> docs: Update code of conduct to use organisational email

- .github/workflows/mkdocs.yml
- docs/concepts/order_dependence.md
- docs/generating_sql.md
- mkdocs.yml
- pyproject.toml
> docs: Add docs on how to use Narwhals to generate SQL

- pyproject.toml
> release: Bump version to 1.40.0

- narwhals/_duckdb/expr.py
- narwhals/_duckdb/expr_dt.py
- narwhals/_duckdb/expr_list.py
- narwhals/_duckdb/expr_str.py
- narwhals/_duckdb/expr_struct.py
> chore: rename `_input` to `expr` in `_duckdb`

- narwhals/_dask/expr.py
- narwhals/_dask/expr_dt.py
- narwhals/_dask/expr_str.py
- narwhals/_ibis/expr.py
- narwhals/_ibis/expr_dt.py
- narwhals/_ibis/expr_list.py
- narwhals/_ibis/expr_str.py
- narwhals/_ibis/expr_struct.py
- narwhals/_spark_like/expr.py
- narwhals/_spark_like/expr_dt.py
- narwhals/_spark_like/expr_str.py
- narwhals/_spark_like/expr_struct.py
> chore: rename `_input` to `expr` in `_spark_like`, `_ibis`, and `_dask`

- .github/workflows/typing.yml
> ci: Use Pyright-cov to enforce 100% type coverage

- .github/workflows/downstream_tests.yml
- .pre-commit-config.yaml
- CONTRIBUTING.md
- Makefile
- narwhals/_duckdb/dataframe.py
- narwhals/_duckdb/expr.py
- pyproject.toml
> chore: Use DuckDB 1.3 for typing, remove make typing from `pre-commit`, update `CONTRIBUTING`

- narwhals/_duckdb/expr.py
- narwhals/_ibis/expr.py
- narwhals/_spark_like/expr.py
> chore: simplify `broadcast` for spark-like and ibis

- narwhals/_spark_like/namespace.py
> fix: Fix CI for PySpark 4.0

- .github/workflows/pytest.yml
- narwhals/_pandas_like/dataframe.py
- pyproject.toml
> ci: pin modin for now

- narwhals/translate.py
- tests/translate/from_native_test.py
> fix: spark-like `pass_through=True, eager_only=True` interaction

- tests/translate/get_native_namespace_test.py
> ci: fix native namespace test

- tests/frame/getitem_test.py
> ci: remove outdated cudf xfail

- tests/frame/getitem_test.py
> ci: Fix cudf again

- narwhals/utils.py
- Related #1968
Long awaited follow-up to (#1968)
> chore: Remove outdated `_has_default_index` comment

- narwhals/stable/v1/__init__.py
- tests/v1_test.py
> test: add extra `to_dict` test for v1

- .github/workflows/check_tpch_queries.yml
- narwhals/series.py
> docs: update example of `Series` constructor

- narwhals/functions.py
- tests/from_dict_test.py
- tests/from_numpy_test.py
- tests/new_series_test.py
> feat: improve error messages for IO functions

- pyproject.toml
> release: Bump version to 1.41.1

- pyproject.toml
> release: Bump version to 1.42.0

- narwhals/_duckdb/namespace.py
- narwhals/_spark_like/namespace.py
- tests/expr_and_series/horizontal_broadcasts_test.py
- tests/expr_and_series/sum_horizontal_test.py
>  enh: push down over for _horizontal expressions 

- .github/workflows/extremes.yml
- narwhals/_arrow/dataframe.py
> fix: fix pyarrow nightly compat

- narwhals/_ibis/expr.py
- narwhals/_spark_like/expr.py
- tests/expr_and_series/diff_test.py
- tests/expr_and_series/is_first_distinct_test.py
- tests/expr_and_series/is_last_distinct_test.py
- tests/expr_and_series/shift_test.py
> fix: align null ordering position for ibis

- narwhals/_utils.py
- utils/check_api_reference.py
While working on something else I spotted this 🤷🏼‍♀️
> chore: Remove unused utility functions

- tests/expr_and_series/is_in_test.py
[kaggle notebook](https://www.kaggle.com/code/lukeimurfather/narwhals-pre-release-test-cudf)
@MarcoGorelli is this a regression in polars?
> ci: xfail polars_lazy[gpu] to make CI green

- narwhals/_polars/dataframe.py
- [Comment](https://github.com/narwhals-dev/narwhals/pull/2683#discussion_r2151516994)
> refactor: Introduce `PolarsBaseFrame` parent class

- narwhals/stable/v1/__init__.py
- tests/stable_v1_dependencies_test.py
> fix: `narwhals.stable.v1.dependencies` was importing `narwhals.dependencies`

- pyproject.toml
> release: Bump version to 1.43.1

- .github/workflows/downstream_tests.yml
- https://github.com/narwhals-dev/narwhals/actions/runs/15758798248/job/44420431101?pr=2598
[Plotly switched to `uv`](https://github.com/plotly/plotly.py/commit/eb95abc4d52a9c3ed231c5509ee9cc12804d1107#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47) :)
> ci: update plotly downstream tests

- narwhals/_polars/utils.py
- tests/expr_and_series/is_in_test.py
- tests/expr_and_series/lit_test.py
- tests/utils.py
> fix: update tests for `cuDF` `25.08.00a`

- narwhals/_arrow/utils.py
- narwhals/_dask/utils.py
- narwhals/_pandas_like/utils.py
- narwhals/_utils.py
> fix: raise NotImplementedError instead of returning it

- pyproject.toml
> release: Bump version to 1.44.0

- narwhals/_spark_like/expr.py
- narwhals/_spark_like/namespace.py
- narwhals/_spark_like/utils.py
- tests/expr_and_series/division_by_zero_test.py
> ci: use try_divide in PySpark for division

- .github/workflows/downstream_tests.yml
- .github/workflows/extremes.yml
- .github/workflows/pytest-pyspark.yml
- .github/workflows/pytest.yml
- .github/workflows/random_ci_pytest.yml
- .github/workflows/typing.yml
different jobs are installing different versions, so i think they need different cache suffixes?
> ci: pin sqlglot, use different cache_suffixes for different jobs

- narwhals/_duckdb/expr_dt.py
- narwhals/_duckdb/expr_list.py
- narwhals/_duckdb/expr_str.py
- narwhals/_duckdb/expr_struct.py
- narwhals/_ibis/expr_dt.py
- narwhals/_ibis/expr_str.py
- narwhals/_spark_like/expr_dt.py
- narwhals/_spark_like/expr_list.py
- narwhals/_spark_like/expr_str.py
- narwhals/_spark_like/expr_struct.py
- narwhals/expr.py
- narwhals/expr_cat.py
- narwhals/expr_dt.py
- narwhals/expr_list.py
- narwhals/expr_name.py
- narwhals/expr_str.py
- narwhals/expr_struct.py
> chore: use _with_elementwise more for DuckDB/spark-like

- tests/expr_and_series/str/to_datetime_test.py
- tests/expr_and_series/unary_test.py
- tests/frame/group_by_test.py
- tests/v1_test.py
- tpch/execute.py
- tpch/queries/q14.py
- tpch/queries/q9.py
tiny random insignificant things
> chore: clean assorted

- narwhals/_duckdb/utils.py
> chore: use `descending` and `nulls_last` for duckdb `window_expression`

- tests/v1_test.py
> chore: fixup error message for duckdb nightly

- tests/expr_and_series/cast_test.py
- tests/expr_and_series/over_test.py
- tests/expr_and_series/rank_test.py
> ci: cudf tests fixup

- .github/workflows/downstream_tests.yml
> ci: unpin mypy in altair job

- tests/dependencies/is_narwhals_dataframe_test.py
- tests/dependencies/is_narwhals_series_test.py
- tests/expr_and_series/order_dependent_lazy_test.py
- tests/series_only/gather_every_test.py
- tests/series_only/head_test.py
- tests/series_only/sort_test.py
- tests/series_only/tail_test.py
- tests/translate/from_native_test.py
- tests/v1_test.py
> chore: more v1 test suite cleanups

- README.md
- docs/ecosystem.md
With Formulaic 1.2.0 released at long last, it's time to officially join the Narwhals ranks :).
> docs: Add `formulaic` to ecosystem list

- CONTRIBUTING.md
- docs/overhead.md
- narwhals/_pandas_like/dataframe.py
> perf: avoid redundant copies in `join` for pandas

- narwhals/_duration.py
- narwhals/_ibis/expr_dt.py
- narwhals/_ibis/utils.py
- tests/expr_and_series/dt/offset_by_test.py
> Enh: Accept negative offsets in `Expr.dt.offset_by()`

- .github/workflows/extremes.yml
- .github/workflows/pytest-pyspark.yml
- .github/workflows/pytest.yml
- .github/workflows/random_ci_pytest.yml
- pyproject.toml
- Related issue #2818
Opening as draft to see what else is affected by pyproject.toml configs.
Also, probably it's better to _not_ have it by default but enabling it in GHA. Thoughts on this?
> test: Use pytest-xdist in GHA

- tests/conftest.py
> test(typing): Annotate `pytest_addoption`

- narwhals/_pandas_like/utils.py
- tests/expr_and_series/str/contains_test.py
- tests/expr_and_series/str/to_uppercase_to_lowercase_test.py
- tests/frame/interchange_to_pandas_test.py
- tests/no_imports_test.py
- tests/repr_test.py
> fix: Fixup logic for new pandas str type

- pyproject.toml
> release: Bump version to 1.47.1

- .pre-commit-config.yaml
- utils/import_check.py
- https://github.com/astral-sh/ruff/pull/18907
- https://github.com/astral-sh/ruff/releases/tag/0.12.4
- https://discord.com/channels/1235257048170762310/1272835922924273694/1395712325683642500
> ci: bump `ruff==0.12.4`

- tests/expr_and_series/dt/offset_by_test.py
Unlucky timing to open _another_ PR just after the sqlframe release 😄
> tests: sqlframe fully passes `offset_by` test

- .github/workflows/downstream_tests.yml
- README.md
- docs/ecosystem.md
- Closes #2852 and adds gt-extras to used by/ecosystem
> ci: Add gt-extras to downstream tests

- narwhals/_arrow/group_by.py
- narwhals/_compliant/typing.py
- narwhals/_dask/group_by.py
- narwhals/_pandas_like/group_by.py
- tests/frame/group_by_test.py
- Related issue #2385
Opening as draft: I am expecting some old versions to break
> feat: Allow `all` and `any` in group by context

- pyproject.toml
> release: Bump version to 1.48.0

- .github/workflows/extremes.yml
@baggiponte keeping us on our feet regarding uv stuff
> ci: Use uv for nightly pandas

- pyproject.toml
> release: Bump version to 1.48.1

- narwhals/stable/v1/__init__.py
- tests/v1_test.py
> fix `get_column` typing for `stable.v1`

- narwhals/_dask/expr_dt.py
- tests/expr_and_series/division_by_zero_test.py
- tests/expr_and_series/dt/timestamp_test.py
- tests/expr_and_series/name/suffix_test.py
- tests/modern_polars/pivot_test.py
- tests/modern_polars/unpivot_test.py
> ci: fixup cudf tests

- narwhals/_exceptions.py
- narwhals/_pandas_like/group_by.py
- narwhals/_spark_like/dataframe.py
- narwhals/_utils.py
- narwhals/dataframe.py
- narwhals/dependencies.py
- narwhals/stable/v1/__init__.py
- narwhals/translate.py
- tests/dependencies/is_native_dataframe_series_raise_test.py
- tests/translate/get_native_namespace_test.py
- #1444
- https://github.com/vega/altair/discussions/3862
> feat: Warn, instead of raising, in `is_*_dataframe` / `is_*_series` functions

- narwhals/_duckdb/expr.py
- narwhals/_ibis/expr.py
- narwhals/_spark_like/expr.py
- narwhals/_sql/expr.py
> chore: factor out log from SparkLike, DuckDB, and Ibis

- .pre-commit-config.yaml
- narwhals/dataframe.py
- narwhals/series.py
> docs: Enable darglint for dataframe and series modules

- narwhals/dtypes.py
- tests/dtypes_test.py
- Closes https://github.com/narwhals-dev/narwhals/issues/2877
> feat: Add `is_boolean` method to `DType`.

- narwhals/_polars/expr.py
- narwhals/_polars/series.py
- narwhals/_polars/utils.py
- See https://github.com/narwhals-dev/narwhals/pull/2940#discussion_r2256658300
> chore: Simplify polars `.list.unique`

- docs/api-reference/expr_list.md
- docs/api-reference/series_list.md
- narwhals/_arrow/series_list.py
- narwhals/_compliant/any_namespace.py
- narwhals/_compliant/expr.py
- narwhals/_duckdb/expr_list.py
- narwhals/_ibis/expr_list.py
- narwhals/_pandas_like/series_list.py
- narwhals/_polars/expr.py
- narwhals/_polars/series.py
- narwhals/_polars/utils.py
- narwhals/_spark_like/expr_list.py
- narwhals/expr_list.py
- narwhals/series_list.py
- tests/expr_and_series/list/contains_test.py
- Closes #2936 
- `pyarrow` support (https://github.com/apache/arrow/issues/33295)
> feat: add `list.contains`

- docs/api-reference/typing.md
- narwhals/_arrow/dataframe.py
- narwhals/_compliant/dataframe.py
- narwhals/_compliant/namespace.py
- narwhals/_pandas_like/dataframe.py
- narwhals/_polars/dataframe.py
- narwhals/_polars/namespace.py
- narwhals/dataframe.py
- narwhals/functions.py
- narwhals/typing.py
- Part of https://github.com/narwhals-dev/narwhals/issues/2116#issuecomment-3122104794
I was going to do this *after* `IntoBackend`, but it turned out to be a much simpler change
> feat(typing): Add `IntoSchema` alias

- narwhals/_duckdb/expr_dt.py
- narwhals/_ibis/expr_dt.py
- narwhals/_ibis/utils.py
- narwhals/_spark_like/expr_dt.py
- narwhals/_sql/expr.py
- narwhals/_sql/expr_dt.py
> chore: Refactor SQLExprDateTimeNamespace

- .github/workflows/downstream_tests.yml
Drive by https://github.com/Nixtla/hierarchicalforecast/pull/384/
> ci: Fix hierarchicalforecast downstream test

- pyproject.toml
> release: Bump version to 2.1.1

- .pre-commit-config.yaml
- narwhals/_compliant/group_by.py
- narwhals/_namespace.py
- narwhals/_utils.py
- narwhals/dataframe.py
- narwhals/dtypes.py
- narwhals/expr.py
- narwhals/expr_cat.py
- narwhals/expr_dt.py
- narwhals/expr_list.py
- narwhals/expr_name.py
- narwhals/expr_str.py
- narwhals/expr_struct.py
- narwhals/group_by.py
- narwhals/schema.py
- narwhals/series.py
- narwhals/series_cat.py
- narwhals/series_dt.py
- narwhals/series_list.py
- narwhals/series_str.py
- narwhals/series_struct.py
- narwhals/stable/v1/__init__.py
> docs: remove now-redundant "returns" sections from docstrings

- tests/modern_polars/ewm_mean_test.py
- Related issues #2949
Observed first in https://github.com/narwhals-dev/narwhals/pull/2949 random versions tox (3.9, ubuntu-latest)
> fix(tests): correct polars version in modern polars ewm_mean_test

- .github/workflows/extremes.yml
- narwhals/_utils.py
- tests/expr_and_series/map_batches_test.py
- tests/utils.py
> Revert "fix: Use importlib for polars version (#2952)", xfail `map_batches` test for now

- pyproject.toml
> release: Bump version to 2.1.2

- tests/frame/top_k_test.py
> chore: xfail top k multiple in old polars

- pyproject.toml
> release: Bump version to 2.2.0

- pyproject.toml
I don't feel like risking to ignore any test we run
> fix(ci): Disallow `sqlframe==3.39.3`

- narwhals/_expression_parsing.py
> chore: remove (internal) `ExprKind.NARY`

- narwhals/_plan/aggregation.py
- narwhals/_plan/arrow/dataframe.py
- narwhals/_plan/arrow/functions.py
- narwhals/_plan/categorical.py
- narwhals/_plan/common.py
- narwhals/_plan/demo.py
- narwhals/_plan/dummy.py
- narwhals/_plan/expr.py
- narwhals/_plan/expr_expansion.py
- narwhals/_plan/functions.py
- narwhals/_plan/lists.py
- narwhals/_plan/literal.py
- narwhals/_plan/name.py
- narwhals/_plan/operators.py
- narwhals/_plan/options.py
- narwhals/_plan/protocols.py
- narwhals/_plan/ranges.py
- narwhals/_plan/strings.py
- narwhals/_plan/temporal.py
- narwhals/_plan/when_then.py
- narwhals/_plan/window.py
> refactor(expr-ir): Clearing out the cobwebs

- narwhals/_plan/aggregation.py
- narwhals/_plan/common.py
- narwhals/_plan/expr.py
- narwhals/_plan/expr_expansion.py
- narwhals/_plan/name.py
- Child of #2572
Should help to reduce some boilerplate
- https://docs.python.org/3.13/library/copy.html#copy.replace
> refactor(expr-ir): `copy.replace` most `with_*` methods

- pyproject.toml
> release: Bump version to 2.3.0

- narwhals/_plan/common.py
- narwhals/_plan/expr_rewrites.py
- narwhals/_plan/meta.py
- narwhals/_plan/operators.py
- narwhals/_plan/schema.py
- narwhals/_plan/selectors.py
- narwhals/_plan/when_then.py
- Child of #3066
Always forgetting about the 100 limit for narwhals
> refactor(expr-ir): Make use of long lines

- narwhals/_plan/arrow/namespace.py
- narwhals/_plan/protocols.py
> refactor(expr-ir): Shrink protocols

- narwhals/expr.py
- tests/expr_and_series/fill_null_test.py
closes https://github.com/narwhals-dev/narwhals/issues/3104
> fix: allow for `fill_null` with aggregate expression

- narwhals/_compliant/series.py
- narwhals/_expression_parsing.py
- narwhals/_polars/series.py
- narwhals/dataframe.py
- narwhals/group_by.py
- narwhals/series.py
- narwhals/stable/v1/__init__.py
- tests/frame/group_by_test.py
Reverts narwhals-dev/narwhals#3106
> Revert "chore: simplify parsing expressions in group-by"

- .pre-commit-config.yaml
- pyproject.toml
- tests/expr_and_series/bool_test.py
- tests/expr_and_series/is_in_test.py
- tests/expr_and_series/lit_test.py
- tests/expr_and_series/median_test.py
- tests/expr_and_series/quantile_test.py
- tests/expr_and_series/str/to_datetime_test.py
- tests/frame/concat_test.py
- tests/frame/estimated_size_test.py
- tests/frame/get_column_test.py
- tests/frame/getitem_test.py
- tests/frame/join_test.py
- tests/frame/select_test.py
- tests/series_only/from_iterable_test.py
- tests/translate/from_native_test.py
- tests/translate/narwhalify_test.py
- tests/v1_test.py
- tests/v2_test.py
> chore: Upgrade ruff to `v0.13.0` and fix related issues in `tests/`

- tests/pickle_test.py
> test(typing): fix `pickle_test` using `Sequence`

- narwhals/_dask/expr.py
- narwhals/_duckdb/expr.py
- narwhals/_duckdb/utils.py
- narwhals/_pandas_like/expr.py
- narwhals/_spark_like/expr.py
- narwhals/_sql/expr.py
- tests/expr_and_series/n_unique_test.py
> enh: support `n_unique` with `over` across all backends

- narwhals/_duckdb/expr.py
- tests/expr_and_series/skew_test.py
> enh: support `skew` with `over`

- pyproject.toml
> release: Bump version to 2.6.0
