README.md, tpch/q1.py
@anmyachev just FYI, in case you were interested in this (and, especially, if you were interested in collaborating)
=> add modin to readme

tests/hypothesis/test_join.py
Repeating the data inside each frame, if not, `join` can't find data to link. Same for columns to join, they have to be the same left and right. Unless I'm missing something of course. 
Feedback very welcome.
=> Hypothesis testing DataFrame.join

tests/hypothesis/test_join.py
=> Add nulls & inf to hypothesis test for DataFrame.join

README.md
=> add trailblazing user: timebasedcv

narwhals/dataframe.py, narwhals/functions.py, narwhals/utils.py, tests/test_common.py
Trying to close https://github.com/MarcoGorelli/narwhals/issues/46
=> Adding error message when different libraries are used

tests/hypothesis/test_concat.py, tests/utils.py
Added `min` and `max` to floats, because the test was failing when `inf` was included in the data.
=> Testing concat with hypothesis

narwhals/expression.py
Here's a screenshot of the rendered docstring:
=> add docstring for Expr.alias

narwhals/expression.py
=> add docstring for Expr.all

narwhals/expression.py
I re-used the one sentence description from polars.Expr.std,
followed the style of examples that are already in the docs (max(), any())
I've chosen for df's/values that were somewhere halfway between the already present examples and the ones from polars examples, so I'm curious if they're okay
=> std usage example added

narwhals/expression.py
=> mean usage example added

narwhals/dependencies.py
got this trick from scikit-learn 😎
=> use sys.modules for dependencies

README.md
I'm a fan of Ibis, and I've been made aware that my initial comparison didn't go down very well with them.
In my head, it was intended more of as a "here's justification for why I wanted to make yet another tool, where Ibis wouldn't be sufficient", but I understand that that's not the way it came across, and I'm sorry.
I've tried making the comparison fairer and friendlier - tagging @lostmygithubaccount in case you have comments. I'm a fan of Ibis and would like to be on good terms 🤗 Hopefully this strikes the right balance?
=> Make Ibis comparison friendlier

CONTRIBUTING.md
=> Add pre-commit instructions

docs/api-reference/expressions_str.md, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/utils.py, narwhals/expression.py, narwhals/translate.py, pyproject.toml, tests/expr/test_to_datetime.py
=> add str.to_datetime

narwhals/series.py
I moved over to the series methods and tried the documentation for `drop_nulls()`. Followed directions in https://github.com/narwhals-dev/narwhals/issues/71.
=> series drop nulls documentation

docs/api-reference/expressions_dt.md, docs/api-reference/series_dt.md, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/series.py, narwhals/expression.py, narwhals/series.py, tests/test_dt.py
=> add temporal methods

narwhals/_pandas_like/series.py, tests/expr/n_unique_test.py
=> align n_unique

narwhals/dependencies.py
Partially addresses https://github.com/narwhals-dev/narwhals/issues/71.
=> Add docstrings to get_modin(), get_cudf(), get_pyarrow()

tests/test_dt.py
=> fix total_minutes test, convert to nanoseconds instead of milliseconds

narwhals/expression.py
=> DOC: fill in missing docstrings for `Expr.sample`

docs/api-reference/expressions_dt.md, docs/api-reference/series_dt.md, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/series.py, narwhals/expression.py, narwhals/series.py, tests/test_dt.py
=> add temporal methods for calculating total seconds and milli/micro/nano seconds

narwhals/_pandas_like/series.py, narwhals/expression.py, tests/expr/is_between_test.py
=> Add docstring for Expr.is_between()

narwhals/functions.py, narwhals/utils.py, tests/test_invalid.py
closes https://github.com/narwhals-dev/narwhals/issues/39
=> Concat should preserve laziness

narwhals/_pandas_like/dataframe.py, narwhals/dataframe.py, tests/frame/slice_test.py
Closes #131 
Narwhals looks great, so this was partly me just wanting to see how the internals work. Happy to contribute as well if this is what you had in mind for the issue.
=> Allow slicing eager dataframes

narwhals/series.py
Also added missing arguments to docstrings for consistency.
=> Add Series.cast() and update other docstrings

narwhals/_pandas_like/series.py, narwhals/series.py
=> DOC: fill in missing docstrings for Series.all and Series.sort

narwhals/series.py
=> DOC: fill in missing docstrings for Series.is_in

narwhals/expression.py, tests/test_series.py
Addressing: https://github.com/narwhals-dev/narwhals/issues/101
=> Improve error message for is_in

narwhals/_pandas_like/expr.py, narwhals/expression.py, tests/expr/filter_test.py
closes #197
sorry just doing this in a rush as I'd like to use it in thursday's talk
=> fixup filter

narwhals/series.py
=> DOC: fill in missing docstrings for Series.sample

narwhals/_pandas_like/series.py, narwhals/dependencies.py, narwhals/series.py
We shouldn't `convert_dtypes` on behalf of the user
Also, correctly the record slightly on the dependencies
=> dont convert_dtypes in is_in

narwhals/series.py
=> DOC: fill in missing docstrings for Series.is_between

docs/api-reference/series.md, narwhals/_pandas_like/series.py, narwhals/series.py, tests/test_series.py, utils/check_api_reference.py
closes https://github.com/narwhals-dev/narwhals/issues/202 .. (maybe)
=> Adding Series.zip_with

CONTRIBUTING.md, docs/how_it_works.md, mkdocs.yml, narwhals/dependencies.py
=> add how it works section

.github/workflows/extremes.yml, docs/api-reference/expressions.md, docs/api-reference/series.md, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/series.py, narwhals/expression.py, narwhals/series.py, tests/test_common.py, tests/test_series.py
Fix #203 by introducing `.quantile(...)` for Expr and Series.
I am opening this as draft because of two main reasons:
=> feat: series and expr quantile

docs/api-reference/expressions_dt.md, docs/api-reference/series_dt.md, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/series.py, narwhals/expression.py, narwhals/series.py, tests/test_dt.py
I accidentally force pushed so I need to open a new one.
=> nanoseconds

.github/pull_request_template.md
https://github.com/narwhals-dev/narwhals/issues/218
Issue template on another PR
Feedback welcome
=> Template for PR 

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml
Part of https://github.com/narwhals-dev/narwhals/issues/218
After your (kind 😇) feedback , I'll work on docs improvement and feature request templates... if y'all want. : ) 
Here is how it looks on a mock project:
[New Issue.pdf](https://github.com/narwhals-dev/narwhals/files/15485281/New.Issue.pdf)
=> Proposed template for bug reporting

.github/ISSUE_TEMPLATE/doc_issue.yml
- Related issue #
- Closes #218
Feedback welcome  - checking out my master piece (this template) :-)
=> Adding template for doc issue

narwhals/expression.py
=> Method.len

README.md
=> Fix image URL.

narwhals/dataframe.py
- Related issue #205 
- Closes #
Updated the docstrings for `DataFrame.unique` and `DataFrame.drop` to follow the template and format used in `Series` methods.
EDIT: i see the err, i'm on it!
=> Update df docstrings for unique and drop

narwhals/_pandas_like/series.py, narwhals/_pandas_like/utils.py, narwhals/dependencies.py, tests/test_series.py
=> Preserve dtype backend

narwhals/_pandas_like/utils.py, tests/series/cast_test.py
=> fixup cast to string for pandas

narwhals/expression.py
=> docs: added docstring for Col

narwhals/expression.py
=> simplify check

docs/api-reference/narwhals.md, narwhals/__init__.py, narwhals/utils.py, tests/utils_test.py
=> feat: implement narwhals.maybe_convert_dtypes

narwhals/dataframe.py
=> docs: updated docstrings for class DataFrame

docs/api-reference/narwhals.md, docs/basics/column.md, docs/basics/complete_example.md, docs/basics/dataframe.md, narwhals/__init__.py, narwhals/_pandas_like/utils.py, narwhals/dataframe.py, narwhals/expression.py, narwhals/series.py, narwhals/translate.py, tests/narwhalify_test.py, tpch/notebooks/q1/execute.ipynb, tpch/notebooks/q2/execute.ipynb, tpch/notebooks/q3/execute.ipynb, tpch/notebooks/q4/execute.ipynb, tpch/notebooks/q5/execute.ipynb, tpch/notebooks/q6/execute.ipynb, tpch/notebooks/q7/execute.ipynb
=> feat: add `narwhalify` decorator

narwhals/dataframe.py
=> update docstrings for methods

narwhals/_pandas_like/utils.py
=> perf: use copy=False in set_axis where possible

narwhals/expression.py
=> docs: added docstring for all()

docs/installation.md, narwhals/__init__.py, pyproject.toml, utils/bump_version.py
=> Bump version to 0.9.5

README.md, docs/index.md, docs/related.md, mkdocs.yml, tpch/notebooks/gpu/execute.ipynb, tpch/notebooks/q1/execute.ipynb, tpch/notebooks/q2/execute.ipynb, tpch/notebooks/q3/execute.ipynb, tpch/notebooks/q4/execute.ipynb, tpch/notebooks/q5/execute.ipynb, tpch/notebooks/q6/execute.ipynb, tpch/notebooks/q7/execute.ipynb, tpch/notebooks/q8/execute.ipynb
=> docs: add overhead section

README.md, docs/overhead.md, tpch/notebooks/q1/execute.ipynb, tpch/notebooks/q2/execute.ipynb, tpch/notebooks/q3/execute.ipynb, tpch/notebooks/q4/execute.ipynb, tpch/notebooks/q5/execute.ipynb, tpch/notebooks/q6/execute.ipynb, tpch/notebooks/q7/execute.ipynb
I've updated the notebooks to calculate the Ibis overhead too
The results are quite mixed - whilst their pandas backend has quite a heavy overhead, their Polars one looks pretty solid! I'm impressed
for now i'll just remove their mention on the `overhead` page, my mistake to have included it in the first place
=> bench: update notebooks

narwhals/series.py, tests/series/arithmetic_test.py
=> feat: implement series arithmetic

docs/api-reference/dataframe.md, narwhals/_pandas_like/dataframe.py, narwhals/dataframe.py, tests/frame/write_parquet_test.py
=> feat: add DataFrame.write_parquet

docs/installation.md, narwhals/__init__.py, pyproject.toml
=> Bump version to 0.9.6

.github/release-drafter.yml, CONTRIBUTING.md
=> docs: Contributing steps update

narwhals/dataframe.py, narwhals/expression.py, narwhals/selectors.py, narwhals/series.py, narwhals/translate.py, narwhals/utils.py, pyproject.toml
=> clean: format docstrings with ruff

.gitignore, CONTRIBUTING.md, noxfile.py, tests/test_common.py, tests/test_str.py
- Closes #292 
It is fairly minimal but I liked the tool, it is the first time I am using it though 🙈
=> test: nox for local testing

docs/api-reference/dataframe.md, docs/api-reference/series.md, narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/group_by.py, narwhals/_pandas_like/series.py, narwhals/_pandas_like/utils.py, narwhals/dataframe.py, narwhals/series.py, tests/test_common.py, tests/test_series.py, utils/check_api_reference.py
- Closes: Some related comment lost in the ether
TIL I've learned... we don't have `series.head()`
=> enh: dataframe and series `.item()`

docs/api-reference/dataframe.md, docs/api-reference/expressions.md, docs/api-reference/lazyframe.md, docs/api-reference/series.md, narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/series.py, narwhals/dataframe.py, narwhals/expression.py, narwhals/series.py, tests/test_common.py, tests/test_series.py
Introduces:
- DataFrame and LazyFrame `.tail()` method
- Series `.head()` and `tail()` methods
- Expr `.head()` and `tail()` methods
=> enh: `.head()` and `.tail()`

.github/workflows/publish_to_pypi.yml
- Closes #
The removed lines conflict with the release drafter
=> ci: Removed conflicting github release

narwhals/dataframe.py
- Related issue #205
I love the name of the `@nw.narwhalify` decorator! 😄
=> docs: Update docs for with_columns

.github/ISSUE_TEMPLATE/doc_issue.yml, .github/ISSUE_TEMPLATE/feature_request.yml
- Related issue #https://github.com/narwhals-dev/narwhals/issues/218
- Closes #
The template for the docs issues was not showing up, it had errors 😱.
=> ci: issue template correction

narwhals/_pandas_like/dataframe.py, requirements-dev.txt, tests/test_common.py, tests/test_invalid.py, tests/utils_test.py
=> perf: use fastpath in with_columns

CONTRIBUTING.md, README.md
=> web: add community calendar link

narwhals/dataframe.py
- Related issue #205  
- Closes #
I tried to follow the structure of the other docstring updates, i.e. explaining that you can write a custom function while also keeping the structure of the different examples. Let me know what you think and once you're happy with it I'll adapt the docstrings for `LazyFrame.select` accordingly.
=> docs: Update docs for select

docs/api-reference/expressions.md, docs/api-reference/series.md, narwhals/_pandas_like/expr.py, narwhals/expression.py, narwhals/series.py, tests/expr/len_test.py, tests/test_series.py
- Closes #322 
Let me know if tests are good enough!
=> enh: `Expr.len` and `Series.len`

narwhals/_pandas_like/series.py
=> chore: simplify Series

.github/ISSUE_TEMPLATE/bug_report.yml
- Closes #https://github.com/narwhals-dev/narwhals/issues/230
=> ci: Added show_versions() to issue template

mkdocs.yml, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/series.py, narwhals/dataframe.py, narwhals/expression.py, narwhals/series.py, narwhals/utils.py, tests/cat/get_categories_test.py, tests/test_invalid.py, utils/check_api_reference.py
=> feat: add cat.get_categories, make test numpy2.0 compatible

narwhals/_pandas_like/group_by.py, tests/group_by_test.py
=> fix: group-by(...).agg(nw.col(...).len()) was raising unnecessarily

narwhals/dataframe.py
- Related issue #205 
- Closes #
=> docs: Update documentation for group_by

narwhals/__init__.py, narwhals/_pandas_like/namespace.py, narwhals/_pandas_like/utils.py, narwhals/dtypes.py, tests/series/cast_test.py
=> feat: support Date dtype in Narwhals

docs/api-reference/dtypes.md, narwhals/__init__.py, narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/namespace.py, narwhals/_pandas_like/series.py, narwhals/_pandas_like/utils.py, narwhals/dtypes.py, tests/frame/schema_test.py
=> feat: add nw.Object dtype

docs/api-reference/series.md, narwhals/_pandas_like/series.py, narwhals/series.py, tests/series/to_list_test.py, utils/check_api_reference.py
=> feat: add Series.to_list

.github/ISSUE_TEMPLATE/config.yml
The `)` was a typo. Without it, it works.
=> Fixes discord link

narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/series.py
=> clean: assorted clean ups

narwhals/translate.py
- Related issue #
- Closes #
Very "atomic" PR. :) As suggested in #331 and on Discord, these functions should not be exposed in this file.
=> refactor: remove `get_` functions from translate

narwhals/_arrow/dataframe.py, narwhals/_arrow/series.py, narwhals/_pandas_like/dataframe.py, narwhals/dataframe.py, narwhals/translate.py, tests/frame/len_test.py, tests/frame/rows_test.py, tests/frame/schema_test.py
=> feat: add more methods to the pyarrow backend

docs/api-reference/dtypes.md, narwhals/__init__.py, narwhals/_arrow/namespace.py, narwhals/_arrow/utils.py, narwhals/_pandas_like/namespace.py, narwhals/_pandas_like/utils.py, narwhals/dtypes.py, tests/frame/schema_test.py, tests/series/test_common.py
=> feat: add duration dtype

docs/api-reference/dependencies.md, narwhals/dependencies.py, tests/dependencies/is_pandas_dataframe_test.py
=> feat: add is_pandas_dataframe

.pre-commit-config.yaml, narwhals/dependencies.py
=> feat: add typeguard for is_pandas_dataframe

.github/workflows/extremes.yml, narwhals/_pandas_like/utils.py, tests/series/test_common.py
=> fix: compatibility with old numpy versions

docs/api-reference/dtypes.md, narwhals/__init__.py, narwhals/_arrow/namespace.py, narwhals/_pandas_like/namespace.py, narwhals/_pandas_like/utils.py, narwhals/dtypes.py, tests/frame/schema_test.py, tests/series/cast_test.py
=> feat: add Unknown dtype

.pre-commit-config.yaml, utils/check_backend_completeness.py
=> chore: add Missing pyarrow methods script

tests/conftest.py, tests/series/arithmetic_test.py, tests/series/eq_ne_test.py, tests/series/to_frame_test.py, tests/series/to_list_test.py
=> chore: make constructor_series in conftest

docs/basics/complete_example.md, narwhals/_pandas_like/dataframe.py, narwhals/dataframe.py, tests/frame/test_common.py, tests/hypothesis/test_join.py
- Closes #301
I am concerned about cudf - I was not able to find a clear doc regarding join's (better called merge)  🤔
=> feat: cross join

tests/frame/test_common.py
=> chore: increase local test coverage to 100

narwhals/_arrow/dataframe.py, narwhals/_pandas_like/dataframe.py, narwhals/dataframe.py, tests/frame/slice_test.py
=> allow slicing by sequence

README.md
- Closes #
I’ve been attempting to contribute to the current repository, but I’ve found it challenging to locate the contributing guidelines. I believe it would be beneficial to include them in the README file.
=> docs: Add contributing guide link to README.md

narwhals/_arrow/series.py, tests/expr/cat/get_categories_test.py
=> feat: add .cat.get_categories to pyarrow

README.md
=> add Hamilton to README

narwhals/_arrow/series.py, tests/series/is_empty_test.py, tests/series/test_common.py, utils/check_backend_completeness.py
=> feat: add Series.is_empty

.github/workflows/extremes.yml, narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/group_by.py, narwhals/_pandas_like/series.py, narwhals/_pandas_like/utils.py, pyproject.toml, tests/frame/test_common.py, tests/frame/test_invalid.py, tests/frame/write_parquet_test.py, tests/hypothesis/test_join.py, tests/series/test_common.py, tests/test_utils.py, tests/tpch_q1_test.py
=> Try lowering minimum pandas

docs/why.md
- Closes #
This is just a suggestion, feel free to reject it!
=> docs: Change expression of merge example in `Why`

narwhals/_pandas_like/group_by.py, tests/conftest.py, tests/test_group_by.py
fixes the example from https://github.com/narwhals-dev/narwhals/issues/282#issuecomment-2208586002
- Closes #
=> fix: raise if complex pandas aggregation would return empty results

narwhals/_pandas_like/dataframe.py, narwhals/dataframe.py, tests/frame/test_common.py
=> patch: pandas-like drop hotfix

tests/frame/sort_test.py, tests/frame/test_common.py
towards https://github.com/narwhals-dev/narwhals/issues/401
- Closes #
=> chore: factor `sort_test` out of `test_common`

narwhals/_arrow/namespace.py, narwhals/_arrow/series.py, narwhals/_pandas_like/namespace.py, narwhals/_pandas_like/series.py
=> chore: make from_iterable private

narwhals/dataframe.py
- Closes #205 (or at least from the list I wrote)
Requires #394 to be merged to pass doctest-modules
=> docs: dataframe docstring via template

narwhals/_arrow/series.py, narwhals/_pandas_like/series.py, narwhals/dataframe.py, narwhals/series.py, pyproject.toml, tests/conftest.py, tests/series/array_dunder_test.py
=> fix: `dtype` could not be passed to Series.__array__

pyproject.toml
=> build: try reducing wheel size

docs/api-reference/dataframe.md, docs/api-reference/lazyframe.md, narwhals/_arrow/dataframe.py, narwhals/_pandas_like/dataframe.py, narwhals/dataframe.py, tests/conftest.py, tests/frame/clone_test.py, tests/frame/test_common.py
Mentioned in #355 
I am not very familiar with pyarrow Dataframes. What could be a clean way to implement copy/clone?
I added `NotImplementedError` as a placeholder, if we keep the error I will add a test
=> feat: add `clone` for dataframes

narwhals/dataframe.py, narwhals/expression.py, narwhals/series.py
=> chore: return Self more

docs/api-reference/expressions.md, docs/api-reference/series.md, narwhals/_arrow/expr.py, narwhals/_arrow/series.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/series.py, narwhals/expression.py, narwhals/series.py, tests/expr/abs_test.py
=> feat: Expr.Abs and Series.abs

narwhals/dataframe.py, narwhals/group_by.py
=> feat: add DataFrame.lazy and LazyFrame.lazy

narwhals/dataframe.py
=> Overload to dict

tests/frame/test_common.py, tests/frame/to_dict_test.py
=> chore: factor out to_dict test

.pre-commit-config.yaml, tpch/notebooks/gpu/execute.ipynb, tpch/notebooks/q1/execute.ipynb, tpch/notebooks/q2/execute.ipynb, tpch/notebooks/q21/execute.ipynb, tpch/notebooks/q3/execute.ipynb, tpch/notebooks/q4/execute.ipynb, tpch/notebooks/q5/execute.ipynb, tpch/notebooks/q6/execute.ipynb, tpch/notebooks/q7/execute.ipynb, tpch/notebooks/q8/execute.ipynb
=> chore: add nbstripout

tests/frame/select_test.py, tests/frame/test_common.py
Towards #401 
- Related issue #401 
- Closes #
=> clean: factor select_test out of test_common

narwhals/dataframe.py, narwhals/group_by.py
=> Generic groupby

tests/frame/double_test.py, tests/frame/test_common.py
- Related issue #401 
- Closes #
=> clean: factor double_test out of test_common

narwhals/dataframe.py, tests/expr/diff_test.py, tests/expr/fill_null_test.py, tests/expr/is_between_test.py, tests/expr/n_unique_test.py, tests/expr/shift_test.py
=> clean: assorted

tests/frame/rows_test.py, tests/frame/schema_test.py, tests/hypothesis/test_basic_arithmetic.py, tests/hypothesis/test_join.py
=> clean: use from_native in tests

narwhals/_arrow/dataframe.py, narwhals/_arrow/expr.py, narwhals/_arrow/namespace.py, narwhals/_arrow/series.py, narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/group_by.py, narwhals/_pandas_like/namespace.py, narwhals/_pandas_like/series.py, narwhals/_pandas_like/utils.py, narwhals/translate.py, narwhals/utils.py
=> clean: include `native` in some names / functions

README.md, docs/api-reference/narwhals.md, docs/api-reference/typing.md, docs/basics/column.md, docs/basics/complete_example.md, docs/basics/dataframe.md, docs/index.md, docs/quick_start.md, mkdocs.yml, narwhals/typing.py
=> docs: add page on type hints

narwhals/_arrow/dataframe.py, narwhals/_arrow/expr.py, narwhals/_arrow/namespace.py, narwhals/_arrow/series.py, narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/group_by.py, narwhals/_pandas_like/namespace.py, narwhals/_pandas_like/selectors.py, narwhals/_pandas_like/series.py, narwhals/_pandas_like/utils.py, narwhals/dataframe.py, narwhals/expression.py, narwhals/group_by.py, narwhals/series.py, narwhals/translate.py, narwhals/utils.py, tests/frame/test_common.py, utils/check_api_reference.py, utils/check_backend_completeness.py
=> perf: push down `parse_version`

narwhals/_arrow/series.py, tests/expr/diff_test.py
=> perf: simplify pyarrow diff

docs/installation.md, narwhals/__init__.py, pyproject.toml
=> Bump version to 0.9.29

narwhals/_pandas_like/group_by.py, narwhals/dataframe.py, narwhals/translate.py, tests/frame/instantiation_test.py, tests/frame/test_common.py
=> chore: simplify instantiation of top-level Narwhals objects

narwhals/_arrow/series.py, narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/series.py, narwhals/series.py, utils/check_api_reference.py
=> chore: simplify Series instantiation

.github/workflows/random_ci_pytest.yml, narwhals/_arrow/dataframe.py, narwhals/_arrow/expr.py, narwhals/_arrow/namespace.py, narwhals/_arrow/series.py, narwhals/_expression_parsing.py, narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/group_by.py, narwhals/_pandas_like/namespace.py, narwhals/_pandas_like/typing.py, narwhals/_pandas_like/utils.py, narwhals/expression.py, narwhals/typing.py
=> chore: Factor out expression parsing

pyproject.toml
=> Refactor: Re enable and fix Ruff's PLR5501 Check

narwhals/_arrow/series.py, narwhals/_arrow/utils.py, narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/utils.py, narwhals/stable/v1.py, narwhals/translate.py, pyproject.toml, tests/conftest.py, tests/frame/test_common.py, utils/check_api_reference.py
=> Refactor: Re enable and fix Ruff's TD Checks

narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/series.py, pyproject.toml, tests/frame/rows_test.py
=> Refactor: Re enable and fix Ruff's PD003 and PD009 Checks

pyproject.toml
=> Refactor: Re enable and fix Ruff's PT011 Check

narwhals/_pandas_like/group_by.py, narwhals/stable/v1.py, narwhals/translate.py, pyproject.toml
=> Refactor: Re enable and fix Ruff's ERA001 Check

pyproject.toml
=> Refactor: Re enable and fix Ruff's FBT003 Check

narwhals/dependencies.py, pyproject.toml
=> Refactor: Re enable and fix Ruff's ICN001 Check

.github/workflows/random_ci_pytest.yml, noxfile.py, pyproject.toml
=> ci: ignore em101, make random ci more robust (maybe)

docs/how_it_works.md, narwhals/_arrow/series.py, narwhals/_pandas_like/series.py, narwhals/dataframe.py, narwhals/expression.py, narwhals/functions.py, narwhals/group_by.py, narwhals/series.py, narwhals/stable/v1.py, narwhals/translate.py, narwhals/utils.py, tests/frame/clone_test.py, tests/frame/join_test.py
=> chore: rename some internal attributes for clarity

docs/extending.md, docs/how_it_works.md, narwhals/_arrow/dataframe.py, narwhals/_arrow/series.py, narwhals/_expression_parsing.py, narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/group_by.py, narwhals/_pandas_like/namespace.py, narwhals/_pandas_like/selectors.py, narwhals/_pandas_like/series.py, narwhals/_pandas_like/typing.py, narwhals/_pandas_like/utils.py, narwhals/translate.py, narwhals/utils.py, utils/check_backend_completeness.py
=> chore: Rename pandas objects

docs/api-reference/dataframe.md, narwhals/_arrow/dataframe.py, narwhals/_pandas_like/dataframe.py, narwhals/dataframe.py, pyproject.toml, tests/frame/get_column_test.py, utils/check_api_reference.py
=> feat: add DataFrame.get_column

narwhals/_pandas_like/dataframe.py
=> perf: avoid unnecessary reset_index in join

docs/overhead.md
- Closes #https://github.com/narwhals-dev/narwhals/issues/476
=> doc: Fix link

docs/installation.md, narwhals/__init__.py, pyproject.toml, utils/bump_version.py
=> Bump version to 1.0.5

narwhals/_arrow/utils.py, narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/group_by.py, narwhals/_pandas_like/utils.py, narwhals/dataframe.py, narwhals/expression.py, narwhals/functions.py, narwhals/translate.py, narwhals/utils.py, pyproject.toml, tests/utils.py
=> Refactor: Re enable and fix Ruff's TRY Checks

pyproject.toml
=> ci: ignore pandas internal warning

narwhals/_arrow/namespace.py, tests/expr/sum_horizontal_test.py
=> feat: pyarrow `sum_horizontal`

docs/installation.md, narwhals/__init__.py, pyproject.toml
=> Bump version to 1.0.6

tests/frame/join_test.py, tests/utils.py
=> chore: increase local coverage for join

narwhals/_arrow/dataframe.py, tests/frame/join_test.py, utils/check_backend_completeness.py
=> feat: implement inner join for arrow

narwhals/_arrow/expr.py, narwhals/_arrow/series.py, narwhals/series.py, tests/expr/arithmetic_test.py, tests/series/arithmetic_test.py, tests/tpch_q1_test.py
=> feat: add some right-hand operations for Arrow

.github/workflows/release-drafter.yml
- Related issue #https://github.com/narwhals-dev/narwhals/issues/490
- Closes #
I think it would be better to do like polars: https://github.com/pola-rs/polars/pull/17412
=> ci: run autolabeler also after PR title has been edited

narwhals/stable/v1.py, narwhals/translate.py, tests/stable_api_test.py
=> chore: rename `native_dataframe` in `from_native`

narwhals/translate.py, tests/translate/from_native_test.py
- Closes #470 
A tiny one for once 😂
=> feat: `from_native` raise invalid comb

docs/api-reference/dataframe.md, docs/api-reference/lazyframe.md, docs/api-reference/schema.md, mkdocs.yml, narwhals/__init__.py, narwhals/_arrow/dataframe.py, narwhals/_pandas_like/dataframe.py, narwhals/dataframe.py, narwhals/schema.py, narwhals/stable/v1.py, tests/frame/schema_test.py, tests/frame/test_common.py, tests/test_schema.py
- Closes #313 
Arguably complies with the current pattern, but could get cleaner if #461 finds its way in
=> feat: `collect_schema` method

README.md, docs/levels.md, mkdocs.yml, pyproject.toml, tests/series/cast_test.py
=> docs: rework README, remove ibis comparison

docs/installation.md, narwhals/__init__.py, pyproject.toml
=> Bump version to 1.1.0

narwhals/_arrow/dataframe.py, narwhals/_arrow/namespace.py, narwhals/_arrow/series.py, narwhals/_arrow/utils.py, tests/frame/lit_test.py
- Related issue #372
Assumes that `lit` takes a scalar value
=> feat: pyarrow `lit`

narwhals/_arrow/namespace.py, narwhals/_arrow/utils.py, tests/frame/test_common.py
=> feat: pyarrow `concat`

.github/workflows/check_docs_build.yml, docs/levels.md, tests/frame/join_test.py, utils/check_for_no_build_errors.py
=> ci: fix exception in code snippet, add check to CI

narwhals/_arrow/expr.py, narwhals/_arrow/series.py, tests/frame/test_common.py, utils/check_backend_completeness.py
- Related issue # https://github.com/narwhals-dev/narwhals/issues/372
- Closes #
I also added __invert__ so that we can reuse the test in `test_common.py`
Please let me know 🙏
=> feat: add `is_null` and `__invert__` to pyarrow series

narwhals/_arrow/dataframe.py, narwhals/_interchange/dataframe.py, narwhals/expression.py, narwhals/functions.py, narwhals/utils.py, pyproject.toml, tests/frame/write_parquet_test.py
- Closes #
Low hanging changes
=> chore: ruff rules

.github/workflows/downstream_tests.yml
=> ci: remove [dev] from sklego install

narwhals/_arrow/expr.py, tests/expr/cat/get_categories_test.py
It was not discussed, I hope I am not missing something
=> feat: `ArrowExprCatNamespace`

narwhals/_arrow/expr.py, narwhals/_arrow/series.py, tests/expr/len_test.py, utils/check_backend_completeness.py
- Related issue # #372 
- Closes #
nox is giving failed nightly version
=> feat: add len to pyarrow series and expr

.github/workflows/extremes.yml, .github/workflows/pytest.yml, tests/frame/test_invalid.py
=> ci: actually use pandas nightly in pandas-nightly build

.github/workflows/extremes.yml, narwhals/_arrow/group_by.py, narwhals/_arrow/namespace.py, narwhals/_pandas_like/group_by.py, tests/test_group_by.py, tests/tpch_q1_test.py, tpch/notebooks/q1/execute.ipynb, tpch/notebooks/q2/execute.ipynb, tpch/notebooks/q3/execute.ipynb, tpch/notebooks/q4/execute.ipynb, tpch/notebooks/q5/execute.ipynb, tpch/notebooks/q6/execute.ipynb, tpch/notebooks/q7/execute.ipynb
=> feat: allow nw.len in groupby for arrow

docs/installation.md, narwhals/__init__.py, pyproject.toml
=> Bump version to 1.1.1

narwhals/_arrow/series.py, narwhals/series.py, tests/series_only/test_common.py, utils/check_backend_completeness.py
=> feat: arrow series `zip_with`

narwhals/_arrow/group_by.py
=> chore: refactor agg_arrow

narwhals/_arrow/expr.py, narwhals/_arrow/series.py, tests/expr_and_series/sample_test.py, utils/check_backend_completeness.py
=> feat: arrow series `sample`

CONTRIBUTING.md, README.md
=> docs: fix link for community cal

README.md
=> docs: add note about funding to readme

docs/installation.md, narwhals/__init__.py, pyproject.toml
=> Bump version to 1.1.2

narwhals/_arrow/expr.py, narwhals/_arrow/series.py, tests/expr_and_series/n_unique_test.py, utils/check_backend_completeness.py
- Related issue #372
- Closes #
- [ x] Code follows style guide (ruff)
I implemented `n_unique`. A test file already existed, so I did not have to write a test
=> Implement n_unique

narwhals/expression.py
=> chore: rename internal extract_native function

narwhals/_arrow/expr.py, narwhals/_arrow/series.py, tests/expr_and_series/str/contains_test.py, tests/expr_and_series/str/head_test.py, tests/expr_and_series/str/slice_test.py, tests/expr_and_series/str/starts_with_ends_with_test.py, tests/expr_and_series/str/tail_test.py, tests/expr_and_series/str/to_datetime_test.py
- Related issue #372 (but hidden)
=> feat: arrow string namespace(s)

narwhals/_arrow/namespace.py, narwhals/_arrow/selectors.py, tests/test_selectors.py
The easiness of these implementations is really a joy
=> feat: arrow selectors

docs/related.md
best to avoid any potential conflict by removing all comparisons, I'm sorry for having made them in the first place
- Closes #
=> docs: reword "related projects" section, remove all Ibis comparisons

narwhals/dataframe.py, narwhals/expression.py, narwhals/group_by.py, narwhals/selectors.py, narwhals/series.py, narwhals/stable/v1.py, narwhals/translate.py, narwhals/utils.py
Docstring standardization using `@nw.narwhalify` and `df|s_any` pattern
=> docs: docstrings narwhalify-cation

narwhals/_arrow/expr.py, narwhals/_arrow/series.py, narwhals/_arrow/utils.py, tests/expr_and_series/arithmetic_test.py, tests/series_only/arithmetic_test.py
=> feat: implement truediv for pyarrow

docs/installation.md, narwhals/__init__.py, pyproject.toml
=> Bump version to 1.1.3

docs/api-reference/expressions.md, docs/api-reference/series.md, narwhals/_arrow/expr.py, narwhals/_arrow/series.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/series.py, narwhals/dataframe.py, narwhals/expression.py, narwhals/series.py, tests/expr_and_series/arg_true_test.py
=> feat: add DataFrame__contains__, Expr.arg_true, and Series.arg_true

README.md
=> Add additional sponsors and institutional partners to README

narwhals/_arrow/series.py, narwhals/_pandas_like/series.py, tests/series_only/test_common.py, tests/series_only/value_counts_test.py, utils/check_backend_completeness.py
=> feat: add arrow value_counts 

docs/api-reference/series.md, narwhals/_arrow/expr.py, narwhals/_arrow/series.py, narwhals/_pandas_like/series.py, narwhals/_polars/series.py, narwhals/series.py, tests/expr_and_series/sort_test.py, tests/expr_and_series/unary_test.py, tests/expr_and_series/unique_test.py, tests/series_only/to_dummy_test.py, utils/check_api_reference.py, utils/check_backend_completeness.py
=> feat: `Series.to_dummies`, arrow `sort` and `unique`

docs/installation.md, narwhals/__init__.py, pyproject.toml
=> Bump version to 1.1.4

narwhals/_pandas_like/dataframe.py
=> perf: fastpath for simple select in pandas-like

tests/frame/item_test.py, tests/frame/test_common.py
=> chore: factor `item_test` out of `test_common`

tests/frame/concat_test.py, tests/frame/test_common.py
=> chore: factor `concat_test` out of `test_common`

docs/installation.md, narwhals/__init__.py, pyproject.toml
=> Bump version to 1.1.5

narwhals/_arrow/expr.py, narwhals/_arrow/series.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/series.py, narwhals/_polars/series.py, narwhals/expr.py, narwhals/series.py, tests/expr_and_series/sort_test.py
- [Related ~issue~ comment](https://github.com/narwhals-dev/narwhals/pull/577#discussion_r1686927536)
=> feat: add `nulls_last` argument in `Series/Expr.sort` 

narwhals/_pandas_like/dataframe.py, tests/frame/with_columns_test.py, tests/series_only/value_counts_test.py
closes #571 
closes #593 
- Closes #
=> feat: allow non-string columns names more for pandas

narwhals/_arrow/dataframe.py, narwhals/_arrow/series.py, narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/series.py, narwhals/_polars/series.py, narwhals/series.py, narwhals/stable/v1.py, pyproject.toml, tests/series_only/value_counts_test.py
Expands on `Series.value_counts` available arguments to match polars 1.0
=> feat: `Series.value_count` spec enhancement 

narwhals/translate.py
=> chore: reoder definitions in from_native

narwhals/_arrow/dataframe.py, tests/frame/rows_test.py
=> feat: pyarrow dataframe `iter_rows`

narwhals/_arrow/dataframe.py, narwhals/_arrow/namespace.py, narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/group_by.py, narwhals/_pandas_like/namespace.py, narwhals/_polars/dataframe.py, narwhals/dataframe.py, narwhals/expr.py, narwhals/group_by.py
=> chore: remove some unnecessary flattens

narwhals/_arrow/expr.py, narwhals/_arrow/series.py, tests/expr_and_series/quantile_test.py, tests/series_only/test_common.py, utils/check_backend_completeness.py
=> feat: arrow `quantile` method

docs/api-reference/narwhals.md, narwhals/__init__.py, narwhals/_arrow/series.py, narwhals/functions.py, narwhals/stable/v1.py, tests/from_dict_test.py
=> feat: add from_dict

docs/api-reference/narwhals.md, narwhals/__init__.py, narwhals/_arrow/namespace.py, narwhals/_pandas_like/namespace.py, narwhals/expr.py, narwhals/stable/v1.py, tests/expr_and_series/any_horizontal_test.py
=> feat: `any_horizontal` function

README.md, docs/extending.md, docs/levels.md
=> docs: document PyArrow as "full" support

narwhals/_polars/namespace.py
=> fix: correct Polars version check for pl.len function

narwhals/functions.py, narwhals/stable/v1.py, tests/from_dict_test.py
- Closes #603 
Code is ugly :|
=> feat: add `schema` argument to `from_dict` function

narwhals/_arrow/dataframe.py, narwhals/_arrow/expr.py, narwhals/_arrow/namespace.py, narwhals/_arrow/selectors.py, narwhals/_arrow/series.py, narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/group_by.py, narwhals/_pandas_like/namespace.py, narwhals/_pandas_like/selectors.py, narwhals/_pandas_like/series.py, narwhals/_pandas_like/utils.py, narwhals/_polars/dataframe.py, narwhals/_polars/expr.py, narwhals/_polars/namespace.py, narwhals/_polars/series.py, narwhals/functions.py, narwhals/translate.py, narwhals/utils.py, tests/frame/join_test.py
=> chore: extend `Implementation` for all backends

narwhals/_arrow/series.py, tests/series_only/is_between_test.py
- Related issue # #372 
- Closes #
=> feat : added arrow `is_between` and `is_between_test.py`

utils/check_backend_completeness.py
- Related issue # #372 
- Closes #
I'm sorry I forgot to remove series.is_between from backend completness
=> cleaning: remove series.is_between from backend completness

README.md, docs/related.md, docs/roadmap.md
=> docs: fix typo in README, update roadmap + related projects

docs/installation.md, narwhals/__init__.py, pyproject.toml
=> release: Bump version to 1.1.6

docs/api-reference/typing.md, docs/basics/complete_example.md, docs/levels.md, docs/other/pandas_index.md, narwhals/dataframe.py, narwhals/expr.py, narwhals/group_by.py, narwhals/selectors.py, narwhals/series.py, narwhals/stable/v1.py, narwhals/translate.py, narwhals/utils.py
=> docs: replace `df_any`/`s_any` with `df`/`s`

narwhals/_arrow/dataframe.py, narwhals/_pandas_like/dataframe.py, narwhals/dataframe.py, narwhals/stable/v1.py, tests/frame/slice_test.py
=> feat: allow slicing by tuple of sequences of ints

narwhals/dataframe.py, tests/frame/slice_test.py
=> feat: raise informative error if getitem is used in unsupported manner

docs/api-reference/dataframe.md, docs/api-reference/expr.md, docs/api-reference/lazyframe.md, docs/api-reference/series.md, narwhals/_arrow/dataframe.py, narwhals/_arrow/expr.py, narwhals/_arrow/series.py, narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/series.py, narwhals/dataframe.py, narwhals/expr.py, narwhals/series.py, tests/expr_and_series/gather_every_test.py, tests/frame/gather_every_test.py
Just something I was planning to add :)
=> feat: `gather_every` methods

docs/installation.md, narwhals/__init__.py, pyproject.toml
=> release: Bump version to 1.1.7

narwhals/_arrow/series.py
- Related issue #610 
- Closes  #610 
Replaced our current implementation of to_dummies with SO solution and @FBruzzesi optimized it, so now we have a solution that is faster and more memory friendly
=> perf: optimizing arrow to_dummies 

.github/workflows/extremes.yml, narwhals/_dask/dataframe.py, narwhals/_dask/expr.py, narwhals/_dask/namespace.py, narwhals/_dask/utils.py, narwhals/dependencies.py, narwhals/translate.py, requirements-dev.txt, tests/dask_test.py
Alright, let's start stubbing this out 🥳 🚀 🎸 
As a follow-up, we'll need to add nightlies to `extremes.yml`
- Closes #
=> feat: Add initial (and very minimal) support for Dask.DataFrame

narwhals/_dask/expr.py, tests/dask_test.py
=> feat: add shift for Dask Dataframe

narwhals/translate.py
=> fix dask typo

narwhals/dependencies.py, narwhals/translate.py
=> fix: fix dask version in dask backend

narwhals/_dask/expr.py, tests/dask_test.py
=> feat: add cum_sum for dask

narwhals/_dask/expr.py, tests/dask_test.py
=> feat: added dask `Expr.__mul__` and test cases

narwhals/dependencies.py, tests/dask_test.py, tests/expr_and_series/gather_every_test.py
=> chore: replace constructor_with_series with constructor in gather_every_test

narwhals/_dask/expr.py, narwhals/_dask/namespace.py, tests/dask_test.py
=> feat: add `starts_with` for dask

narwhals/_dask/expr.py, narwhals/dependencies.py, narwhals/translate.py, tests/dask_test.py
- Closes #
Hey @MarcoGorelli what about the tests for dunder methods - I noticed there's no specific test for `Expr.__add__` or can we treat the with_column test as such? 
edit: Okay I figured it out. test_with_columns indeed covers for add/sub/mul, cool!
=> feat: added dask `Expr.__sub__`

narwhals/dependencies.py, tests/expr_and_series/is_in_test.py, tests/expr_and_series/sort_test.py, tests/series_only/arithmetic_test.py, tests/series_only/filter_test.py, tests/series_only/is_between_test.py, tests/series_only/is_sorted_test.py, tests/series_only/null_count_test.py, tests/series_only/operators_test.py, tests/series_only/test_common.py, tests/series_only/to_dummy_test.py, tests/series_only/to_frame_test.py, tests/series_only/to_list_test.py, tests/series_only/value_counts_test.py
=> chore: replace constructor_series with constructor

tests/expr_and_series/gather_every_test.py, tests/expr_and_series/is_duplicated_test.py, tests/expr_and_series/is_first_distinct_test.py, tests/expr_and_series/is_last_distinct_test.py, tests/expr_and_series/is_unique_test.py, tests/expr_and_series/max_test.py, tests/expr_and_series/mean_test.py, tests/expr_and_series/min_test.py, tests/expr_and_series/sum_test.py, tests/expr_and_series/unique_test.py
=> chore: use constructor instead of constructor_series in tests more

tests/frame/schema_test.py, tests/frame/test_common.py
=> chore: factor `test_schema` and `test_collect_schema` out of `test_common`

narwhals/_arrow/group_by.py, pyproject.toml, tests/frame/drop_nulls_test.py, tests/frame/drop_test.py, tests/frame/filter_test.py, tests/frame/head_test.py, tests/frame/pipe_test.py, tests/frame/rename_test.py, tests/frame/select_test.py, tests/frame/sort_test.py, tests/frame/tail_test.py, tests/frame/with_row_index_test.py, tests/from_dict_test.py, tests/stable_api_test.py, tests/test_group_by.py, tests/test_selectors.py
=> chore: enable more lazy tests

pyproject.toml, tests/frame/std_test.py, tests/frame/test_common.py
=> chore: factor `test_std` outside `test_common`

narwhals/translate.py, tests/expr_and_series/any_all_test.py, tests/expr_and_series/count_test.py, tests/expr_and_series/std_test.py, tests/series_only/is_between_test.py, tests/series_only/test_common.py
=> chore: remove some pyarrow xfails from tests, further split up

docs/installation.md, narwhals/__init__.py, pyproject.toml
=> release: Bump version to 1.1.8

narwhals/_dask/expr.py, tests/dask_test.py
- Related issue # https://github.com/narwhals-dev/narwhals/issues/637
- Closes #
=> feat: Added Dask `Expr.sum`

narwhals/_dask/expr.py, tests/dask_test.py
=> feat: add `to_lowercase`, `to_uppercase`, `to_datetime` for dask

narwhals/_dask/expr.py, tests/dask_test.py
- Related pr #666
- Related comment https://github.com/narwhals-dev/narwhals/pull/666#discussion_r1695513304
=> fix: dask expr `dt.nanosecond` implementation

narwhals/_dask/dataframe.py, narwhals/_dask/expr.py, tests/dask_test.py
- Related issue https://github.com/narwhals-dev/narwhals/issues/637
- Closes #
=> feat: add `drop_nulls` for dask

pyproject.toml, requirements-dev.txt
- [Related discord comment](https://discord.com/channels/1235257048170762310/1237430779584446546/1267753983460642908)
This will allow local development without any additional setup than installing `requirements-dev.txt` and running tests
=> tests: add pytest-env to dev requirements

docs/installation.md, narwhals/__init__.py, pyproject.toml
=> release: Bump version to 1.1.9

narwhals/_dask/expr.py, tests/dask_test.py
=> feat: add dask `Expr.min` and test

docs/basics/complete_example.md, docs/basics/dataframe.md
=> docs: fix todo, avoid lazyframe collect_schema warning

narwhals/_dask/dataframe.py, tests/dask_test.py
[I asked for permission first](https://github.com/narwhals-dev/narwhals/issues/637#issuecomment-2259215956)
=> feat: dask `schema` and `collect_schema`

CONTRIBUTING.md
- Closes #
It was wrong to instruct  that the title should start "with an uppercase letter". That's what I get for copy/pasting. 😅
Added TLDR while I'm at it.
=> docs: Contributing guide correction

narwhals/_dask/expr.py, tests/expr_and_series/operators_test.py
How did we survive for so long without these?
=> feat: dask equality and inequality operators

docs/how_it_works.md
Bullet point indentation was not enough to render properly + typo
=> docs: how it works bulletpoint indentation

narwhals/_arrow/expr.py, tests/expr_and_series/over_test.py
=> feat: arrow expr `over` method

docs/api-reference/expr_str.md, docs/api-reference/series_str.md, narwhals/_arrow/expr.py, narwhals/_arrow/series.py, narwhals/_dask/expr.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/series.py, narwhals/expr.py, narwhals/series.py, tests/expr_and_series/str/strip_chars_test.py
- Related issue #637 #372 
- Closes #
=> feat: add `strip_chars` to string namespace

docs/api-reference/expr.md, docs/api-reference/series.md, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/series.py, narwhals/expr.py, narwhals/series.py, tests/expr_and_series/clip_test.py
- Related issue #700 
- Closes #700
=> feat: add series and expr `clip` method

narwhals/_dask/dataframe.py, narwhals/_dask/group_by.py, pyproject.toml, tests/test_group_by.py
- Closes #
Mostly copied code from `PandasLikeGroupBy`. Updated tests to `collect()` dask dataframes before sorting.
=> feat: add `group_by` to dask

narwhals/_dask/dataframe.py, narwhals/_dask/namespace.py, tests/expr_and_series/double_selected_test.py, tests/expr_and_series/double_test.py, tests/frame/double_test.py, tests/frame/join_test.py, tests/frame/sort_test.py
It ended up being significantly larger than what it was intended.
Namely, wanted to implement `join` method, yet in the test we use `sort` method and `nw.all` function. 
I can split it up in 2 or 3 if needed
=> feat: DaskLazyFrame `join` and `sort`, DaskNamespace `all`

narwhals/_dask/dataframe.py, tests/frame/unique_test.py
=> feat: DaskLazyFrame `unique` method

narwhals/translate.py, tests/translate/from_native_test.py
=> test: improve coverage for `from_native` (dask)

tests/translate/from_native_test.py
=> ci: fix ci from pytest importerror

docs/installation.md, narwhals/__init__.py, pyproject.toml
=> release: Bump version to 1.2.0

narwhals/_dask/expr.py, tests/expr_and_series/name/keep_test.py, tests/expr_and_series/name/map_test.py, tests/expr_and_series/name/prefix_test.py, tests/expr_and_series/name/suffix_test.py, tests/expr_and_series/name/to_lowercase_test.py, tests/expr_and_series/name/to_uppercase_test.py
=> feat: dask expr name namespace

docs/installation.md, narwhals/__init__.py, pyproject.toml
=> release: Bump version to 1.3.0

docs/api-reference/series_cat.md
=> docs: patch `Series.cat` page

narwhals/dataframe.py, narwhals/stable/v1.py
=> docs: use animals instead of cars in example

tpch/notebooks/q1/execute.ipynb
=> docs: run tpch q1 with more libraries

narwhals/_dask/dataframe.py
=> perf: remove some lambdas from _dask backend

narwhals/_pandas_like/dataframe.py, tests/frame/with_columns_test.py
=> fix: empty with_columns not working for pandas backend

docs/api-reference/series.md, narwhals/_arrow/series.py, narwhals/_pandas_like/series.py, narwhals/series.py, tests/series_only/to_arrow_test.py, utils/check_api_reference.py
- Closes #761 
Can't test cudf, I left it as `NotImplementedError` for now. If anyone knows how to do it properly, happy to integrate it :)
=> feat: series `to_arrow` method

docs/api-reference/dataframe.md, narwhals/_arrow/dataframe.py, narwhals/_pandas_like/dataframe.py, narwhals/dataframe.py, tests/frame/to_arrow_test.py
- Somewhat related issue #761
Similarly to #769, cudf is getting not implemented error for now
=> feat: dataframe `to_arrow` method

narwhals/_dask/namespace.py, narwhals/_dask/selectors.py, tests/test_selectors.py
=> feat: `DaskSelectorNamespace` 

README.md
any objections to including this?
- Closes #
=> docs: include "downloads per month" in readme

README.md
=> docs: add Altair to "used by" section

narwhals/_arrow/namespace.py, narwhals/_dask/namespace.py, narwhals/_pandas_like/namespace.py, tests/expr_and_series/sum_horizontal_test.py, tests/test_selectors.py
=> feat: dask `sum_horizontal`

narwhals/_arrow/dataframe.py, narwhals/_dask/dataframe.py, narwhals/_pandas_like/dataframe.py, narwhals/dataframe.py, tests/frame/drop_nulls_test.py
- Related issue #742 
Add support for `subset` argument in dataframe `drop_nulls` method
=> feat: extend dataframe `drop_nulls` method

docs/installation.md, narwhals/__init__.py, pyproject.toml
=> release: Bump version to 1.4.0

.github/workflows/publish_to_pypi.yml, docs/extending.md, narwhals/_arrow/dataframe.py, narwhals/_arrow/expr.py, narwhals/_arrow/series.py, narwhals/_arrow/utils.py, narwhals/_dask/expr.py, narwhals/_dask/namespace.py, narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/series.py, narwhals/_pandas_like/utils.py, narwhals/_polars/expr.py, narwhals/_polars/namespace.py, narwhals/_polars/series.py, narwhals/_polars/utils.py, narwhals/dtypes.py, narwhals/expr.py, narwhals/functions.py, narwhals/selectors.py, narwhals/series.py
=> chore: rename internal dtype functions

docs/how_it_works.md, narwhals/_arrow/dataframe.py, narwhals/_arrow/expr.py, narwhals/_arrow/group_by.py, narwhals/_arrow/namespace.py, narwhals/_dask/dataframe.py, narwhals/_dask/expr.py, narwhals/_dask/group_by.py, narwhals/_dask/namespace.py, narwhals/_dask/selectors.py, narwhals/_dask/utils.py, narwhals/_interchange/dataframe.py, narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/group_by.py, narwhals/_pandas_like/namespace.py, narwhals/_polars/dataframe.py, narwhals/_polars/group_by.py, narwhals/_polars/namespace.py, narwhals/_polars/utils.py, narwhals/translate.py, narwhals/utils.py
If we have `_compliant_frame`, we should probably also have `_native_frame`
- Closes #
=> chore: rename _native_dataframe to _native_frame

.pre-commit-config.yaml, narwhals/_arrow/dataframe.py, narwhals/_arrow/series.py, narwhals/_expression_parsing.py, narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/series.py, narwhals/dataframe.py, narwhals/dependencies.py, narwhals/expr.py, narwhals/series.py, narwhals/translate.py, pyproject.toml, utils/import_check.py
=> feat: improve typing for `to_pandas` / `to_numpy` / `to_arrow`

docs/api-reference/narwhals.md, narwhals/__init__.py, narwhals/_dask/dataframe.py, narwhals/functions.py, narwhals/stable/v1.py, narwhals/utils.py, tests/frame/drop_test.py, tests/new_series_test.py
=> feat: add narwhals.new_series

docs/installation.md, narwhals/__init__.py, pyproject.toml
=> release: Bump version to 1.4.1

narwhals/_dask/expr.py, tests/expr_and_series/diff_test.py
- Related issue # https://github.com/narwhals-dev/narwhals/issues/637
- Closes #
=> feat: add `diff()` method to Dask backend

narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/utils.py, tests/frame/schema_test.py
=> fix: cuDF compat

docs/installation.md, narwhals/__init__.py, pyproject.toml
=> release: Bump version to 1.4.2

narwhals/functions.py, narwhals/stable/v1.py, narwhals/translate.py
- Closes #469 
Not been fully discussed how to approach this, but this is how I would go about it
=> chore: stable api `narwhalify` de-duplication

tests/expr_and_series/dt/datetime_duration_test.py
- Closes #
- Add constructor_lazy and ensure it fails as expected.
- Combine two separate tests into one.
=> test: Improve `duration_attribute_tests`

tests/expr_and_series/arithmetic_test.py, tests/expr_and_series/cat/get_categories_test.py, tests/expr_and_series/is_in_test.py, tests/frame/to_dict_test.py
- Related issue #804
- Closes #
I quickly checked and fixed some minor issues, but the `to_string_test` requires more time. I'm happy to update it in the current PR or in a new one.
=> test: Remove some `to_list()`

tests/expr_and_series/is_first_distinct_test.py, tests/expr_and_series/is_last_distinct_test.py, tests/expr_and_series/is_unique_test.py, tests/expr_and_series/unique_test.py, tests/frame/is_duplicated_test.py, tests/frame/is_unique_test.py
- Related issue #804
- Closes #
=> test: Remove some `to_numpy`

docs/other/column_names.md, docs/roadmap.md, mkdocs.yml, narwhals/_expression_parsing.py, tests/frame/select_test.py
=> feat: allow for non-string columns in `select` for pandas backend

docs/installation.md, narwhals/__init__.py, pyproject.toml
=> release: Bump version to 1.5.1

docs/installation.md, narwhals/__init__.py, pyproject.toml
=> release: Bump version to 1.5.2

narwhals/dataframe.py
=> docs: Fix indentation for __getitem__

docs/installation.md, narwhals/__init__.py, pyproject.toml
=> release: Bump version to 1.5.3

docs/api-reference/dataframe.md, narwhals/__init__.py, narwhals/_arrow/dataframe.py, narwhals/_arrow/series.py, narwhals/_dask/dataframe.py, narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/series.py, narwhals/dataframe.py, narwhals/expr.py, narwhals/series.py, tests/expr_and_series/filter_test.py, tests/frame/filter_test.py, tests/frame/get_column_test.py, tests/frame/row_test.py, tests/frame/slice_test.py
A bunch more things which would be useful to scikit-learn
- Closes #
=> feat: Support more indexing: boolean lists to DataFrame.filter and Series.filter, add DataFrame.row, 

.github/workflows/pytest.yml, .gitignore, noxfile.py, pyproject.toml
In the hope to better locally test #821
=> chore: nox revamp and coverage threshold change

docs/installation.md, narwhals/__init__.py, pyproject.toml
=> release: Bump version to 1.5.4

narwhals/_arrow/namespace.py, narwhals/_pandas_like/namespace.py, tests/frame/lit_test.py
=> patch: allow `lit` to broadcast as left operand

narwhals/_pandas_like/series.py
this could prevent index-mismatched errors
- Closes #
=> feat: use validate_column_comparand in zip_with

narwhals/_arrow/namespace.py, narwhals/_pandas_like/namespace.py, tests/frame/lit_test.py
Reverts narwhals-dev/narwhals#854
=> Revert "patch: allow `lit` to broadcast as left operand"

narwhals/_arrow/namespace.py, narwhals/_arrow/series.py, tests/expr_and_series/when_test.py
=> feat: implement when/then/otherwise for PyArrow

narwhals/_arrow/namespace.py, narwhals/_arrow/series.py, tests/expr_and_series/when_test.py
=> chore: simplify arrow

docs/installation.md, narwhals/__init__.py, pyproject.toml
=> release: Bump version to 1.5.5

CONTRIBUTING.md
I added extra steps, I hope it's clear.
Once it's merged I'll add images to some steps. 
- Closes #
=> docs: add codespace steps and fork steps to `CONTRIBUTING.md`

CONTRIBUTING.md
- Closes #
This should fix some links that where referring to a specific commit :)
(nice that we have the guide for codespaces now 👏)
=> docs: fix relative links in contributing.md

docs/api-reference/narwhals.md, narwhals/__init__.py, narwhals/stable/v1.py, narwhals/utils.py, tests/test_utils.py
- Closes #800 
Are we ok with returning `None` for not pandas-like dataframes? 👀
=> feat: add `maybe_get_index`

narwhals/_pandas_like/series.py, tests/expr_and_series/is_first_distinct_test.py, tests/expr_and_series/is_last_distinct_test.py
=> test: Unxfail 2 modin tests

narwhals/_pandas_like/series.py, tests/expr_and_series/is_duplicated_test.py, tests/expr_and_series/is_unique_test.py
=> test: unxfail more modin tests

narwhals/_dask/dataframe.py, narwhals/_dask/expr.py, narwhals/_dask/selectors.py, narwhals/_dask/utils.py
This doesn't make a difference to users
But I hope it makes the internal code easier to understand and more maintainable
- Closes #
=> chore: improve (internal) Dask typing

narwhals/_arrow/dataframe.py, narwhals/_arrow/expr.py, narwhals/_arrow/series.py, pyproject.toml
=> build: exclude more files (plus some drive-by typing)

utils/generate_backend_completeness.py
=> patch: api completeness table hotfix

tpch/execute/q11.py, tpch/queries/q11.py
=> feat: query 11 implementation

narwhals/functions.py, narwhals/stable/v1.py
=> docs: Example correction

tpch/execute/q3.py, tpch/queries/q3.py
- Related issue #863
- Closes #
=> feat: Add q3 of tpch

tpch/execute/q4.py, tpch/queries/q4.py
=> feat: add q4 implementation

tpch/execute/q5.py, tpch/queries/q5.py
=> feat: add q5 implementation

tpch/queries/q10.py, tpch/queries/q11.py, tpch/queries/q2.py, tpch/queries/q3.py, tpch/queries/q4.py, tpch/queries/q5.py
=> patch: Improve q10, q11, q2, q3, q4, and q5 queries

tpch/execute/q6.py, tpch/queries/q6.py
- Related issue #863
- Closes #
=> feat: Add q6 of tpch

narwhals/dataframe.py
=> docs: fix error in `write_csv` docstring

.gitignore
- Closes #
Small clean up of the gitignore:
- Rearranged ignores into sections like https://github.com/github/gitignore/blob/main/Python.gitignore
- added ignores to vscode, MacOS stuff and `dist`
=> chore: clean up gitignore

narwhals/_duckdb/dataframe.py, narwhals/_duckdb/series.py, narwhals/_ibis/dataframe.py, narwhals/_ibis/series.py, narwhals/_interchange/dataframe.py, narwhals/dependencies.py, narwhals/translate.py, tests/frame/interchange_schema_test.py
=> feat: Duckdb interchange

docs/installation.md, narwhals/__init__.py, pyproject.toml
=> release: Bump version to 1.6.1

.github/workflows/extremes.yml, .github/workflows/pytest.yml, narwhals/dependencies.py, tests/frame/arrow_c_stream_test.py, tests/frame/interchange_schema_test.py, tests/series_only/arrow_c_stream_test.py
=> fix: compatiblity with Python3.8 for Ibis

docs/installation.md, narwhals/__init__.py, pyproject.toml
=> release: Bump version to 1.6.2

tpch/execute/__init__.py, tpch/execute/q1.py, tpch/execute/q10.py, tpch/execute/q11.py, tpch/execute/q15.py, tpch/execute/q17.py, tpch/execute/q18.py, tpch/execute/q19.py, tpch/execute/q2.py, tpch/execute/q20.py, tpch/execute/q21.py, tpch/execute/q3.py, tpch/execute/q4.py, tpch/execute/q5.py, tpch/execute/q6.py, tpch/execute/q7.py, tpch/execute/q9.py, tpch/queries/q15.py, tpch/queries/q17.py, tpch/queries/q18.py, tpch/queries/q19.py, tpch/queries/q20.py, tpch/queries/q21.py, tpch/queries/q6.py, tpch/queries/q7.py, tpch/queries/q9.py
- Related issue #863
- Closes #
I've adopted a more generic coding approach, which may be easier to modify and expand now.
If this is acceptable, I plan to refactor all existing  `execute` codes accordingly; if not, I'll revert the changes to the original state.
=> feat: Add more queries of tpch

narwhals/_dask/namespace.py, tests/frame/lit_test.py
When the typo in the branch name is still something that could be reasonable in the context 🤦🏼‍♂️
=> feat: dask lit with dtype

.github/workflows/extremes.yml
=> ci: allow pre-releases in nightly uv pip install

docs/api-reference/dataframe.md, docs/api-reference/lazyframe.md, narwhals/_arrow/dataframe.py, narwhals/_dask/dataframe.py, narwhals/_pandas_like/dataframe.py, narwhals/dataframe.py, tests/frame/join_test.py
- Related issue #896
- Closes #
=> feat: Add join_asof support for pandas and dask

.github/workflows/check_tpch_queries.yml, tpch/execute/q10.py, tpch/execute/q11.py, tpch/execute/q15.py, tpch/execute/q17.py, tpch/execute/q18.py, tpch/execute/q3.py, tpch/execute/q4.py, tpch/execute/q5.py, tpch/execute/q6.py, tpch/execute/q7.py, tpch/execute/q9.py, tpch/generate_data.py, tpch/tests/test_queries.py
=> test: fixup tpch tests

narwhals/_arrow/dataframe.py, narwhals/_dask/dataframe.py, narwhals/_pandas_like/dataframe.py, narwhals/dataframe.py, tests/frame/join_test.py
- Related issue #896
- Closes #
=> feat: enable `by` argument in `join_asof`

docs/why.md
No related issue.
Fixes a (potential) typo within the `why` section of the docs.
=> docs: fix a typo

docs/installation.md, narwhals/__init__.py, pyproject.toml
=> release: Bump version to 1.6.3

narwhals/_arrow/dataframe.py, narwhals/_dask/dataframe.py, narwhals/_pandas_like/dataframe.py, narwhals/dataframe.py, tests/frame/join_test.py
=> feat: add `on` key to `join`

narwhals/_pandas_like/dataframe.py, tests/frame/join_test.py
fix join when using string literals
- Closes #
=> fix: fix join when using string literals

narwhals/_arrow/group_by.py
@MarcoGorelli I personally find something like this simpler to maintain in my mental model, but feel free to just close it if you don't agree
=> chore: pyarrow group by refactor

docs/installation.md, narwhals/__init__.py, pyproject.toml
=> release: Bump version to 1.6.4

.github/workflows/check_tpch_queries.yml, tpch/execute/q10.py, tpch/execute/q11.py, tpch/execute/q12.py, tpch/execute/q13.py, tpch/execute/q14.py, tpch/execute/q15.py, tpch/execute/q16.py, tpch/execute/q17.py, tpch/execute/q18.py, tpch/execute/q19.py, tpch/execute/q20.py, tpch/execute/q21.py, tpch/execute/q22.py, tpch/execute/q3.py, tpch/execute/q4.py, tpch/execute/q5.py, tpch/execute/q6.py, tpch/execute/q7.py, tpch/execute/q8.py, tpch/execute/q9.py, tpch/queries/q17.py, tpch/queries/q8.py
These don't take that long to run, and would've helped avert a regression...I've also added pyarrow to the mix (thanks vim macros for making this a speedy process)
- Closes #
=> test: always run tpch tests

narwhals/_arrow/dataframe.py, narwhals/_arrow/expr.py, narwhals/_dask/dataframe.py, narwhals/_dask/expr.py, narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/expr.py, narwhals/dataframe.py, tests/frame/join_test.py
- Related issue #742
Also changes the signature to follow polars others in join
=> feat: join suffix parameter

docs/api-reference/expr.md, docs/api-reference/series.md, narwhals/_arrow/expr.py, narwhals/_arrow/series.py, narwhals/_dask/expr.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/series.py, narwhals/expr.py, narwhals/series.py, tests/expr_and_series/mode_test.py
I started to take a very mild look at skrub... and immediately stumbled upon not having `mode` implemented
=> feat: add `mode` method

docs/api-reference/series.md, narwhals/_arrow/series.py, narwhals/_pandas_like/series.py, narwhals/series.py, tests/series_only/scatter_test.py, utils/check_api_reference.py
=> feat: add Series.Scatter

docs/installation.md, narwhals/__init__.py, pyproject.toml
=> release: Bump version to 1.7.0

narwhals/_arrow/series.py, tests/series_only/slice_test.py
=> bug: add support for PyArrow: multi-element `__getitem_`_

tests/expr_and_series/mode_test.py
[Related comment](https://github.com/narwhals-dev/narwhals/pull/942#issuecomment-2345490367)
=> test: xfail polars>1.7.0 `Expr.mode` with broadcast

.github/workflows/check_tpch_queries.yml, README.md, tpch/generate_data.py, utils/check_api_reference.py
=> clean: Assorted cleanups

docs/installation.md, narwhals/__init__.py, pyproject.toml
=> release: Bump version to 1.8.0

.github/workflows/extremes.yml
=> Debug nightly

.github/workflows/extremes.yml
=> ci: fixup nightlies

narwhals/_arrow/series.py, narwhals/_arrow/utils.py, narwhals/_dask/expr.py, narwhals/translate.py
- Closes #465 
Really not revolutionary, but I would avoid people at the sprint finding todo's in the code which are false positives
=> chore: some TODO's cleanup

narwhals/_arrow/expr.py, narwhals/_arrow/series.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/series.py, narwhals/expr.py, narwhals/series.py, tests/expr_and_series/sample_test.py
=> feat: add seed to `Expr|Series.sample`

docs/api-reference/dataframe.md, narwhals/_arrow/dataframe.py, narwhals/_pandas_like/dataframe.py, narwhals/dataframe.py, tests/frame/sample_test.py
- Related issue #973 
I mean... why not? 😂
=> feat: add `DataFrame.sample` method

docs/installation.md, narwhals/__init__.py, pyproject.toml
=> release: Bump version to 1.8.1

narwhals/_arrow/dataframe.py
- Related issue #971
- Closes #
=> Replace assert with raise

tests/expr_and_series/str/contains_test.py
- Closes #
Add tests as follow up on https://github.com/narwhals-dev/narwhals/pull/982#pullrequestreview-2305880801
=> test: add tests to check case sensitive regex for str.contains

CONTRIBUTING.md
- Closes #
- [ -] Code follows style guide (ruff)
- [ -] Tests added
=> docs: Fix link to how Narwhals works

narwhals/_arrow/dataframe.py, narwhals/_arrow/utils.py, narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/utils.py, narwhals/_polars/dataframe.py, narwhals/_polars/utils.py, narwhals/dataframe.py, narwhals/stable/v1.py, narwhals/utils.py, tests/frame/slice_test.py, tests/series_only/slice_test.py
=> Bug: `__getitem__` check for edge cases such as subsetting 0 rows or 0 columns

docs/installation.md, narwhals/__init__.py, pyproject.toml
=> release: Bump version to 1.8.2

docs/roadmap_and_related.md
- Related issue #1011 
- Closes #1011
=> docs: add pycapsule interface to related projects #1011

pyproject.toml
=> Only run tests located in the tests directory

docs/extending.md
Just wanted to see the integrated projects list in a richer format
=> Extensions page improvement

docs/installation.md
- Related issue # 997
- Closes #
=> docs: Add pyarrow example to Installation guide

narwhals/dataframe.py
- Related issue #1000 
- Closes #
=> docstrings pyarrow support for dataframe.to_pandas()

CONTRIBUTING.md, docs/api-reference/series.md, narwhals/series.py, narwhals/stable/v1.py, tests/series_only/to_native_test.py, utils/check_api_reference.py
- Related issue #1002 
- Closes #1002
This PR implements the `to_native` method on the `Series` object.
=> feat: adding to_native to Series

.github/workflows/mkdocs.yml
- Related issue #997 
- Closes #997 
After PR #1023, The following bug was detected in the official website. It should be fixed with this PR:
=> fix: package dependency added pyarrow in docs

.gitignore, CONTRIBUTING.md
None
- [N/A] Tests added 
- It is possible to run unit tests and doctests at the same time. I adapted the docs to reflect this
- The IntelliJ / Pycharm project folder should be excluded, just like the VSCode project folder
=> docs: Update contributing guidelines

narwhals/dataframe.py
- Related issue #1000 
- Closes #
=> Add pyarrow to_csv docstring

utils/generate_backend_completeness.py
- Closes #1006 
- [N/A] Tests added
=> docs: Add DataFrame.pipe to API completeness table

narwhals/_polars/dataframe.py
=> fix: polars getitem on polars==0.20.30

narwhals/dataframe.py, narwhals/stable/v1.py
- Related issue #1000
- Closes #
=> docs: add pyarrow example for dataframe getitem and to_dict

narwhals/_arrow/selectors.py, narwhals/_arrow/utils.py, narwhals/_dask/selectors.py, narwhals/_dask/utils.py, narwhals/_expression_parsing.py, narwhals/_pandas_like/group_by.py, narwhals/_pandas_like/selectors.py, narwhals/_pandas_like/utils.py, narwhals/translate.py, narwhals/utils.py
Inspired by #993, I took a very high level overview and run [perflint](https://github.com/tonybaloney/perflint) (careful with this one!!!). Tests are all passing locally and I thought to give it a go :)
=> perf: low-hanging overhead

narwhals/series.py
=> feat: improve Series repr

tests/test_group_by.py
- Related issue #  https://github.com/narwhals-dev/narwhals/issues/862
- Closes #
=> test: xfail `test_group_by_n_unique_w_missing` for cuDF

docs/api-reference/series.md, narwhals/_arrow/series.py, narwhals/_expression_parsing.py, narwhals/_pandas_like/series.py, narwhals/series.py, tests/series_only/__iter___test.py, utils/check_api_reference.py
=> feat: add `Series.__iter__`

docs/installation.md, narwhals/__init__.py, pyproject.toml
=> release: Bump version to 1.9.0

docs/installation.md, narwhals/__init__.py, pyproject.toml
=> release: Bump version to 1.9.1

docs/installation.md, narwhals/__init__.py, pyproject.toml, utils/bump_version.py
=> ci: improve release process so it fails early

docs/installation.md, narwhals/__init__.py, pyproject.toml
=> release: Bump version to 1.8.3

utils/bump_version.py
=> ci: delete all local tags before making release

narwhals/_pandas_like/dataframe.py
- Closes #
Previous PR: https://github.com/narwhals-dev/narwhals/pull/1041
Looks like cuDF doesn't need this bit where we drop duplicates 
https://github.com/narwhals-dev/narwhals/pull/1041/files#diff-1bb9576cb79de69b2e45bcbc828669f54a6049dbdb76407986b3439ba309369dR481-R487
Tested and it's working as expected
=> fix: add cuDF specific implementation for join how="anti"

narwhals/_dask/group_by.py, narwhals/_pandas_like/group_by.py, tests/test_group_by.py
=> fix: pandas and dask group by `observed=True`

narwhals/_arrow/namespace.py, narwhals/_dask/namespace.py, narwhals/_expression_parsing.py, narwhals/_pandas_like/namespace.py, narwhals/expr.py, tests/expr_and_series/all_horizontal_test.py, tests/expr_and_series/any_horizontal_test.py, tests/expr_and_series/mean_horizontal_test.py, tests/expr_and_series/sum_horizontal_test.py
- Related issue #1071 
- Closes #1071
Fixing bug for sum_horizontal (see #1071)
=> fix: fixing `nw.all()` doesn't work in sum_horizontal

narwhals/_arrow/dataframe.py, narwhals/_arrow/namespace.py, narwhals/_arrow/series.py, narwhals/_dask/dataframe.py, narwhals/_dask/expr.py, narwhals/_dask/namespace.py, narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/namespace.py, narwhals/_pandas_like/series.py, narwhals/_pandas_like/utils.py, narwhals/_polars/dataframe.py, narwhals/_polars/namespace.py, narwhals/_polars/series.py, narwhals/_polars/utils.py, narwhals/dataframe.py, narwhals/dependencies.py, narwhals/series.py, narwhals/utils.py
=> chore: `get_<dependency>` cleanup

docs/installation.md, narwhals/__init__.py, pyproject.toml
=> release: Bump version to 1.8.4

narwhals/dataframe.py, narwhals/stable/v1.py
=> docs: add pyarrow to dataframe lazy docstring

narwhals/_arrow/dataframe.py, narwhals/_arrow/series.py, narwhals/_arrow/utils.py, narwhals/_dask/dataframe.py, narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/series.py, narwhals/_pandas_like/utils.py, narwhals/_polars/dataframe.py, narwhals/_polars/series.py, narwhals/_polars/utils.py
=> chore: rename translate_dtype to native_to_narwhals_dtype

narwhals/dataframe.py
- Related issue #1000
- Closes #
=> doc: add pyarrow to DataFrame docstring

narwhals/_dask/namespace.py, narwhals/_pandas_like/series.py, tests/expr_and_series/when_test.py, tests/series_only/zip_with_test.py
=> fix: `PandasLikeSeries.zip_with` scalar value and `DaskNamespace.when`

docs/api-reference/narwhals.md, narwhals/__init__.py, narwhals/stable/v1/__init__.py, narwhals/utils.py, tests/utils_test.py
=> feat: add `maybe_reset_index` for pandas-like dataframe or series

narwhals/_arrow/utils.py, narwhals/_duckdb/dataframe.py, narwhals/_ibis/dataframe.py, narwhals/_pandas_like/utils.py, narwhals/_polars/utils.py, narwhals/dtypes.py, tests/dtypes_test.py
=> feat: allow inspecting the inner type of List

tests/utils.py
- Closes #
Follow up on https://github.com/narwhals-dev/narwhals/pull/1100
=> test: update check for cuDF series

README.md, docs/css/mkdocstrings.css, docs/extending.md, docs/index.md, mkdocs.yml
=> docs: assorted docs updates

docs/installation.md, narwhals/stable/v1/__init__.py
- Closes #
- Fix import statement to refer to stable API in stable API file + typo in installation page
=> docs: fix some docs issues

README.md
=> docs: correct python bytes description

narwhals/_arrow/dataframe.py, narwhals/_pandas_like/dataframe.py, narwhals/_polars/dataframe.py, narwhals/dataframe.py, tests/frame/getitem_test.py
=> fix: Fix `DataFrame.__getitem__` when slicing with tuple and null slice

narwhals/_arrow/dataframe.py, narwhals/_dask/dataframe.py, narwhals/_pandas_like/dataframe.py, narwhals/dataframe.py, tests/frame/sort_test.py
Required to have consistent behaviour across libraries (needed in plotly)
=> feat: add `nulls_last` kw in dataframe sort

docs/roadmap_and_related.md
We get the question of how we differ from Ibis a lot
I think we need a friendly comparison of the projects, so that we have something we can link to people when they ask
- Closes #
=> docs: add Ibis to "related projects"

docs/backcompat.md
=> docs: fix small docs typo

narwhals/_arrow/namespace.py, tests/expr_and_series/when_test.py
=> fix: when-then-otherwise lit string for arrow backend

narwhals/_arrow/utils.py, narwhals/_duckdb/dataframe.py, narwhals/_pandas_like/utils.py, narwhals/_polars/utils.py, narwhals/dtypes.py, tests/dtypes_test.py, tests/frame/schema_test.py
- Closes # https://github.com/narwhals-dev/narwhals/issues/1108
=> feat: allow inspecting the inner type / length of nw.Array

docs/api-reference/expr_str.md, docs/api-reference/series_str.md, utils/check_api_reference.py
- Related issue https://github.com/narwhals-dev/narwhals/pull/1144#pullrequestreview-2351890173
Iterates over the referenced PR. I pushed the suggested addition after the merge 😇.
=> docs: apply further changes to api reference

.github/workflows/pytest.yml, docs/api-reference/expr_dt.md, docs/api-reference/series_dt.md, narwhals/_arrow/expr.py, narwhals/_arrow/series.py, narwhals/_dask/expr.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/series.py, narwhals/_pandas_like/utils.py, narwhals/dataframe.py, narwhals/expr.py, narwhals/series.py, tests/expr_and_series/convert_time_zone_test.py, tests/expr_and_series/replace_time_zone_test.py
=> feat: add dt.replace_time_zone

docs/installation.md, narwhals/__init__.py, pyproject.toml, tests/expr_and_series/convert_time_zone_test.py
=> release: Bump version to 1.9.2

README.md
- None
Narwhals is now a [required dependency of the marimo notebook](https://github.com/marimo-team/marimo/pull/2567).
Thanks for making such a great package. marimo seeks to be interoperable with many different dataframe libraries, and narwhals makes it easier. Additionally, narwhals' promise of API stability through the `.stable` module gave us the confidence we needed to add narwhals as a required dependency.
=> Used by marimo

narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/series.py, narwhals/_polars/series.py, narwhals/series.py, tests/series_only/scatter_test.py
- closes #1154 
- Closes #1154
=> fix: make Series.scatter always return new series

docs/installation.md, narwhals/__init__.py, pyproject.toml
=> release: Bump version to 1.9.3

narwhals/this.py, pyproject.toml
```
>>> import narwhals.this
⣿⣿⣿⣿⣿⠘⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿ THE ZEN OF NARWHALS
⣿⣿⣿⣿⣿⠠⢹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿ Keep it simple
⣿⣿⣿⣿⣿⡀⡄⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿ Move slowly and keep things working
⣿⣿⣿⣿⣿⡇⡼⡘⠛⠿⠿⠿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿ A good API is an honest one
⣿⣿⣿⡿⣫⡄⠾⣣⠹⣿⣿⣿⣶⣮⣙⠻⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿ Yes, that needs documenting
⣿⣿⢋⣴⣿⣷⣬⣭⣾⣿⣿⣿⣿⣿⣿⣿⣦⡙⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿ People learn better from examples
⣿⢃⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⡌⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿ than from explanations⠀
⡏⠀⢰⠄⢻⣿⣿⣿⣿⡿⠋⢉⠻⣿⣿⣿⣿⣿⣿⡜⣿⣿⡿⢁⢻⣿⣿⣿⣿⣿ If in doubt, say 'no'⠀
⡇⣌⣀⣠⣾⣿⣿⣿⣿⣇⠶⠉⢁⣿⣿⣿⣿⣿⣿⣧⡹⣿⡇⣿⣧⠻⠿⠿⠿⠿ you can always reconsider⠀
⡧⢹⣿⣿⣿⣜⣟⣸⣿⣿⣷⣶⣿⡿⣿⣿⣝⢿⣿⣿⣷⣬⣥⣿⣿⣿⣿⣿⡟⣰ Yes, we need a test for that
⢡⣆⢻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⡙⣿⣿⡇⣿⣿⣿⣿⠟⣋⣭⣛⠻⣋⣴⣿ If you want users
⣶⣤⣤⣙⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣦⣍⣡⣿⡿⢋⣴⣿⣿⣿⣿⣿⣿⣿⣿ you need good docs⠀
⣿⣿⣿⣿⣿⣶⣬⣙⣛⠻⠿⠿⠿⠿⠿⠟⣛⣩⣥⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿ Our code is not irreplaceable
```
=> feat: add The Zen of Narwhals

.github/workflows/bump-version.yml
=> ci: try fixup bump-version.yml

narwhals/_duckdb/dataframe.py, narwhals/_duckdb/series.py, narwhals/_ibis/dataframe.py, narwhals/_ibis/series.py, narwhals/_interchange/dataframe.py, narwhals/_interchange/series.py, tests/frame/interchange_native_namespace_test.py
Addresses [comment](https://github.com/narwhals-dev/narwhals/pull/901#discussion_r1795942960)
=> fix: add `__native_namespace__` for interchange support dataframes

tests/expr_and_series/unary_test.py
=> test: unxfail test_unary for dask

narwhals/_pandas_like/series.py, narwhals/_pandas_like/utils.py, tests/frame/with_columns_test.py
=> fix: preserve dtypes when using with_columns and length-1 pandas df

docs/installation.md, narwhals/__init__.py, pyproject.toml
=> release: Bump version to 1.9.4

narwhals/_pandas_like/utils.py
- Closes #
Per comment: on https://github.com/narwhals-dev/narwhals/pull/1192#discussion_r1802948783
=> Simplify return function in `_pandas_like.utils.py`

narwhals/this.py
=> docs: add 'commotion' to Zen

docs/installation.md
=> doc: Add uv to quick start

.github/workflows/downstream_tests.yml
Related to https://github.com/marimo-team/marimo/pull/2659
=> simplify marimo in downstream_tests.yml
