narwhals-dev/narwhals

.github/workflows/pytest.yml, .gitignore, narwhals/dataframe.py, narwhals/pandas_like/group_by.py, narwhals/pandas_like/typing.py, narwhals/series.py, narwhals/typing.py
- Add some docstrings for the `narwhals.dataframe.DataFrame` class
=> Add docstrings

narwhals/dataframe.py
Docstrings for:
- `narwhals.dataframe.DataFrame.unique`
- `narwhals.dataframe.DataFrame.sort`
- `narwhals.dataframe.DataFrame.join`
You can create a new base `docstrings` branch from your `main` before merging since I can't do it with my user
=> More docstrings

narwhals/dataframe.py
This PR adds all the missing docstrings for the `narwhals.dataframe.DataFrame` class.
I had to use some tricks to let one of the `to_dict()` docstrings pass. I think there is a problem in the docstring "translation" process. Apparently tabs in the outputs are transformed to spaces before the output is checked by pytest. However, even setting the output to have spaces instead of tabs does not work. My workaround is to transform the tabs to spaces like this:
```python
p = pprint.pformat(df.to_dict(as_series=True)).replace('\t', '    ')
print(p)
```
instead of doing directly:
```python
df.to_dict(as_series=True)
```
The other solution would be just to skip the test with `# doctest: +SKIP`
~~I changed the error message in the `__init__` because the class constructor should not accept Polars …
=> Docstrings DataFrame

narwhals/dataframe.py
I added the missing docstrings for the `narwhals.dataframe.LazyFrame` class.
The pre-commit error is for a single word in a docstring output. Codespell thinks it's a typo. I tried adding an inline ignore but it doesn't work.
About the other error in the CI, I think the docstring with the lambda operator is not supported in Python 3.8.
=> Docstrings LazyFrame

.github/workflows/extremes.yml, tests/hypothesis/test_join.py
Previous polars versions were failing when using `join` on a column with a `float=-0.0`.
Added specific example to make sure it is always tested.
=> Bumped polars version on extremes.yml due to polars old bug

README.md
providing a bit more context for the comparison
I think this still needs showing though, as for the use case I have in mind, requiring pandas+PyArrow is a non-starter
can always remove the plot if they do follow through on making PyArrow+pandas optional
=> provide more context in ibis comparison

narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/utils.py, tests/hypothesis/test_basic_arithmetic.py
we shouldn't be converting to a proper string dtype on the user's behalf, just preserve what they already have
"proper" Object support may come later, if there's requests - but for now, treat them as strings in disguise
=> preserve object dtype

.github/workflows/extremes.yml, pyproject.toml, tests/test_common.py, tests/test_dt.py, tests/test_series.py
we just need to skip some tests for the min-versions CI job, as Float64 wasn't available back then. But, anyone using pandas that far back wouldn't have been using Float64 anyway, so this won't affect them
=> make pandas>=1.1.5 the minimum requirement

narwhals/_pandas_like/expr.py, narwhals/_pandas_like/series.py, narwhals/expression.py, narwhals/series.py, tests/test_common.py
This one is spicy, I'm very curious if I did it right
=> Added ddof arg to std

narwhals/expression.py
=> Add docstring for Expr.min()

narwhals/_pandas_like/utils.py, narwhals/dependencies.py, tests/frame/with_columns_sequence_test.py
partial fix for #141 
For passing lists / tuples, I _think_ what we need is a Series constructor. Something like
```python
df.with_columns(
g_1=nw.Series(
["A"] * (n_samples // 2) + ["B"] * (n_samples // 2),
implementation=nw.get_implementation(X),
)
)
```
?
We need to pass something to `nw.Series`, otherwise it doesn't know which library's Series to create
An alternative API could be
```python
plx = nw.get_namespace(X)
df.with_columns(
g_1=plx.Series(["A"] * (n_samples // 2) + ["B"] * (n_samples // 2))
)
```
which...might be a bit cleaner?
=> allow numpy array in with_columns

narwhals/series.py
I can also simplify them to look like those in the Dataframe section, so would be something like this:
>>> import polars as pl
>>> import narwhals as nw
>>> s_pl = pl.Series("foo", [1, 2, 3])
>>> s = nw.Series(s_pl)
>>> s.name
'foo'
But I thought it looks better if I follow the same template as the rest of the documentation in the Series section.
=> Add docstring for Series shape and name

docs/api-reference/expressions.md, docs/api-reference/series.md, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/series.py, narwhals/expression.py, narwhals/series.py, tests/expr/is_duplicated_test.py, tests/expr/is_first_distinct_test.py, tests/expr/is_last_distinct_test.py, tests/expr/is_unique_test.py, tests/expr/null_count_test.py, tests/test_series.py, utils/check_api_reference.py
Similar to #159 but for series and expr methods ([complete list from polars](https://docs.pola.rs/py-polars/html/reference/series/descriptive.html)); introduces the following Series methods:
- is_duplicated
- is_empty (not in expr)
- is_unique
- null_count
- is_first_distinct
- is_last_distinct
- is_sorted (not in expr)
- value_counts (not in expr)
=> feat: Series descriptive methods

narwhals/expression.py
I noticed that the narwhals Expr.is_in() works slightly different than polars Expr.is_in() - 
it doesn't accept Series and Expressions as "other" argument.  Therefore I changed the description to "list"and "List-like objects"
because it was what I've found in the error description.
Edit: I see now, that has been addressed in #101 , should I then change "list", "list-like objects"to Iterable in the docstrings?
=> DOC: usage example for is_in added in Expr

.pre-commit-config.yaml, narwhals/_pandas_like/group_by.py, narwhals/_pandas_like/namespace.py, narwhals/_pandas_like/series.py, narwhals/_pandas_like/utils.py, narwhals/dtypes.py, narwhals/series.py
this helps ensure that we're never importing anything on behalf of the user, we should only ever use what they're already using
=> ban 3rd party imports

docs/api-reference/group_by.md, mkdocs.yml, narwhals/group_by.py
=> DOC: fill in missing docstrings for GroupBy.agg

docs/api-reference/selectors.md, narwhals/__init__.py, narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/namespace.py, narwhals/_pandas_like/selectors.py, narwhals/selectors.py, tests/selectors_test.py
=> feat: implement selectors set arithmetic

mkdocs.yml
xref #215
sorted alphabetically API Reference
=> DOC: sort API Reference

.github/release-drafter.yml, .github/workflows/release-drafter.yml
- Closes #https://github.com/narwhals-dev/narwhals/issues/239
When this is added, a draft release (that can be edited) will be created. Then you can publish it when needed. 
New pull requests should automatically be labeled now.  It uses the titles of the PR to assign the label, so it can add it to the right category. 
Please note that the regular expressions  (ln 14 - 37) on `.github/release-drafter.yml` need adjustment, or we need to make sure that the PR always start with the right word. I only changed the one for documentation to show how it may be handled. 
I took the labels as Polars does, but their PR titles always start correctly.
Feedback? questions?
edit: it works on a toy project. Is this "GitHub Enterprise"?
=> Added Release drafter

docs/api-reference/expressions_dt.md, docs/api-reference/series_dt.md, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/series.py, narwhals/expression.py, narwhals/series.py, tests/test_dt.py
-  `# noqa: A002` is because ruff complain about the "format" naming, but that's what polars uses.
- other comments in the code itself
=> feat: `strftime` for datetime namespace

docs/api-reference/expressions_str.md, docs/api-reference/series_str.md, mkdocs.yml, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/series.py, narwhals/expression.py, narwhals/series.py, tests/expr/str/slice_test.py, tests/expr/str/tail_test.py, tests/test_str.py
None
Implements `slice`, `starts_with` and `tail` methods in the str namespace for Expr and Series.
It is a quite large one, but slice implementation allowed to refactor head and tail, however using slice does not allow for negative indexes as polars does. Since they were not supported anyway in the first place, I moved to this implementation but happy to discuss how to work around it.
=> enh: `slice`, `starts_with`, `tail` methods for `str` namespace

docs/api-reference/expressions.md, docs/api-reference/series.md, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/series.py, narwhals/expression.py, narwhals/series.py, tests/expr/round_test.py, tests/test_common.py
- Closes #302 
I just realized polars does not have a `DataFrame.round`, I guess `df.select(pl.all().round())` would do the trick :)
=> enh: series and expr round method

.github/workflows/publish_to_pypi.yml
- Closes #
You can see here:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
And here:
https://github.blog/2024-02-12-get-started-with-v4-of-github-actions-artifacts/
I noticed the warnings when I saw the [runs of a PR](https://github.com/narwhals-dev/narwhals/actions/runs/9610106865) ..just plain curiosity. 🤓
=> ci: Updating github actions artifacts

docs/api-reference/dataframe.md, narwhals/_pandas_like/dataframe.py, narwhals/dataframe.py, tests/frame/rows_test.py, tests/test_common.py
- Closes #285
I've matched the API with https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.rows.html
=> feat: add DataFrame.rows

narwhals/_pandas_like/group_by.py, narwhals/_pandas_like/namespace.py, narwhals/_pandas_like/series.py, narwhals/_pandas_like/utils.py
As mentioned in #321, I am proposing a small tweak to `series_from_iterable` to (hopefully) improve readibility:
- renaming to `native_series_from_iterable` given that it returns a "native" (pandas, modin, etc) series
- adding a `from_iterable` to `PandasSeries` to allow creating directly a `PandasSeries`
As checklist above, I still need to add a test. Happy to close if you think it is not needed :)
=> refactor: rename `series_from_iterable`

narwhals/dataframe.py, narwhals/series.py, tests/expr/str/starts_with_ends_with_test.py, tests/frame/drop_nulls_test.py, tests/frame/pipe_test.py, tests/frame/test_common.py, tests/frame/test_invalid.py, tests/frame/with_row_index_test.py, tests/hypothesis/test_concat.py, tests/series/test_common.py, tests/test_group_by.py, tests/tpch_q1_test.py
As implemented in #331, I like the idea of recommending to use `nw.from_native` instead of the classes directly. Moving this to a separate PR as @MarcoGorelli asked. 
The recommendation was already mentioned in some docstrings, but not applied everywhere. This also allows to simplify the `LazyFrame.__init__`.
=> refactor: always recommend `from_native`

tests/expr/test_dt.py, tests/utils.py
- Closes #
Since `sys.platorm` is `darwin` on MacOS, those tests were skipped when testing locally and local coverage results were also misleading. (Should we also test macOS in the CI? 🤔)
=> bug: don't skip arrow tests on macOS

tests/frame/filter_test.py, tests/frame/test_common.py
- Related issue: https://github.com/narwhals-dev/narwhals/issues/401
- Closes: None
Before the change, 6 tests were executed when I ran:
```
pytest tests/frame/test_common.py::test_filter tests/frame/test_common.py::test_filter_series
```
Now, 8 are executed with:
```
pytest tests/frame/filter_test.py
```
Is that expected?  
---
Also, I tried using `constructor_with_pyarrow` but two tests failed with errors like:
```
...
E       AttributeError: 'ArrowDataFrame' object has no attribute 'filter'
...
E       AttributeError: 'ArrowDataFrame' object has no attribute 'with_columns'
...
```
Any suggestions? Maybe there's an easy fix, I'm not too familiar with this repo yet.  
---
**One more question**: why aren't factored out tests using `nw.to_native(result)` and comparing `result_native` …
=> clean: factor `filter_test` and `filter_test_series` out of `test_common`

tests/frame/instantiation_test.py, tests/frame/test_common.py
- Related issue: https://github.com/narwhals-dev/narwhals/issues/401
- Closes: None
I'm not sure the small modifications were translated correctly from the original test. Is not passing eager_only=True enough for a lazy instantiation?
=> clean: factor `test_<lazy|eager>_instantiation` out of `test_common`

README.md, docs/index.md
=> docs: fix `typing` link

narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/group_by.py, narwhals/_pandas_like/namespace.py, narwhals/_pandas_like/selectors.py, narwhals/_pandas_like/series.py, narwhals/_pandas_like/utils.py, narwhals/translate.py, noxfile.py, pyproject.toml, tests/frame/test_common.py
- [N/A] Tests added 
- [N/A] Documented the changes
By using enums instead of strings we achieve:
1. Single source of truth: now to add a new backend, one only needs to modify the `narwhals/dependencies.py` file
2. Simplify contribution: by having enums in a single location and using `assert_never`, once a new value is added to the Enum, MyPy will flag all the places where modifications are needed, this is much easier to navigate than finding failed tests
3. For multi-backend implementations (such as pandas), a file called `implementations.py` is added showing the subset of implementations supported for that specific platform
4. Reduce boilerplate: with Enums and a couple of mappings, there is no longer a need for many if/elif/else logic, thus making the code easier to extend. There are …
=> Use enums for implementations

pyproject.toml
The only relevant check that is not compliant is DTZ001 which implies adding timezone info in datetime objects
=> Refactor: Re enable and fix Ruff's DTZ Checks

.github/workflows/random_ci_pytest.yml, tests/expr/cast_test.py, utils/generate_random_versions.py
=> ci: pin Numpy version in random CI versions job

narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/series.py, pyproject.toml
The idea of this PR is to locally disable the check where it cannot be avoided and enable it globally to make sure new violations are properly flagged
=> Refactor: Re enable and Ruff's ARG check globally

narwhals/_pandas_like/dataframe.py, narwhals/dataframe.py, tests/frame/test_common.py
Disclaimer: I think I never used a semi join before. From the [polars docs](https://docs.pola.rs/user-guide/transformations/joins/#semi-join) this seems like it should do the trick 😁
=> enh: pandas-like semi join

mkdocs.yml
- Closes #
Little pet peeve of mine, but I was looking foward to get the docs in dark mode too.
This PR simply adds the dark mode switch, which has 3 modes:
- System preference (Default dark or light mode based on users' system preference)
- Light mode
- Dark mode
=> docs: add dark-mode switch

tests/expr/unary_test.py, tests/frame/test_common.py
- Related issue: https://github.com/narwhals-dev/narwhals/issues/401
- I'm assuming this goes into tests/expr since the test is called test_expr_unary, so I moved it there and removed the expr from its name.
- `constructor_with_pyarrow` didn't work.
=> Moved/renamed test_expr_unary to expr/unary_test::test_unary

.github/release-drafter.yml, utils/bump_version.py
make sure that, for `bump_version`, we're starting off on `upstream/main`
i'm also removing the tag from the release drafter so it doesn't get overwritten
=> ci: try improving release flow

docs/api-reference/narwhals.md, narwhals/__init__.py, narwhals/_arrow/series.py, narwhals/expression.py, narwhals/stable/v1.py, tests/expr/all_horizontal_test.py
Remark that polars and pandas `__and__` logic is different for None.
I fixed the implementation for pyarrow however!
=> feat: expose `all_horizontal`

narwhals/_arrow/namespace.py, narwhals/_expression_parsing.py, narwhals/_pandas_like/namespace.py, tests/frame/with_columns_sequence_test.py
=> patch: `_create_compliant_series`

docs/api-reference/narwhals.md, narwhals/__init__.py, narwhals/_arrow/dataframe.py, narwhals/_interchange/dataframe.py, narwhals/_interchange/series.py, narwhals/dataframe.py, narwhals/functions.py, narwhals/series.py, narwhals/stable/v1.py, narwhals/translate.py, narwhals/typing.py, narwhals/utils.py, requirements-dev.txt, tests/frame/get_column_test.py, tests/frame/interchange_schema_test.py, tests/frame/join_test.py, tests/frame/test_invalid.py, tests/series/is_ordered_categorical_test.py, tests/translate/from_native_test.py, utils/check_api_reference.py, utils/check_backend_completeness.py, utils/generate_random_versions.py
closes #388 
- Closes #
Maybe `from_native` should return a `SimpleFrame` here, with which you can't really do much other than inspect metadata - but then at least the IDE won't autocomplete things it doesn't support
=> feat: add "interchange"-level support for libraries which implement the interchange protocol

narwhals/_arrow/dataframe.py, narwhals/_pandas_like/dataframe.py, narwhals/dataframe.py, tests/frame/is_duplicated_test.py, tests/frame/is_unique_test.py, tests/frame/unique_test.py, utils/check_backend_completeness.py
[Relevant arrow issue/conversation](https://github.com/apache/arrow/issues/30950)
=> feat: arrow `unique`, `is_duplicated`, `is_unique`

narwhals/_arrow/series.py, narwhals/_pandas_like/series.py, narwhals/_polars/series.py, narwhals/series.py
- Closes #
`Series.__getitem__` return a Series when a slice or sequence is passed, this should make the fix for that :)
=> bug: fix `Series.__getitem__` typing

narwhals/_pandas_like/group_by.py, requirements-dev.txt, tests/frame/interchange_schema_test.py, tests/hypothesis/test_join.py, tests/series_only/arithmetic_test.py, tests/test_group_by.py
Ibis put upper bounds on their deps, which is interfering with our testing here
We can test the interchange part just by explicitly calling `__dataframe__` ourselves
- Closes #
=> ci: fix hypothesis failure, remove ibis from tests

narwhals/_arrow/dataframe.py, narwhals/_arrow/series.py, narwhals/_arrow/utils.py, tests/expr_and_series/n_unique_test.py, tests/expr_and_series/str/to_datetime_test.py, tests/frame/item_test.py, tests/series_only/is_sorted_test.py, tests/series_only/test_common.py
closes #557
we're already doing this where we need it: https://github.com/narwhals-dev/narwhals/blob/1790c81712c3337000f2b5f95342bfe2dc1a7557/narwhals/_arrow/namespace.py#L81-L82
pandas is often returning non-Python scalars (e.g. pd.Timestamp, np.int64, ...) - I think we should aim to keep things native as much as possible. These scalars are designed to be mostly interchangeable with the stdlib ones anyway, but overcome some limitations (e.g. `pd.Timestamp` has 'ns' resolution, whereas stdlib datetime only `'us'`)
- Closes #
=> perf: remove as_py from _arrow implementation wherever possible

tests/frame/select_test.py, tests/frame/test_common.py
- Related issue: https://github.com/narwhals-dev/narwhals/issues/401
=> chore: factor `test_empty_select` out of `test_common` (to existing `select_test.py`)

narwhals/_dask/expr.py, tests/dask_test.py
=> feat: add `is_between` for dask

tests/expr_and_series/name/keep_test.py, tests/expr_and_series/name/map_test.py, tests/expr_and_series/name/prefix_test.py, tests/expr_and_series/name/suffix_test.py, tests/expr_and_series/name/to_lowercase_test.py, tests/expr_and_series/name/to_uppercase_test.py, tests/expr_and_series/sample_test.py, tests/expr_and_series/sum_all_test.py, tests/expr_and_series/unary_test.py, tests/frame/add_test.py, tests/frame/double_test.py, tests/frame/join_test.py, tests/frame/series_sum_test.py, tests/frame/slice_test.py, tests/frame/test_common.py, tests/frame/with_columns_sequence_test.py, tests/series_only/test_common.py
=> chore: enable more lazy tests

narwhals/_dask/expr.py, tests/dask_test.py
=> feat: add `ends_with`, `contains`, `slice` for dask

narwhals/_dask/dataframe.py, narwhals/_dask/expr.py, narwhals/_dask/namespace.py, narwhals/_dask/typing.py, narwhals/_expression_parsing.py, tests/dask_test.py
Edit: For DaskNamespace, as of now:
- `_create_expr_from_callable`: implemented
- `_create_expr_from_series`, `_create_compliant_series`, `_create_series_from_scalar` raise `NotImplementedError`
feedbacks are welcomed!
=> feat: dask `select` method

tests/dask_test.py
- Closes #
As [Iron Maiden taught us](https://en.wikipedia.org/wiki/The_Number_of_the_Beast_(song)), the number 666 may be cursed. The `random-version` test took that literally and failed ([run 666](https://github.com/narwhals-dev/narwhals/actions/runs/10148205433/job/28060389675)) in a dask test. I could reproduce with `pyarrow==11.0.0`. It seems to be the same known error with `ß` that I was mentioned in various places in the code base.
I added an `xfail` let me know what you think :)
=> test: xfail uppecase for dask and pyarrow 11.0.0

narwhals/_pandas_like/dataframe.py, tests/frame/rows_test.py
- Closes #
While using `narwhals` in a small library of mine, I noticed a little inconsistency with `PandasLikeDataFrame.iter_rows` when the columns are "renamed to positional names if they are invalid Python identifiers, repeated, or start with an underscore." ([pandas docs](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.itertuples.html))
To reproduce:
```python
import narwhals as nw
import pandas as pd
import polars as pl
df = pd.DataFrame(
[[1, 2, 3,4], [6, 7, 8, 9]],
columns=["a", "_b", 1, "2"]
)
pl_df = pl.DataFrame(df)
def func(df):
df = nw.from_native(df)
return list(df.iter_rows(named=True))
func(df)
func(pl_df)
```
This should fix that 👀
=> bug: fix `iter_rows` inconsistency in pandas

narwhals/_dask/dataframe.py, tests/dask_test.py
This is a pretty small PR! I mainly wanted to get a feel for the API 😁 (initially made lots of changes as if it was a regular DataFrame and then remembered it was lazy!)
Adds in a `columns` property for the DaskLazyFrame.
EDIT: Ok, I couldn't resist tinkering. This now applies a fair bit more functionality, getting 'filter' to work (at least for some basic cases since the expressions still aren't fully complete).
I've added in "not-implemented" functions (i.e. empty functions that just raise an error) to appease mypy type checking. I figured this was a better move that `# type: ignore` annotation since they actually will be needed at some point, but let me know if the other approach would be better!
=> feat: dask `columns` property & `filter` method

narwhals/_dask/dataframe.py, narwhals/_dask/expr.py, narwhals/_dask/namespace.py, narwhals/_dask/utils.py, narwhals/_expression_parsing.py, tests/dask_test.py
Following up from: https://github.com/narwhals-dev/narwhals/pull/670
Introduces filter for dask dataframes, plus a few required methods for comparison to get things working into a testable state. (@FBruzzesi hope it's ok, I went ahead and implemented `__and__` - I know you said you'd probably do this, so I hope I haven't stood on any toes! It seemed a quick add and otherwise testing all horizontal was a little messy)
Note: There's a pretty disgusting hack I've added in that should probably come out before anything is merged. Looks like narwhals `evaulate_into_exprs` has this bit:
```python
series.append(evaluated_expr[0].alias(name))0
```
I'm getting an error here because `evalated_exp[0]` is a dask-exp/dask-series (depending on version) which doesn't have an `alias` …
=> Feat: Dask filter and __and__ method added

.github/workflows/check_docs_build.yml, .github/workflows/downstream_tests.yml, .github/workflows/extremes.yml, .github/workflows/mkdocs.yml, .github/workflows/pytest.yml, .github/workflows/random_ci_pytest.yml
=> ci: adopt uv

narwhals/_dask/expr.py, tests/dask_test.py
- Closes #
Maybe it's  soon time to refactor `dask_test.py` ?
=> feat: add `fill_null` to `DaskExpr`

narwhals/_dask/expr.py, tests/dask_test.py
=> feat: add dask `Expr.max` and test

docs/how_it_works.md
The current documentation is unclear about the how objects move from narwhals api to polars compatible backend to native api. This adds a section that tries to make that more clear.
=> docs: explain translation from narwhals api to native api

narwhals/_arrow/group_by.py, tests/test_group_by.py
- Closes #714 
Possibly not the most performant implementation, but it does the job.
Using numpy unique would not work if any column to group by is not numeric.
=> feat: `ArrowGroupBy.__iter__` method

narwhals/_arrow/utils.py
=> perf: only use as_py for pyarrow when necessary (before pyarrow 13)

narwhals/_dask/expr.py, tests/expr_and_series/arithmetic_test.py
- Related issue #637 (working towards TPCH Q1, only `len` is missing)
It's literally always calling the native implementation
=> feat: dask expr dunder methods

narwhals/_dask/expr.py
- Related issue #637  
- Closes #
If this looks good I'll also add `NotImplementedError` to the following methods and this PR
`Expr.sort`
`Expr.head`
`Expr.tail`
=> feat: add NotImplementedError error for index changing methods Dask

narwhals/_dask/namespace.py, narwhals/_dask/utils.py, tests/expr_and_series/len_test.py, tests/stable_api_test.py
=> perf: keep `nw.len` totally lazy for dask

narwhals/_dask/expr.py, tests/expr_and_series/len_test.py, tests/test_group_by.py
=> feat: dask expr `len` method

narwhals/_dask/namespace.py, tests/frame/lit_test.py
=> feat: dask namespace `lit` method

narwhals/expr.py
=> chore: simplify Expr.clip

docs/api-reference/expr_str.md, docs/api-reference/series_str.md, narwhals/_arrow/expr.py, narwhals/_arrow/series.py, narwhals/_dask/expr.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/series.py, narwhals/expr.py, narwhals/series.py, tests/expr_and_series/str/replace_test.py, tests/utils.py
- Related issue #637 #372 
- Closes #
In polars, `Expr.replace` and `Expr.replace_all` also accept and `Expr` for the pattern and value arguments. 
But this seems only to be true when using `pl.lit` as arguments.  
I just implemented the type `str` for this PR.
=> feat: add  `str.replace` and  `str.replace_all`

docs/api-reference/dataframe.md, docs/api-reference/series.md, narwhals/dataframe.py, narwhals/series.py, tests/frame/arrow_c_stream_test.py, tests/series_only/arrow_c_stream_test.py, utils/check_api_reference.py
closes #784 
@kylebarron fancy taking a look to see if this is what needs doing / if I've understood the assignment?
- Closes #
=> feat: Support Arrow PyCapsule Interface for export

CONTRIBUTING.md, narwhals/_arrow/dataframe.py, narwhals/_arrow/group_by.py, narwhals/_arrow/namespace.py, narwhals/_arrow/series.py, narwhals/_arrow/utils.py, narwhals/_dask/dataframe.py, narwhals/_dask/namespace.py, narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/series.py, narwhals/dataframe.py, narwhals/dependencies.py, narwhals/expr.py, narwhals/series.py, narwhals/translate.py, narwhals/utils.py, tests/no_imports_test.py
I'd originally introduced these `get_` functions (`get_numpy`, `get_pandas`, etc...) to make sure we didn't import anything which the user hadn't already imported
This is fine for short-circuiting `isinstance` checks. However, we're also importing 3rd party libraries within functions, not just for `isinstance` checks, and my concern is that we're assuming that some imports are automatically available, but that this might not always be the case in the future. For example, currently, `import pyarrow` automatically imports `numpy` as well, and so `np = get_numpy()` works without issues. But I don't know if we can assume that that'll always be the case, so we may need to import numpy explicitly to be safe
So, I've added explicit `is_pandas_dataframe` / `is_polars_series` / etc. methods which …
=> chore: import overhaul

narwhals/_dask/expr.py, tests/expr_and_series/null_count_test.py
=> feat: add dask `Expr.null_count`

narwhals/_pandas_like/series.py, narwhals/_pandas_like/utils.py, narwhals/expr.py, narwhals/series.py, requirements-dev.txt, tests/conftest.py
Test cudf.DataFrame if installed
We can't test it in CI (unless Nvidia sponsors us 😉 ), but we can at least run the tests manually on Kaggle notebooks once every whenever we feel like it, like this: https://www.kaggle.com/code/marcogorelli/testing-cudf-in-narwhals/notebook
Gradually fixing up the failing cuDF tests can then make for good sprint material - we're got a few coming up
- Closes #
=> test: Add `cudf_constructor` to conftest

narwhals/_dask/expr.py, tests/expr_and_series/is_in_test.py
Main implementation here is `is_in` which is fairly simple (I've just used Dask's own `isis` method, and then removed the `xfail` from the Dask pytest).
I've also marked in `is_duplicated` and `is_unique` as *not implemented*. I think this is the right call because Dask doesn't have any internal `duplicated` check (at least yet! Looks like it could be on the cards soon-ish)
Here's the Github issues/PRs relating to Dask duplication checks:
- https://github.com/dask/dask/issues/1854
- https://github.com/dask/dask/issues/10374
- https://github.com/dask/dask/pull/10542
=> feat: add `is_in` to `DaskExpr` and mark `is_duplicated` and `is_unique` as not implemented

tests/expr_and_series/gather_every_test.py, tests/expr_and_series/pipe_test.py, tests/expr_and_series/round_test.py, tests/expr_and_series/str/replace_test.py, tests/expr_and_series/str/slice_test.py, tests/expr_and_series/str/strip_chars_test.py, tests/expr_and_series/str/tail_test.py, tests/expr_and_series/str/to_uppercase_to_lowercase_test.py, tests/frame/get_column_test.py, tests/frame/slice_test.py, tests/series_only/to_list_test.py, tests/series_only/zip_with_test.py
this enables more tests to pass for cudf (which doesn't support tolist? srs?) https://www.kaggle.com/code/marcogorelli/testing-cudf-in-narwhals?scriptVersionId=192865185
- Closes #
=> chore: use compare_dict in series tests

narwhals/_dask/expr.py, tests/expr_and_series/is_duplicated_test.py, tests/expr_and_series/is_unique_test.py
Edit: I just read @benrutter [comment](https://github.com/narwhals-dev/narwhals/issues/637#issuecomment-2293078216). 
I don't think we should limit ourselves to what comes out of the box. It may not be the most performant operation, but if I had to have a logic such as:
```py
if polars:
...
elif dask:
...
```
I would probably end up with something similar because that is not natively supported
=> feat: dask expr `is_unique` & `is_duplicated`

.github/release-drafter.yml
- Closes #https://github.com/narwhals-dev/narwhals/issues/490
I tried "smarter" regex expressions to accept uppercase/lowercase but didn't work on github. Specifically (?i) instead of all the cases I added.
=> ci: Modified drafter's labeller regex to match titles with uppercase

tests/expr_and_series/is_duplicated_test.py
- Related issue #804
This PR converts tests in `to_string_test` to use `compare_dicts`.
=> test: Use compare dicts in is_duplicated_test

narwhals/_dask/expr.py, tests/expr_and_series/dt/datetime_duration_test.py
- Closes #
It uses a little trick, `//1`, to obtain an integer, but I’m unsure if this approach is appreciated. Without it, some tests will fail, while others may not.
=> feat: add `DaskExpr.total_minutes`, `total_seconds`, `total_milliseconds`, `total_microseconds`, `total_nanoseconds`

narwhals/_dask/expr.py, tests/expr_and_series/dt/to_string_test.py
- Related issue #637  
- Closes #
~Dask seems to be failing for `%.f`, any suggesstions on how to handle it ?~ Solved
=> feat: add `dt.to_string` to `DaskExpr`

narwhals/_pandas_like/dataframe.py
=> fix: __array__ for pandas (pyarrow dtypes) was raising for old versions of PyArrow

tests/expr_and_series/dt/to_string_test.py, tests/frame/slice_test.py, tests/series_only/to_list_test.py
- Closes #804 
Tiny trick for pyarrow using `str(value)`
=> test: remove `to_numpy` and `to_list` in tests

narwhals/_arrow/dataframe.py, narwhals/_pandas_like/dataframe.py, narwhals/_polars/dataframe.py, narwhals/dataframe.py, narwhals/stable/v1.py, tests/frame/slice_test.py
I kinda wish we didn't have to go overboard with `__getitem__` overloads, but scikit-learn are using this, so I think we should
My general thinking on this is: make sure that Narwhals is easily usable by scikit-learn. Then, it's their decision whether or not they adopt - but we should at least be ready
- Closes #
=> feat: support `__getitem__` with slices for columns

docs/api-reference/narwhals.md, narwhals/__init__.py, narwhals/_arrow/namespace.py, narwhals/_dask/namespace.py, narwhals/_expression_parsing.py, narwhals/_pandas_like/namespace.py, narwhals/_polars/namespace.py, narwhals/_polars/typing.py, narwhals/expr.py, narwhals/stable/v1.py, tests/expr_and_series/mean_horizontal_test.py
- Closes #814 
As `mean` can only be numeric, unlike #825, it is safe to fill nulls with zeros for the sum, and count the number of non-nulls summands.
=> feat: `mean_horizontal`

README.md
Sorry for making it a separate PR but I didn't know how to turn the gif into github-asset other than just droping it in the README.md (and didn't want to experiment with branches on github)
Does this looks now more clear and comprehensible?
Do you like the white background? I feel like it looks better in the README.md but if anybody what's back the cotton-candy-theme let me know.
- Closes #
=> narwhals-gif README.md

.github/release-drafter.yml
- Closes #
Trying to correct labelling - there is an issue with label "internal". 
The regex `^[C|c]hore|[CI|ci]|[R|r]efactor|[T|t]est|[T|t]emplate|[B|b]ench` used for internal was classifying other PRs.  I fail to understand why this regex would match and label "doc" as internal for example.
=> ci: changed release-drafter regex

.github/release-drafter.yml
- Closes #
It seems that the labeller is still having "issues". This PR was not labeled: https://github.com/narwhals-dev/narwhals/pull/850
The `|` inside the square brackets are not needed but should not cause a problem. 
If this doesn't fix it, maybe I should go back to the original setting of the release-drafter. Regex seems to work differently than locally. (What a surprise 🤓).
=> ci: Correct labeller regex

docs/api-reference/dependencies.md, narwhals/__init__.py, narwhals/dependencies.py, narwhals/stable/v1.py, narwhals/utils.py, tests/test_utils.py
closes #148 
I think this is all that's needed for that issue, then people can do:
```python
if nw.dependencies.is_pandas_like_dataframe(df):
index = nw.to_native(df).index
```
- Closes #
=> feat: Add is_pandas_like_dataframe and is_pandas_like_series

docs/other/column_names.md, narwhals/_expression_parsing.py, narwhals/dataframe.py, tests/frame/select_test.py
Quickly reverting https://github.com/narwhals-dev/narwhals/pull/828 before anyone uses it 🙈 
Parsing non-strings as expressions creates other problems, which I noticed while reviewing the when-then-otherwise PR
If people want to select columns which might not be strings, then can use `nw.col` and be explicit 😇 
- Closes #
=> feat: make DataFrame.select stricter: non-string columns can only be selected using `nw.col`

narwhals/stable/v1.py
- Closes #
Alternative of #864.
=> patch: Fix inconsistent between tying and comments in `from_native` when 'strict=True' 

narwhals/stable/v1.py, tests/frame/concat_test.py, tests/frame/test_invalid.py
See [comment](https://github.com/narwhals-dev/narwhals/pull/808?notification_referrer_id=NT_kwDOAo1WGLQxMTk5Nzg1MzA4Njo0MjgxNzA0OA#issuecomment-2308934423)
=> patch: stableify `concat` function

narwhals/_dask/namespace.py, tests/frame/concat_test.py
I've added in a `concat` method returning a `DaskLazyFrame`. One thing that *wasn't* tested for the `concat_test` was whether an error gets thrown trying to horizontally concat frames of different length. I'm not 100% sure what happens within polars/pandas when you do this, but dask will throw a confusing assertion error when you try to access anything within the dataframe, so I thought putting in a handy check here was worthwhile.
=> feat: dask namespace `concat` method 

narwhals/stable/v1.py, narwhals/translate.py, tests/stable_api_test.py, tests/translate/from_native_test.py
- Closes #833
@EdAbati helps a lot in discord! Thanks again!
=> patch: Improving typing of stable `from_native` when 'strict=False'

pyproject.toml
- Closes #
We currently have `utils/` in the tar.gz files, we should remove them
=> chore: Exclude `utils/` from build

.pre-commit-config.yaml, tests/test_utils.py
- Closes #
the previous regex seems to ignore anything that has `utils` in the path name (e.g. test_utils.py) 👀
=> chore: run mypy only on `narwhals/` and `tests/`

narwhals/functions.py, narwhals/stable/v1.py
I wrote the docstring's for concat function. Please have a look into it
=> docs: docstring for `concat`

.github/workflows/pytest.yml, docs/api-reference/dependencies.md, narwhals/_ibis/dataframe.py, narwhals/_ibis/series.py, narwhals/_interchange/dataframe.py, narwhals/dependencies.py, narwhals/translate.py, pyproject.toml, tests/frame/interchange_schema_test.py, tests/no_imports_test.py
=> feat: Better ibis interchange

narwhals/_arrow/utils.py, narwhals/_duckdb/dataframe.py, narwhals/_ibis/dataframe.py, tests/frame/interchange_schema_test.py
Rather than raise an error, we should just use `nw.Unknown`, like we do for the pandas backend. Then at least inspecting `.schema` won't crash. This is useful because you might want to just select, say, all string columns, and not care that there exists some unrecognised type
having said that, we could and should expand which dtypes we recognise
- Closes #
=> fix: use nw.Unknown for unknown dtypes

.github/workflows/check_tpch_queries.yml, pyproject.toml, requirements-dev.txt, tpch/requirements-tpch.txt, tpch/tests/test_queries.py
- Related issue #863 
- Closes https://github.com/narwhals-dev/narwhals-tpch/issues/2
The workflow runs a test to validate that the TPC-H queries actually execute. To run this workflow the tag 'full-test' must be added on a PR.
=> ci: add tests for the queries of TPC-H 

tests/expr_and_series/dt/datetime_attributes_test.py
- Closes #
xfail tests that use `dt.date` for cuDF as `dt.date` is not implemented
=> test: xfail `dt.date` tests for cuDF

narwhals/_arrow/dataframe.py, narwhals/_dask/dataframe.py, narwhals/_pandas_like/dataframe.py, narwhals/dataframe.py, tests/frame/join_test.py
- Related issue #896
- Closes #
=> feat: enable `on` key in `join_asof`

narwhals/_arrow/group_by.py, narwhals/_dask/group_by.py, narwhals/_pandas_like/group_by.py, tests/test_group_by.py
- Closes #915
Attempt for #915, comments in the code
=> patch: group by `n_unique`

tpch/execute/q12.py, tpch/execute/q13.py, tpch/execute/q14.py, tpch/execute/q16.py, tpch/execute/q22.py, tpch/queries/q12.py, tpch/queries/q13.py, tpch/queries/q14.py, tpch/queries/q16.py, tpch/queries/q22.py
- Related issue #863 
- Closes #
Not done for now, some fix needed.
=> feat: Add q12, q13, q14, q16, q22

CONTRIBUTING.md
Maybe we should just be opinionated and recommend `uv` in the contributing guide? My experience with it is that it "just works" in a way no other tool does
- Closes #
=> docs: Recommend `uv` in contributing guide

tpch/execute/q8.py, tpch/queries/q8.py
- Related issue #863 
- Closes #
=> feat: add q8 of tpch

narwhals/series.py
- Closes #
It looks like `drop_nans` isn't implemented. 
Was also thinking to update to use an example similar to https://narwhals-dev.github.io/narwhals/api-reference/expr/#narwhals.Expr.drop_nulls so it's easy to see the difference between Polars and pandas with `float("nan")`. What do you think @MarcoGorelli? Also, I'm curious - if `drop_nans` was to be implemented, would the expectation be that it would do the same as `drop_nulls` for pandas-like series?
=> doc: update drop_nulls for series documentation

narwhals/stable/v1.py, narwhals/utils.py
=> docs: fix docstring formatting on `maybe_align_index`

narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/series.py
- Related issue [#862](https://github.com/narwhals-dev/narwhals/issues/862)
- Closes #
This PR fixes issue seen in tests:
` ValueError: copy=False is not supported because conversion to a numpy array always copies the data.`
And reduces the number of failing tests by 7.
@MarcoGorelli the cuDF docs show `copy` defaults to `True` on cuDF. So I think that it should set `copy=True` here when it's `None` for cuDF. What do you think - Is that the right approach?
https://docs.rapids.ai/api/cudf/stable/user_guide/api_docs/api/cudf.series.to_numpy/
https://docs.rapids.ai/api/cudf/stable/user_guide/api_docs/api/cudf.dataframe.to_numpy/
=> fix: Update `copy` param on `to_numpy` to default to `True` for cuDF

narwhals/_dask/dataframe.py, tests/frame/filter_test.py
[Related comment](https://github.com/narwhals-dev/narwhals/issues/872#issuecomment-2338313251)
=> chore: ban dask filtering with boolean mask

README.md
=> docs: add `appears on` section with links to relevant podcasts/blogs

narwhals/expr.py, narwhals/series.py
- Closes #
When working on https://github.com/narwhals-dev/narwhals/pull/945, I noticed the parameters for `to_dummies` aren't rendering with the table of parameters like for other methods
This PR fixes it for this and a few others:
=> doc: update docstrings to fix rendering in generated docs

tests/series_only/to_dummy_test.py
- Closes #
`drop_first` is currently a non-functional argument for cuDF: https://docs.rapids.ai/api/cudf/stable/user_guide/api_docs/api/cudf.get_dummies/#cudf-get-dummies so these tests fail with `NotImplementedError: drop_first is not supported yet`
=> test: xfail `to_dummies` with `drop_first` test for cuDF

narwhals/_dask/group_by.py, narwhals/_pandas_like/group_by.py, tests/test_group_by.py
=> fix: group by no aggregation

narwhals/dataframe.py
- Closes #
https://narwhals-dev.github.io/narwhals/api-reference/lazyframe/#narwhals.dataframe.LazyFrame.clone is currently rendering incorrectly.
It looks like it needs to be indented to get it rendering like the other methods. Renders like this now
=> docs: update docstring to fix rendering in generated docs

tests/expr_and_series/dt/datetime_duration_test.py
- Related issue #  https://github.com/narwhals-dev/narwhals/issues/862
- Closes # 
There are ten tests here currently failing because it looks like `TimedeltaProperties` in cuDF doesn't have a `total_seconds` and all these tests depend on it.
https://github.com/rapidsai/cudf/blob/branch-24.10/docs/cudf/source/user_guide/api_docs/series.rst#timedelta-properties
docs start here: https://docs.rapids.ai/api/cudf/stable/user_guide/api_docs/api/cudf.core.series.timedeltaproperties.days/ 
```
FAILED tests/expr_and_series/dt/datetime_duration_test.py::test_duration_attributes[cudf_constructor-total_minutes-expected_a0-expected_b0-expected_c0] - AttributeError: 'TimedeltaProperties' object has no attribute 'total_seconds'
FAILED tests/expr_and_series/dt/datetime_duration_test.py::test_duration_attr …
```
=> test: xfail cuDF tests that use `total_seconds`

narwhals/_dask/dataframe.py, narwhals/_dask/expr.py, tests/frame/join_test.py, tpch/execute/q10.py, tpch/execute/q11.py, tpch/execute/q12.py, tpch/execute/q13.py, tpch/execute/q14.py, tpch/execute/q15.py, tpch/execute/q16.py, tpch/execute/q17.py, tpch/execute/q18.py, tpch/execute/q19.py, tpch/execute/q20.py, tpch/execute/q21.py, tpch/execute/q22.py, tpch/execute/q3.py, tpch/execute/q4.py, tpch/execute/q5.py, tpch/execute/q6.py, tpch/execute/q7.py, tpch/execute/q8.py, tpch/execute/q9.py, tpch/queries/q20.py, tpch/queries/q22.py
- Closes #
- Fix an issue with string keys in left and semi joins in Dask;
- Added an error message of `Expr.unique` is not supported for the Dask backend as it modifies the index;
- Added Dask to tpch benchmarks;
=> Bug: fix an issue with string keys in left and semi joins in Dask, add Dask to tpch benchmarks

tests/frame/join_test.py
- Closes #
cuDF doesn't have `merge_asof`, meaning the following tests fail:
```
FAILED tests/frame/join_test.py::test_joinasof_numeric[cudf_constructor] - AttributeError: module 'cudf' has no attribute 'merge_asof'
FAILED tests/frame/join_test.py::test_joinasof_time[cudf_constructor] - AttributeError: module 'cudf' has no attribute 'merge_asof'
FAILED tests/frame/join_test.py::test_joinasof_by[cudf_constructor] - AttributeError: module 'cudf' has no attribute 'merge_asof'
```
There's already an issue open for it https://github.com/rapidsai/cudf/issues/2231
=> test: xfail cuDF tests for `join_asof`

.github/workflows/check_docs_build.yml, .github/workflows/check_tpch_queries.yml, .github/workflows/downstream_tests.yml, .github/workflows/extremes.yml, .github/workflows/pytest.yml, .github/workflows/random_ci_pytest.yml
- Closes #955
Also added `cache-dependency-glob` pattern to revalidate the cache whenever the `requirements-dev.txt` file is changed. I hope this will work, gotta test it :)
=> ci: enable uv cache, use astral-sh official action

.github/workflows/extremes.yml
it took me way too long to figure this out, but github doesn't allow pull requests to access environment variables. which is probably a good thing?
- Closes #
=> ci: only run nightlies on pushes to main

narwhals/dataframe.py, tests/frame/row_test.py, tests/frame/rows_test.py
- Closes #
These tests currently fail:
```
FAILED tests/frame/row_test.py::test_row_column[cudf_constructor] - TypeError: Series object is not iterable. Consider using `.to_arrow()`, `.t...
FAILED tests/frame/rows_test.py::test_iter_rows[cudf_constructor-False-expected0] - TypeError: cuDF does not support iteration of DataFrame via itertuples. Con...
FAILED tests/frame/rows_test.py::test_iter_rows[cudf_constructor-True-expected1] - TypeError: cuDF does not support iteration of DataFrame via itertuples. Con...
```
Marking as `xfail` as iteration isn't supported here.
https://docs.rapids.ai/api/cudf/stable/user_guide/pandas-comparison/#iteration
https://docs.rapids.ai/api/cudf/stable/user_guide/api_docs/api/cudf.dataframe. …
=> test: xfail cuDF tests that use iteration

tests/expr_and_series/str/to_uppercase_to_lowercase_test.py
- Closes #
Looks like this one is passing
________ test_str_to_uppercase_series[cudf_constructor-data1-expected1] ________ [XPASS(strict)]
=> test: remove xfail for cudf_constructor on `str_to_uppercase` test

narwhals/_arrow/dataframe.py, narwhals/_arrow/utils.py, narwhals/dataframe.py, narwhals/stable/v1.py, tests/frame/slice_test.py, tests/series_only/slice_test.py
=> Bug: add conversion from slice to array for selecting rows in pyarrow `__getitem__` 

tests/utils.py
=> test: convert cuDF numpy types to python types in tests

narwhals/dataframe.py
=> add PyArrow usage example in docstrings `DataFrame.columns`

tests/expr_and_series/str/to_datetime_test.py
- Closes #
Currently this test fails with 
```
FAILED tests/expr_and_series/str/to_datetime_test.py::test_to_datetime[cudf_constructor] - AssertionError: assert '2020-01-01T1...:56.000000000' == '2020-01-01 12:34:56'
```
I created these in the native libraries and I see they have different data types and render differently when converted back to a string.
```
import pandas as pd
import cudf
data = {"a": ["2020-01-01T12:34:56"]}
df_cudf = pd.DataFrame(data)
df_pandas = pd.DataFrame(data)
df_pandas_dt = pd.to_datetime(df_pandas.a, format="%Y-%m-%dT%H:%M:%S")
df_cudf_dt = cudf.to_datetime(df_cudf.a, format="%Y-%m-%dT%H:%M:%S")
print(df_pandas_dt[0])
print(type(df_pandas_dt[0]))
print(df_cudf_dt[0]) …
```
=> test: add specific check for cuDF for test_to_datetime

docs/api-reference/dtypes.md, utils/check_api_reference.py
=> docs: add dtypes check in `utils/check_api_reference.py`

utils/generate_backend_completeness.py
After PR from yesterday, `pipe` got added independently of the class, leading to the following rendering:
With this fix, it will appear only if the class matches the backend
=> fix: generate backend table

docs/api-reference/expr_str.md, docs/api-reference/series_str.md, narwhals/_arrow/expr.py, narwhals/_arrow/series.py, narwhals/_dask/expr.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/series.py, narwhals/expr.py, narwhals/series.py, tests/expr_and_series/str/len_chars_test.py
- Closes #
It has been a while... 🫣
=> feat: add `str.len_chars`

narwhals/_pandas_like/dataframe.py, tests/frame/join_test.py
- Closes #
Right now these tests fail with
`NotImplementedError: Only indicator=False is currently supported`
So the current implementation of `df.join` `how="anti"` won't work.
https://docs.rapids.ai/api/cudf/stable/user_guide/api_docs/api/cudf.dataframe.merge/
Seemed like best to mark it as expected to fail for now. @MarcoGorelli what do you think would make sense here. Maybe a note in the docs and a follow up issue to see if we can implement it in another way for cuDF?
=> fix: add cuDF specific implementation for join how="anti"

narwhals/_arrow/series.py, narwhals/_interchange/series.py, narwhals/_pandas_like/series.py, narwhals/_polars/series.py, narwhals/series.py
=> feat: add `Series.dtype` return annotation

narwhals/dataframe.py, tests/frame/len_test.py
`__len__` should not appear in `dir(some_narwhals_lazy_frame)`, it will raise anyway but pushing the error to the compliant frame
=> fix: move `__len__` to `DataFrame` only

.github/release-drafter.yml
- Closes #
Bots 🤖 are being added in the Release Drafter as contributors, so I'm trying to correct that:
First added a new label to the repo and called it "ignore".  
That label should be set by the release drafter when the PR is opened by the  pre-commit bot.
Also, the "dependabot" (installed already in the repo) sets a label called "dependencies", but it was not included under the _exclude-labels._
=> build: Added PR labels so the Release Drafter ignores evil bots 

tests/series_only/to_numpy_test.py
- Closes #
It looks like cuDF doesn't allow `to_numpy` with nulls. Couldn't find much documentation, but it looks like maybe you need to specify an `na_value`
https://docs.rapids.ai/api/cudf/stable/user_guide/api_docs/api/cudf.series.to_numpy/#cudf.Series.to_numpy
=> test: `xfail` test using None on `to_numpy` for cuDF

tests/utils.py
- Closes #
https://github.com/narwhals-dev/narwhals/issues/862#issuecomment-2381278268
=> test: allow cuDF series in compare_dicts

tests/series_only/__iter___test.py
- Closes #
Test currently fails with :
```
FAILED tests/series_only/__iter___test.py::test_to_list[cudf_constructor] - TypeError: Series object is not iterable. Consider using `.to_arrow()`, `.t...
```
Because it's testing the iteration and that's not supported on cuDF, https://docs.rapids.ai/api/cudf/stable/user_guide/pandas-comparison/#iteration, it seems correct to xfail this one.
=> test: xfail __iter___test for cuDF

narwhals/_pandas_like/series.py, narwhals/_pandas_like/utils.py
=> chore: Refactor validate_column_comparand

narwhals/dataframe.py, narwhals/typing.py
- Closes #
Seems it should be `IntoDataFrameT`, without changing anything else, just rename it.
=> fix: Specialize typing in `dataframe` between `Frame` and `DataFrame`

tests/frame/unpivot_test.py
- Closes #
This was a new failing test for a recently added test:
```
>       assert result.collect_schema().names()[-2:] == [variable_name, value_name]
E       AssertionError: assert ['variable', ...m_value_name'] == ['', 'custom_value_name']
E         
E         At index 0 diff: 'variable' != ''
E         Use -v to get more diff
```
It looks like the empty string is treated as if it were None for `var_name` for `cudf.melt` (https://github.com/rapidsai/cudf/blob/branch-24.12/python/cudf/cudf/core/reshape.py#L684-L685)
Input
```
import cudf
import pandas as pd
data = {
"a": ["x", "y", "z"],
"b": [1, 3, 5],
"c": [2, 4, 6],
}
df_cudf = cudf.DataFrame(data)
df_pd = pd.DataFrame(data)
variable_name, value_name = "", …
```
=> test: xfail empty string test in `test_unpivot`

tests/expr_and_series/cast_test.py, tests/frame/unpivot_test.py
- Related issue # https://github.com/narwhals-dev/narwhals/issues/862#issuecomment-2388539725
- Closes #
=> test: xfail tz_aware test for cuDF

tests/frame/schema_test.py
- Closes #
@MarcoGorelli I took a look at this test and tried to implement what you mentioned here:
https://github.com/narwhals-dev/narwhals/issues/862#issuecomment-2365295750
When I do the following in cuDF directly, the types are `str`, and the docs note here seems to indicate it's not supported:
https://docs.rapids.ai/api/cudf/stable/user_guide/data-types/#a-note-on-object
```
import cudf
data = {'a': [1,2,3]}
df = cudf.DataFrame(data, dtype=object)
type(df['a'][1])
```
I believe that's why we return String here:
https://github.com/narwhals-dev/narwhals/blob/main/narwhals/_pandas_like/utils.py#L291-L299
So marking this as `xfail` seems correct. Let me know if you think there's anything else I could look a here.
=> test: xfail test_actual_object for cuDF

.github/workflows/downstream_tests.yml
=> ci: add py-shiny to downstream tests

narwhals/_pandas_like/group_by.py
- Closes # https://github.com/narwhals-dev/narwhals/issues/862
This is the final failing test on https://github.com/narwhals-dev/narwhals/issues/862 !
Currently it fails here:
```
narwhals/_pandas_like/group_by.py:215: in agg_pandas
result_aggs = native_namespace.DataFrame(grouped.groups.keys(), columns=keys)
/opt/conda/lib/python3.10/site-packages/cudf/utils/performance_tracking.py:51: in wrapper
return func(*args, **kwargs)
```
with
```
else:
if not is_dict_like(data):
>                   raise TypeError("data must be list or dict-like")
E                   TypeError: data must be list or dict-like
/opt/conda/lib/python3.10/site-packages/cudf/core/dataframe.py:852: TypeError
```
It looks like the `cudf.DataFrame` doesn't accept the `dict_keys` for `data`.
For example, …
=> fix: update no_agg to work with cuDF

narwhals/_arrow/dataframe.py, tests/frame/unpivot_test.py
- Related issue #1139
For plotly, this is enough (as one can't plot string values).
Yet I left a TODO, up for discussion, in case we want to allow numeric to be upcasted to string as well - drawback is that we should do that manually.
=> fix: pyarrow unpivot upcast numeric

docs/api-reference/narwhals.md, narwhals/__init__.py, narwhals/_arrow/namespace.py, narwhals/_dask/namespace.py, narwhals/_pandas_like/namespace.py, narwhals/_polars/namespace.py, narwhals/expr.py, narwhals/stable/v1/__init__.py, tests/expr_and_series/concat_str_test.py
- Closes #1116 
This was a bit harder/more complex than expected to get right. The idea being that polars can switch between:
- `ignore_nulls=False` (default), which means that a single null in the row will be propagated to the final result.
- `ignore_nulls=True`, when this happens, it is not as simple as replacing the null with an empty string, since otherwise the separator will get repeated (I am using a reduce). Also the separator "attached" to the same column and row needs to be nullified to empty string.
All this comes out of the box with polars>=0.20.6 and pyarrow (not sure about min version, CI will tell). On the other hand for pandas, dask and polars<0.20.6, a fair bit of manipulation had to be done, especially for `ignore_nulls=True`. 
The gist of it is using a null_mask, a list …
=> feat: `concat_str`

docs/api-reference/series_str.md, utils/check_api_reference.py
- Closes https://github.com/narwhals-dev/narwhals/issues/1133
Extends `utils/check_api_reference.py` to `Series.str` methods.
=> docs: add missing Series str methods in api reference

utils/check_api_reference.py
- Related issue https://github.com/narwhals-dev/narwhals/pull/1143#pullrequestreview-2350534830
Extends `utils/check_api_reference.py` to include methods from `Series.cat`, `Series.dt`, `Expr.cat`, `Expr.dt`, `Expr.name` and `Expr.str`. (Hope I haven't missed anything:))
=> docs: add missing methods in api reference

narwhals/_arrow/expr.py, narwhals/_arrow/series.py, narwhals/_dask/expr.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/series.py, narwhals/expr.py, narwhals/series.py, tests/expr_and_series/str/to_datetime_test.py
~~Opening as draft since~~ (Ok I misscliked) pyarrow is unsupported and may need some discussion for how to achieve it.
For context, this is the snippet in plotly that requires casting to datetime: [process_dataframe_timeline](https://github.com/plotly/plotly.py/blob/7181c4dbdd86400b2b984434e25128507aa8ea69/packages/python/plotly/plotly/express/_core.py#L1780)
=> feat: allow `format=None` in `str.to_datetime`

tests/frame/unpivot_test.py
- Closes # https://github.com/narwhals-dev/narwhals/issues/862
Marking this test as xfail for cuDF as it throws an error.
```
>               raise ValueError("all cols in value_vars must have the same dtype")
E               ValueError: all cols in value_vars must have the same dtype
```
And it looks like this is expected:
https://github.com/rapidsai/cudf/blob/branch-24.12/python/cudf/cudf/core/reshape.py#L651-L657
=> test: xfail test_unpivot_mixed_types for cuDF

mkdocs.yml, utils/generate_backend_completeness.py
- Closes https://github.com/narwhals-dev/narwhals/issues/1004
Separate out `DataFrame` and `LazyFrame` so as to create separate pages in the `api-completeness` section, while leaving `Series` and `Expr` as is.
Page rendering for `DataFrame` and `LazyFrame` is handled at "class-level", page rendering for `Series` and `Expr` remains at "module-level" (making sure `DataFrame` is not "processed" in both contexts).
=> docs: separate out DataFrame and LazyFrame in api-completeness

narwhals/_arrow/dataframe.py, tests/frame/rows_test.py
I'm in the camp of _slow support is better than no support_.
If there ever comes a time that pyarrow supports retrieving row values more natively, then this code can be updated.
- Related issue # NA
- Closes # NA
posit-dev/py-shiny uses `.rows(named=False)` to retrieve the values
=> enh: Add `.rows(named=False)` support for pyarrow

.github/workflows/downstream_tests.yml
Related: 
* posit-dev/py-shiny#1729
* posit-dev/py-shiny#1731
- Re lated issue # NA
- Closes # NA
The default `pytest` command does cover some tests, but others are ran under default settings. By integrating the make commands, `py-shiny` can update the internal script as things change without need for updates to `narwhals`.
=> chore: Use shiny's Makefile to allow for test commands to change over time

docs/api-reference/narwhals.md, narwhals/__init__.py, narwhals/_arrow/namespace.py, narwhals/_dask/namespace.py, narwhals/_pandas_like/namespace.py, narwhals/expr.py, narwhals/stable/v1/__init__.py, tests/expr_and_series/all_horizontal_test.py, tests/expr_and_series/max_horizontal_test.py, tests/expr_and_series/min_horizontal_test.py
=> feat: add `<min|max>_horizontal`

.github/workflows/downstream_tests.yml
- Closes #1163
Attempt at adding downstream tests for `marimo` to the CI pipeline. 
Notes:
- `marimo`'s full test suite also includes additional tests for frontend/cli etc.; I've omitted them as not relevant to the python backend testing functionality.
- `marimo` leverages on `hatch`, though `pyproject.toml` shows the following
> [tool.hatch]
installer = "uv"
- also, `test:test`, `test-optional:test` and `typecheck:check` do refer to the following `pytest` and `mypy` commands 
> [tool.hatch.envs.test.scripts]
test = "pytest{env:HATCH_TEST_ARGS:} {args:tests}"
...
[tool.hatch.envs.test-optional]
template = "test"
...
[tool.hatch.envs.typecheck.scripts]
check = "mypy marimo/"
All this said, I've kept the commands as-is (trying to align with the approach in …
=> ci: add downstream tests for `marimo`

.github/workflows/extremes.yml, .github/workflows/pytest.yml, narwhals/dataframe.py, narwhals/expr.py, narwhals/functions.py, narwhals/schema.py, narwhals/series.py, narwhals/stable/v1/__init__.py
It's frustrating to have to skip a lot of doctests because of version differences
I think we can just test them on the latest versions (like Polars does) - they're just intended to demonstrate functionality anyway, the proper testing is done in `tests`
- Closes #
=> ci: only check doctests on Python3.12

tests/expr_and_series/convert_time_zone_test.py, tests/expr_and_series/replace_time_zone_test.py, tests/series_only/to_dummy_test.py
- Closes #1187
- remove xfail from `test_to_dummies_drop_first` test as `drop_first` is now supported: https://github.com/rapidsai/cudf/issues/16791
- add xfail for https://github.com/rapidsai/cudf/issues/16973 while waiting for the next release
=> test: update cuDF tests

CONTRIBUTING.md
Some doctests do not work for lower Python versions so setting the contributing guide to install Python 3.12.
- Closes #
=> docs: Update CONTRIBUTING.md with Python 3.12

narwhals/_arrow/dataframe.py, narwhals/_pandas_like/dataframe.py, narwhals/dataframe.py, tests/frame/rows_test.py
- Related issue # --
- Closes # --
`posit-dev/py-shiny` specifically relies on `.rows(named=False)` to return unnamed rows. I'd like to be sure that narwhals also supports `.rows(named=False)` for as many types as possible.
`cuDF` currently does not support `.rows(named=False)`, however `.rows(named=True)` does work!
Reprex notebook: https://colab.research.google.com/drive/16AnZzkt0QpJ3NNad8qrmOqPBfUX_jFxa#scrollTo=uM8arylKIF1U
Reprex code:
```python
import narwhals as nw
import cudf
df = cudf.DataFrame(
{
"a": list(range(20)),
"b": list(reversed(range(20))),
"c": list(range(20)),
}
)
print(type(df))
print(df)
nw_df = nw.from_native(df, eager_only = True)
try:
nw_df.rows(named = False)
except Exception as e:
print("nw_df.rows(named=False)", str(e))
try:
list(nw_df.iter_rows(named = …
```
=> fix: Add df`.rows(named=False)` support for cuDF data frames

tests/frame/rows_test.py
=> test: xfail iter_rows tests for cudf

narwhals/expr.py, narwhals/stable/v1/__init__.py
- Related issue #1000 
Adds Pyarrow documentation example to `Expr.mean` in `expr.py`. If this looks good I can also work on the rest of `expr.py`.
=> docs: Add Pyarrow example to Expr.mean

mkdocs.yml
- Closes #
Currently it shows as the next page when on the `dtypes` page:
=> docs: move index to start of API reference

narwhals/_expression_parsing.py
=> perf: move `maybe_evaluate_expr` out of for loop in `reuse_series_implementation`

tests/expr_and_series/str/contains_test.py, tests/series_only/cast_test.py
- Closes #1199 
There are a few cases left in which we instantiate dataframes directly, but I think that's ok:
- hypothesis tests
- from_native tests, in which we add mocks to the list of constructors
=> chore: use constructors

narwhals/dataframe.py, noxfile.py
To be consistent with CI #1189 we should just run doctests in Python 3.12 in `nox`
=> chore: nox doctests only in Python 3.12

narwhals/expr.py, narwhals/functions.py, narwhals/stable/v1/__init__.py
- Related issue #1000 
PyArrow docstring examples for `narwhals/expr.py` and `narwhals/stable/v1/__init__.py`. 
I know #1000 mentions to do 4 functions in 1 PR, but was in a good flow so did the full `expr.py`. 😊  I think it's still within reason for review.
=> docs: Pyarrow example docstrings for `Expr` and stable v1 API

docs/api-reference/expr_dt.md, docs/api-reference/series_dt.md, narwhals/_arrow/expr.py, narwhals/_arrow/series.py, narwhals/_dask/expr.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/series.py, narwhals/_pandas_like/utils.py, narwhals/expr.py, narwhals/series.py, tests/expr_and_series/dt/datetime_attributes_test.py, tests/expr_and_series/dt/timestamp_test.py
=> enh: add dt.timestamp

.github/workflows/downstream_tests.yml, README.md
=> ci: add tubular in ci checks

.gitignore, mkdocs.yml, utils/generate_zen_content.py
Adds dedicated docpage for rendering the ZEN dynamically:
=> docs: zen dedicated doc page

narwhals/expr.py, narwhals/series.py
N/A
Fixes rendering of parameters table at https://narwhals-dev.github.io/narwhals/api-reference/expr/#narwhals.Expr.quantile and https://narwhals-dev.github.io/narwhals/api-reference/series/#narwhals.series.Series.quantile.
From 
to
=> docs: fix parameters table rendering in `quantile` docs

narwhals/_pandas_like/series.py, tests/expr_and_series/dt/datetime_duration_test.py
- Related issue # https://github.com/narwhals-dev/narwhals/pull/951#issuecomment-2355243405
- Closes #
this is implementing total_seconds for cuDF
@MarcoGorelli 
Is this the type of implementation you had in mind when you said it might be [possible using other components](https://github.com/narwhals-dev/narwhals/pull/951#issuecomment-2355243405)?
This has the tests passing but I was curious for feedback on using a private method here that returns either the calculated `total_seconds` or calls the series method `total_seconds`. I couldn't find examples of us doing anything similar.
=> feat: Add total seconds implementation for cuDF

README.md, docs/basics/dataframe_conversion.md, mkdocs.yml, tests/expr_and_series/dt/timestamp_test.py
A new tutorial with ultra-simple examples of DataFrame conversion functions using Narwhals.
I maintain a library which uses Polars internally. I want to allow my users to supply any DataFrame format, but I don't want to re-write my library's code, and not all the methods I use are already implemented in Narwhals.
For me, the most attractive application of Narwhals is to use it to "ingest" any DataFrame, and convert them to Polars for internal use. This is the lowest barrier to entry approach to Narwhals, and my guess is that *many* users would like this.
Given the likely popularity of this workflow, I think it deserves its own page and tutorial on the website.
=> DataFrame conversion tutorial

narwhals/_pandas_like/dataframe.py, tests/translate/from_native_test.py
This should help with https://github.com/Quantco/glum/pull/868
Demo:
```python
In [1]: df
Out[1]: 
a  a  a  b  b  c
a  1  2  3  4  5  6
In [2]: nw.from_native(df)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[2], line 1
----> 1 nw.from_native(df)
File ~/polars-api-compat-dev/narwhals/stable/v1/__init__.py:833, in from_native(native_dataframe, strict, eager_only, eager_or_interchange_only, series_only, allow_series)
831 if isinstance(native_dataframe, Series) and (series_only or allow_series):
832     return native_dataframe
--> 833 result = _from_native_impl(
834     native_dataframe,
835     strict=strict,
836     eager_only=eager_only,
837 …
```
=> feat: better error message for duplicate column names in pandas

mkdocs.yml
- Closes #
I think it's easier to find info on ToC if it's ordered.. but feel free to ignore me :-)
The extra_css is not needed and causes a 404.
=> docs: Render table of contents members ordered & removed css reference

narwhals/_arrow/utils.py, tests/expr_and_series/str/to_datetime_test.py
- Related issue #1282
- Closes #
=> Enh: adding automated inferencing of format `%Y-%m-%dT%H:%M` in pyarrow

narwhals/translate.py, tests/translate/to_py_scalar_test.py
=> fix: np.datetime64 scalar with ns resolution was become int instead of datetime in to_py_scalar

narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/series.py, tests/conftest.py, tests/frame/to_numpy_test.py, tests/series_only/to_numpy_test.py
=> fix: consistent to_numpy behaviour for tz-aware

narwhals/_pandas_like/utils.py, tests/dtypes_test.py
=> fix: fixed-offset datetime weren't being parsed

.github/workflows/downstream_tests.yml, .github/workflows/publish_to_pypi.yml
=> ci: add vegafusion in ci checks

docs/backcompat.md, narwhals/stable/v1/__init__.py, tests/stable_api_test.py
technically breaking, but in practice, from:
- https://github.com/search?q=%22nw.from_native%28native_dataframe%3D%22&type=code
- https://github.com/search?q=%22nw.from_native(%22&type=code
it looks like this affects _zero_ public repositories. People just pass this argument in positionally. We might as well just make the change now then, so as to limit the stable.v1 vs main namespace differences
- Closes #
=> fix: consistent naming of positional arguments in from_native

docs/backcompat.md, narwhals/dataframe.py, narwhals/functions.py, narwhals/stable/v1/__init__.py, narwhals/translate.py, narwhals/utils.py, tests/translate/from_native_test.py, tests/translate/narwhalify_test.py, tests/translate/to_native_test.py
=> depr: deprecate `strict` in `from_native` / `to_native` in favour of `pass_through`

narwhals/_arrow/dataframe.py, narwhals/_arrow/expr.py, narwhals/_arrow/series.py, narwhals/_dask/dataframe.py, narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/series.py, narwhals/dataframe.py, narwhals/expr.py, narwhals/series.py, tests/expr_and_series/unique_test.py
=> feat: add `maintain_order` to Expr.unique and Series.unique 

narwhals/functions.py, narwhals/stable/v1/__init__.py
- Closes #
I wasn't sure if more documentation should be added to the function `get_level` (see [here](https://github.com/narwhals-dev/narwhals/blob/main/narwhals/functions.py#L596)). It's public but it's not really part of the "core functionality".
=> docs: add "returns" documentation to functions.py

.github/workflows/bump-version.yml, .github/workflows/downstream_tests.yml, .github/workflows/downstream_tests_slow.yml, .github/workflows/publish_to_pypi.yml
- Related PR #1228 
EDIT: I changed my mind 😄 I think the "slow tests" and the "publish" workflows should all run in the bump-version PR. So we can see if everything went well before merging.
The flow would be:
1. bump version
2. PR with new tag
3. Publish workflow starts along side all other workflows
4. The publish workflow triggers the "slow tests" workflow and wait for completion
5. Library published
6. merge release PR to main and celebration
~The slow tests are triggered when a tag is pushed to a branch that is _not_ `main`. Since "Bump version" creates a tag on a `bump-version` branch, this should also trigger the slow tests when the bump version PR is made. 
I also changed the "Publish Python" workflow to be triggered on tag pushes on `main`.~
~The flow would be:~
~1. bump …
=> ci: trigger slow downstream libraries tests suites before release

narwhals/_arrow/group_by.py
According to Marco's performance benchmarking for plotly, the bottleneck for a few functions seems to be the call we do to `ArrowGroupBy.__iter__`.
Since pyarrow does not natively support iterating over groups, we (actually pointing finger to myself) implemented a (let's say naive) way of still allowing for that - I remember the use case was for scikit-lego to fully support arrow as well.
This PR tries to improve those performances using native arrow methods and no simple shortcuts. Steps are as follow:
- Create an array containing the string concatenation of the key values (after casting to string). Null handling is required.
- Add the column to the original table
- Return the pair of :
- key values, obtained as first (and unique) value of filtered table for the key names.
- sliced …
=> perf: improve `ArrowGroupBy.__iter__` performances

docs/api-reference/expr.md, docs/api-reference/narwhals.md, docs/api-reference/series.md, narwhals/__init__.py, narwhals/_arrow/expr.py, narwhals/_arrow/group_by.py, narwhals/_arrow/namespace.py, narwhals/_arrow/series.py, narwhals/_dask/expr.py, narwhals/_dask/namespace.py, narwhals/_exceptions.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/namespace.py, narwhals/_pandas_like/series.py, narwhals/_polars/namespace.py, narwhals/_polars/series.py, narwhals/expr.py, narwhals/series.py, narwhals/stable/v1/__init__.py, tests/expr_and_series/median_test.py, tests/expr_and_series/unary_test.py, tests/group_by_test.py
- Closes https://github.com/narwhals-dev/narwhals/issues/1190
WIP: I would need to better dig into details for `pyarrow` and `dask`. Already opened the PR to (also) get advices and/or guidance:)
My understanding per now (might be missing bits, though) is the following:
- neither `pyarrow` nor `dask` do implement a "proper" `median`; otoh, they respectively implement `approximate_median` and `median_approximate` (`dask`'s `median_approximate` fails tests when `npartitions=2`, though)
- relying on already implemented `quantile`(s) would come with the following issues: for `pyarrow`, the issue of having an `interpolation` parameter which would not quite fit the `nw.median()` signature; for dask, the issue of having to hardcode a `"linear"` interpolation strategy and having to `xfail` tests …
=> feat: add support for `median`

.github/workflows/downstream_tests.yml, narwhals/_arrow/utils.py, tests/expr_and_series/str/to_datetime_test.py
=> feat: pyarrow automated inference of format `%Y%m%d%H%M%S` 

narwhals/_arrow/namespace.py, narwhals/_dask/namespace.py, narwhals/_pandas_like/namespace.py, narwhals/expr.py, narwhals/stable/v1/__init__.py, tests/frame/lit_test.py
- Closes https://github.com/narwhals-dev/narwhals/issues/1346
Makes output names out of `nw.lit` be consistent with `polars`'s `"literal"` across backends. Updates docstrings for `nw.lit` by not aliasing column name to possibly make that clearer.
=> fix: Fix `nw.lit` out names

.github/workflows/pytest.yml, narwhals/expr.py, narwhals/stable/v1/__init__.py
- Closes #
The docstring tests didn't run in CI. The Python version for testing docstrings is changed to 3.13 whereas for ibis tests it is changed to 3.11. The outputs are fixed.
=> test: fix docstrings tests in CI

narwhals/utils.py, tests/utils_test.py
- Related issue #1239
- Closes #
[Pandas set_index docs](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html#pandas-dataframe-set-index)
[Pandas set_index test cases](https://github.com/pandas-dev/pandas/blob/9a015d19514597ad5d1c31f566a0a2bdb17d4cc5/pandas/tests/frame/methods/test_set_index.py#L309)
I've renamed the `column_names: str | list[str]` parameter to `keys: str | Series | list[Series | str]`. I referenced the Pandas docs where which have `keys: label or array-like or list of labels/arrays`. Since this is a backwards-compatability function, I figured it is good for it to be close to the Pandas spec, and the original param name `column` doesn't cover all cases anymore.
=> feat: support passing index object directly into maybe_set_index

narwhals/_arrow/dataframe.py, narwhals/_arrow/utils.py, narwhals/expr.py, narwhals/stable/v1/__init__.py
While profiling for plotly, py-spy indicates that we spend a lot of time in `validate_dataframe_comparand` for pyarrow case. This is called only in `with_columns` methods.
This PR proposed two changes:
- Creates constant array via `np.full` in `validate_dataframe_comparand` instead of `[const] * length`
- Changes the logic in `with_columns` to use pyarrow native methods to insert a column value. I expect this to be faster than the current approach of concatenating the already existing columns with the new ones - caveat is if the number of new columns is order(s) of magnitude greater than the existing ones. In _majority_ of scenarios I would expect this to not be the case, but this is the reason I am opening this as **RFC**
=> chroe: refactor `ArrowDataFrame.with_columns`

docs/api-reference/expr.md, docs/api-reference/series.md, narwhals/_arrow/expr.py, narwhals/_arrow/series.py, narwhals/_dask/expr.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/series.py, narwhals/_polars/expr.py, narwhals/_polars/series.py, narwhals/expr.py, narwhals/series.py, tests/expr_and_series/cum_count_test.py, tests/expr_and_series/cum_sum_test.py
- Related issue #1371
I have dask skill issues. Replicating what works for pandas raises an error:
>     def _divisions(self):
>        # This is an issue.  In normal Dask we re-divide everything in a step
>        # which combines divisions and graph.
>        # We either have to create a new Align layer (ok) or combine divisions
>        # and graph into a single operation.
>        dependencies = self.dependencies()
>        for arg in dependencies:
>            if not self._broadcast_dep(arg):
>               assert arg.divisions == dependencies[0].divisions
> E               AssertionError
Code:
```py
def cum_count(self, reverse):
def func(_input: dask_expr.Series, _reverse: bool) -> dask_expr.Series:
not_na_series = (~_input.isna()).astype(int)
return (
not_na_series.cumsum()
if not …
```
=> feat: add `Series|Expr.cum_count` method

narwhals/dtypes.py
Just a quick check: considering I'll have to use cast to get some of the datatypes, maybe I should wrap the from_native into a func after all?
- Related issue #1077
- Closes #
=> docs : docstrings examples - dtypes

docs/api-reference/expr.md, docs/api-reference/series.md, narwhals/_arrow/expr.py, narwhals/_arrow/series.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/series.py, narwhals/expr.py, narwhals/series.py, tests/expr_and_series/cum_count_test.py, tests/expr_and_series/cum_max_test.py, tests/expr_and_series/cum_min_test.py
=> feat: add `Series|Expr` `cum_min` and `cum_max` methods

docs/api-reference/expr.md, docs/api-reference/series.md, narwhals/_arrow/expr.py, narwhals/_arrow/series.py, narwhals/_dask/expr.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/series.py, narwhals/expr.py, narwhals/series.py, tests/expr_and_series/cum_count_test.py, tests/expr_and_series/cum_min_test.py, tests/expr_and_series/cum_prod_test.py, tests/expr_and_series/cum_sum_test.py
- Related issue #1371 
This is 3 folded (I could not resist)
- Introduce `cum_prod`
- Adds `reverse` in `cum_sum`
- Adds cumulative methods for dask if `reverse=False`, raise otherwise
=> feat: add `Series|Expr.cum_prod` method, add `reverse` kw in `cum_sum` method

docs/backcompat.md, docs/pandas_like_concepts/boolean.md
This is just a proposal. I find all the `print` statements hard to read. Maybe we can use content tabs instead. Drawback is that not all outputs are rendered at once.
Screenshot:
Let me know what you think
=> docs: pandas boolean content tabs

narwhals/exceptions.py, tests/frame/select_test.py
- Related comment https://github.com/narwhals-dev/narwhals/issues/1390#issuecomment-2481199944
=> chore: update `InvalidIntoExprError` to mention `nw.lit`

narwhals/dataframe.py
Description was missing though mentioned in the options:
Also, updated reference to LazyFrame on DataFrame object.
=> docs: add missing description for left join strategy

.github/workflows/pytest.yml, noxfile.py
related to https://github.com/ibis-project/ibis/issues/10492
=> ci: prevent ibis from setting upper bounds (where possible)

docs/api-reference/exceptions.md, docs/api-reference/expr.md, docs/api-reference/series.md, narwhals/_arrow/expr.py, narwhals/_arrow/series.py, narwhals/_dask/expr.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/series.py, narwhals/exceptions.py, narwhals/expr.py, narwhals/series.py, narwhals/stable/v1/__init__.py, tests/expr_and_series/rolling_sum_test.py
- Related issue #1254
- Closes #1367 
So I wanted to start with `sum`, assuming it would have been simpler for arrow to implement in a way which is not naive.
Running some benchmarks, performances of this with 1M rows is in the same ballpark of pandas, while the naive way in #1290 is orders of magnitude slower. I would consider this the way to go forward.
=> feat: add `Series|Expr.rolling_sum` method

.github/workflows/downstream_tests.yml
Since yesterday the PR to [narwhalify plotly express](https://github.com/plotly/plotly.py/pull/4790) got merged, we should start to include (some) plotly tests in our ci as promised!
Opening this as draft because it was not fully decided which tests should be run.
@emilykl this is along the lines of how we would test that each commit does not end up breaking plotly via its unit tests
Associated plotly issue: https://github.com/plotly/plotly.py/issues/4864
=> ci: add plotly to downstream tests

.pre-commit-config.yaml, narwhals/dataframe.py, narwhals/expr.py, narwhals/series.py, narwhals/stable/v1/__init__.py, tests/stable_api_test.py
=> docs: use from_native / to_native in series.py

narwhals/series.py
Start updating more docstrings, pending discussion in #1407 
=> docs: use type hints + from_native/to_native in series.py

narwhals/dataframe.py, narwhals/stable/v1/__init__.py
=> docs: use type hints + from_native/to_native in dataframe.py

narwhals/_polars/expr.py, narwhals/_polars/series.py, tests/expr_and_series/ewm_test.py
- Closes #1414
Trying to close that issue,  ~~but I haven't checked with older polars versions than that.~~
**Not ready for review**
=> fix: correct minimum Polars version for ewm_mean

docs/api-reference/index.md, docs/api-reference/lazy_group_by.md, mkdocs.yml, narwhals/group_by.py
I saw that `LazyGroupBy` was not documented so I did it. Let me know if there are mistakes or if you would like changes.
=> docs: Add documentation for LazyGroupBy

.github/workflows/check_docs_build.yml, docs/requirements-docs.txt, narwhals/stable/v1/__init__.py, narwhals/translate.py
=> docs: explain optional boolean args in from_native

narwhals/_arrow/dataframe.py, narwhals/_dask/dataframe.py, narwhals/_pandas_like/dataframe.py, narwhals/dataframe.py, narwhals/expr.py, tests/expr_and_series/filter_test.py
=> feat: support `constraints` in `DataFrame.filter`

narwhals/_arrow/series.py
=> fix: return Python bool instead of pyarrow boolean scalar for Series reductions

narwhals/dependencies.py
The cuDF tests for `is_pandas_dataframe` were failing.
=> BUG: remove cudf from import hooks

pyproject.toml, tests/expr_and_series/ewm_test.py, tests/expr_and_series/str/to_datetime_test.py, tests/frame/pivot_test.py
For pivot, they have a fix in place, so we can remove the xfail once they make a new release: https://github.com/rapidsai/cudf/pull/17373
In the meantime, let's make sure to have the test suite passing so we can include it in the release process (for now, manually)
=> ci: get cudf tests passing again

narwhals/_pandas_like/series.py, tests/expr_and_series/ewm_test.py
cuDF tests were failing for `ewm_mean`.
=> feat: raise `NotImplementedError` for not supported parameters in `ewm_mean` for cuDF

.github/workflows/downstream_tests.yml, .pre-commit-config.yaml, narwhals/stable/v1/__init__.py, narwhals/translate.py, requirements-dev.txt, utils/check_docstrings.py
It looks like other linters don't pick this up, so we need to roll our own script
inspired by @LiamConnors 's work in https://github.com/narwhals-dev/narwhals/pull/1448 - this at least picks up unused imports
also:
closes #1344 
=> ci: Check docstrings don't have unused imports in docstring examples

narwhals/_arrow/dataframe.py, narwhals/_arrow/series.py, narwhals/_dask/dataframe.py, narwhals/_duckdb/dataframe.py, narwhals/_ibis/dataframe.py, narwhals/_interchange/dataframe.py, narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/series.py, narwhals/_polars/dataframe.py, narwhals/_polars/series.py, narwhals/stable/v1/__init__.py, tests/from_dict_test.py, tests/translate/from_native_test.py
closes #1457 
merging as "hot fix" but really we should probably redesign this so that `_dtypes` is a property of `nw.DataFrame` / `nw.LazyFrame` / `nw.Series`, rather than of the compliant objects
=> fix: Preseve dtypes modules in from dict

narwhals/__init__.py, narwhals/selectors.py, narwhals/stable/v1/__init__.py, narwhals/stable/v1/selectors.py, tests/selectors_test.py
=> feat: allow for "import narwhals.stable.v1.selectors as cs"

.github/workflows/downstream_tests.yml, README.md
=> ci: add hierarchicalforecast

narwhals/_arrow/namespace.py, narwhals/_arrow/utils.py, narwhals/_dask/namespace.py, narwhals/_pandas_like/namespace.py, narwhals/_pandas_like/utils.py, narwhals/_polars/namespace.py, narwhals/functions.py, narwhals/stable/v1/__init__.py, tests/frame/concat_test.py
=> feat: diagonal concat

.github/workflows/downstream_tests.yml, docs/api-reference/narwhals.md, narwhals/__init__.py, narwhals/functions.py, narwhals/stable/v1/__init__.py, tests/from_numpy_test.py
=> feat: create dataframe from 2D numpy array and column names

docs/backcompat.md, docs/basics/complete_example.md, docs/basics/dataframe.md, docs/basics/series.md, docs/extending.md
- Closes #1372 
Adds both options in all the documentation examples by using tabs
=> docs: add `from/to_native` in documentation examples

narwhals/_arrow/expr.py, narwhals/_arrow/namespace.py, narwhals/_arrow/series.py, narwhals/_arrow/utils.py, narwhals/_dask/expr.py, narwhals/_expression_parsing.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/namespace.py, narwhals/_pandas_like/series.py, narwhals/_pandas_like/utils.py, narwhals/_polars/series.py, narwhals/series.py, pyproject.toml, tests/expr_and_series/arithmetic_test.py, tests/expr_and_series/operators_test.py, tests/frame/lit_test.py, tests/utils.py
- Resolves #853, resolves #509
Opening as draft to get comments/guidance on the approach. Also, (1) `Dask` behaviour, (2) column name resulting from right arithmetics _on Series_ in `Polars`, (3) leftover _binary dunder methods_ need more thourough exploration on my side.
Another point, this PR should solve both of the issues in principle. I combined the two fixes because I originally thought that the second (#509) could naturally be resolved as a consequence of the first, but at the end that's not really the case (at least via the approach I followed). Perhaps I should separate the two?
#853:
- Tweak `validate_column_comparand` in `_pandas_like` so as to reindex `other` via the lhs series only when possible (which is what the error message was complaining about when outputting …
=> fix: address `lit` broadcasting and output name of right arithmetic ops

.github/workflows/publish_to_pypi.yml, utils/bump_version.py
Like this the job can be run manually, but I'm not sure it should be required for releases - we already have several other downstream libraries we test against, and vegafusion is by far the one with the slowest tests
=> ci: Remove vegafusion from blocking releases, assert current branch in bump_version

narwhals/dataframe.py
NA
Cleans _lazyframe_ docstrings
- All references to lazyframes as `lf_pl`
- `from_native`/`to_native` instead of `narwhalify`
- `agnostic_func` instead of `func`
=> docs: clean lazyframe docstrings

narwhals/dtypes.py, narwhals/stable/v1/_dtypes.py
Should we consider closing #1077?
Noticed that Int16 was not rendering properly. I used to opportunity to add descriptions to other types
=> patch: fix dtypes rendering

narwhals/_pandas_like/series.py
=> Remove the unused code in pandas like series

narwhals/_arrow/dataframe.py, narwhals/_arrow/series.py, narwhals/_dask/dataframe.py, narwhals/_duckdb/dataframe.py, narwhals/_ibis/dataframe.py, narwhals/_interchange/dataframe.py, narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/series.py, narwhals/_polars/dataframe.py, narwhals/_polars/series.py, narwhals/stable/v1/__init__.py, tests/translate/from_native_test.py
=> chore: rename _change_dtypes to _change_version

narwhals/__init__.py, narwhals/_arrow/series.py, narwhals/_pandas_like/series.py, narwhals/_polars/series.py, narwhals/series.py, narwhals/stable/v1/selectors.py, pyproject.toml, tests/selectors_test.py, tests/series_only/__contains___test.py, utils/check_api_reference.py
=> feat: add `Series.__contains__`

noxfile.py
If the dependencies are not in a `list[str]`, the following fails locally:
=> test: fix nox dependencies

CONTRIBUTING.md
=> docs: update contributing guide by adding upstream remote

narwhals/_pandas_like/series.py
- Related issue #1499 
PandasLikeSeriesCatNamespace
PandasLikeSeriesDateTimeNamespace
PandasLikeSeriesStringNamespace
PandasLikeExprCatNamespace
PandasLikeExprDateTimeNamespace
PandasLikeExprStringNamespace
PandasLikeExprNameNamespace
ArrowSeriesCatNamespace
ArrowSeriesDateTimeNamespace
ArrowSeriesStringNamespace
ArrowExprCatNamespace
ArrowExprDateTimeNamespace
ArrowExprStringNamespace
ArrowExprNameNamespace
PolarsSeriesCatNamespace
PolarsSeriesDateTimeNamespace
PolarsSeriesStringNamespace
PolarsExprCatNamespace
PolarsExprDateTimeNamespace
PolarsExprStringNamespace
PolarsExprNameNamespace
DaskExprCatNamespace
DaskExprDateTimeNamespace
DaskExprStringNamespace
DaskExprNameNamespace
=> chore: in _series renamed _pandas_series to _compliant_series

narwhals/_arrow/namespace.py, narwhals/_dask/namespace.py, narwhals/_expression_parsing.py, narwhals/_pandas_like/namespace.py
This gets rid of some `type: ignore`s and casts in _pandas_like / _dask / _arrow
=> chore: overload parse_into_expr

narwhals/_pandas_like/expr.py
Renamed `_expr` to `_compliant_expr` in the following classes:
- Related issue #1499
`pytest —vvl`
before: 
5113 passed, 64 skipped, 168 xfailed in 27.37s
after:
5113 passed, 64 skipped, 168 xfailed in 27.27s
=> chore: rename `_expr` to `_compliant_expr` in `PandasLikeExpr`

CONTRIBUTING.md
- Related issue #1526 
I added a new section to the Contributing docs about checking for an existing SSH key and linking to the "Generating SSH Key" GitHub docs.
=> docs: add link to "Generating a new SSH key"

docs/api-reference/dataframe.md, docs/api-reference/lazyframe.md, docs/api-reference/series.md, narwhals/__init__.py, narwhals/dataframe.py, narwhals/series.py, narwhals/stable/v1/__init__.py, narwhals/utils.py, tests/implementation_test.py, utils/check_api_reference.py
=> feat: Expose nw.Implementation, along with `Implementation.is_pandas`, `Implementation.is_pandas_like`, and more

narwhals/_arrow/expr.py, narwhals/_arrow/series.py, narwhals/_dask/expr.py, narwhals/_polars/expr.py, narwhals/_polars/series.py
- Related issue #1499 
- Renamed `_arrow_series` to `_compliant_series` in `ArrowSeries` classes (_ArrowSeriesCatNamespace, ArrowSeriesDateTimeNamespace, ArrowSeriesStringNamespace_)
- Renamed `_expr` to `_compliant_expr` in `ArrowExpr` classes (_ArrowExprCatNamespace, ArrowExprDateTimeNamespace, ArrowExprStringNamespace, ArrowExprNameNamespace_)
- Renamed `_series` to `_compliant_series` in `PolarsSeries` classes (_PolarsSeriesCatNamespace, PolarsSeriesDateTimeNamespace, PolarsSeriesStringNamespace_)
- Renamed `_expr` to `_compliant_expr` in `PolarsExp` classes (_PolarsExprCatNamespace, PolarsExprDateTimeNamespace, PolarsExprStringNamespace, PolarsExprNameNamespace_)
- Renamed `_expr` to `_compliant_expr` in several `DaskExpr` classes (_DaskExprDateTimeNamespace, DaskExprStringNamespace, …
=> chore: rename `series` and `expr` to `_compliant` for Arrow, Polars, and Dask

narwhals/_polars/namespace.py
NA, addresses https://github.com/narwhals-dev/narwhals/pull/1212#discussion_r1806719080 for `mean` as well.
Avoids unnecessary branching based on `polars` version.
Stumbled upon the above comment by chance, I _think_ we might do the same on `mean` for coherence.
Perhaps I might also take the opportunity to work on unifying exceptions for strings handling in reduction methods that might need it (and _where_ feasible), leveraging the takeaways of the referenced PR and in the spirit of https://github.com/narwhals-dev/narwhals/issues/1373? Might it be useful/reasonable (though not particularly urgent ofc)?
=> chore: avoid unnecessary branching on pl version in `pln.mean`

narwhals/_arrow/series.py, tests/series_only/slice_test.py
=> fix: return Python scalar for Series.__getitem__ when pyarrow-backed (like Polars does)

docs/api-reference/dataframe.md, narwhals/_arrow/dataframe.py, narwhals/_pandas_like/dataframe.py, narwhals/dataframe.py, narwhals/typing.py, narwhals/utils.py, tests/frame/estimated_size_test.py
- Closes #1535
~~EDIT: Forgot to push the test file, but it looks like it needs some work~~
=> feat: Adding dataframe estimated size

docs/api-reference/narwhals.md, narwhals/__init__.py, narwhals/functions.py, narwhals/stable/v1/__init__.py, tests/read_csv_test.py
=> feat: `read_csv`

docs/api-reference/narwhals.md, narwhals/__init__.py, narwhals/functions.py, narwhals/stable/v1/__init__.py, tests/scan_csv_test.py
=> feat: `scan_csv`

narwhals/functions.py, narwhals/stable/v1/__init__.py, tests/read_csv_test.py, tests/scan_csv_test.py
=> feat: add `**kwargs` to `read_csv` and `scan_csv`

.github/release-drafter.yml, .github/workflows/publish_to_pypi.yml, .github/workflows/release-drafter.yml, .pre-commit-config.yaml
`pull_request_target` is flagged as unsafe by [zizmor](https://github.com/woodruffw/zizmor)
in wake of https://blog.pypi.org/posts/2024-12-11-ultralytics-attack-analysis/, i think it might be best to just remove it
we'll just have to remember to set labels before merging, but i think we can get into that habit - else we just fixup the release notes before publishing, no big deal
=> ci: remove pull_request_target, sanitise github.ref_name

narwhals/_arrow/dataframe.py, narwhals/_arrow/series.py, narwhals/_arrow/utils.py, narwhals/_duckdb/dataframe.py, narwhals/_duckdb/series.py, narwhals/_ibis/dataframe.py, narwhals/_ibis/series.py, narwhals/_pandas_like/utils.py, narwhals/_polars/utils.py, narwhals/_spark_like/utils.py
closes #1562 
This makes `.schema` about twice as fast for Polars / DuckDB
Not a game-changer, but nice to have
=> perf: use lru_cache for native_to_narwhals_dtype

docs/api-reference/dtypes.md, narwhals/__init__.py, narwhals/_arrow/utils.py, narwhals/_duckdb/dataframe.py, narwhals/_ibis/dataframe.py, narwhals/_pandas_like/utils.py, narwhals/_polars/utils.py, narwhals/_spark_like/utils.py, narwhals/dtypes.py, narwhals/stable/v1/__init__.py, narwhals/stable/v1/_dtypes.py, narwhals/stable/v1/dtypes.py, narwhals/typing.py, tests/dtypes_test.py
=> feat: add Decimal dtype

tpch/execute.py
=> refactor: use `nw.scan_parquet` in tpch benchmarks

narwhals/dataframe.py
- Related issue #1293 
This is currently work in progress. Feel free to start reviewing. :)
=> docs: document arguments and returns in DataFrame class

narwhals/functions.py, narwhals/series.py, narwhals/stable/v1/__init__.py
=> docs: make docstring examples function names more descriptive in functions.py

narwhals/dataframe.py
I keep chipping away at this. :)
=> docs: more args and returns documentation in DataFrame class

docs/pandas_like_concepts/null_handling.md, mkdocs.yml, narwhals/dataframe.py, narwhals/expr.py, narwhals/series.py
- Closes #1401 
- Adds reference page for Null/NaN handling to docs.
- _if_ the example on how `is_null` behaves across backends is not redundant with respect to the docstrings examples and good to stay there, we might think of adding an example about `is_nan` as well (as soon as we add it)
- Removes `NaN` as entry when initializing dataframes/series in `Polars` and `PyArrow` docstrings (need to recheck whether I've been consistent).
=> docs: null handling

docs/extending.md, docs/index.md, narwhals/stable/v1/__init__.py, narwhals/translate.py
- Closes #1629
Should I also change the `https://narwhals-dev...` links in CONTRIBUTING.md and README.md ... ??
=> docs: Use relative paths

narwhals/_pandas_like/group_by.py
=> perf: avoid merge in pandas groupby

narwhals/_arrow/expr.py, narwhals/_arrow/namespace.py, narwhals/_arrow/selectors.py, narwhals/_dask/expr.py, narwhals/_dask/namespace.py, narwhals/_expression_parsing.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/group_by.py, narwhals/_pandas_like/namespace.py, narwhals/_pandas_like/selectors.py, narwhals/_pandas_like/series.py, narwhals/_pandas_like/utils.py, narwhals/_spark_like/expr.py, narwhals/_spark_like/namespace.py, narwhals/utils.py, tests/group_by_test.py
=> feat: support std and var with ddof !=1 in pandas-like group by

narwhals/_pandas_like/dataframe.py, narwhals/_polars/dataframe.py, narwhals/dataframe.py, tests/frame/pivot_test.py
=> docs: Note that `maintains_order` has no effect (but keep around for backwards-compatibility)

.github/workflows/check_tpch_queries.yml, .github/workflows/extremes.yml, .github/workflows/pytest.yml, CONTRIBUTING.md, pyproject.toml
=> ci: split `dev` from `extra`

narwhals/_arrow/dataframe.py, narwhals/_arrow/namespace.py, narwhals/_dask/dataframe.py, narwhals/_dask/namespace.py, narwhals/_duckdb/dataframe.py, narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/namespace.py, narwhals/_spark_like/dataframe.py, tests/dtypes_test.py, tests/frame/concat_test.py
=> chore: use `__narwhals_namespace__` more

.github/workflows/publish_to_pypi.yml
- Related issue #1647 
- Closes #1647 
This PR just improves the [publish_to_pypi.yml](https://github.com/narwhals-dev/narwhals/blob/main/.github/workflows/publish_to_pypi.yml) to use the environment variables.
=> ci: improve publish ci to use env vars

narwhals/series.py
=> docs: add return type descriptions to Series `arg_true`, `cast`, `clip`, `count`

narwhals/expr.py, narwhals/series.py, tests/expr_and_series/str/contains_test.py
- Closes #1669 
Adds test for `nw.Expr.str.contains` and `nw.Series.str.contains` with `literal=True`.
=> test: add test for `nw.Expr|Series.str.contains` with `literal=True`

narwhals/series.py
=> docs: add return type descriptions for `cum_count`,  `cum_max`,  `cum_min`,  `cum_prod`, `cum_sum` in Series

narwhals/_arrow/dataframe.py, narwhals/_dask/dataframe.py, narwhals/_pandas_like/dataframe.py, narwhals/dataframe.py
In general, it's probably good if we simplify the implementation of `CompliantFrame`s by doing these kinds of operations at the Narwhals level
If we want to encourage people to extend Narwhals, it'll be easier if they just have to worry about `subset: list[str] | None` rather than `subset: str | list[str] | None`
=> chore: flatten `subset` in `unique` one level up

docs/how_it_works.md, narwhals/_arrow/namespace.py, narwhals/_arrow/series.py, narwhals/_dask/namespace.py, narwhals/_pandas_like/namespace.py, narwhals/_pandas_like/series.py, narwhals/_polars/namespace.py, narwhals/expr.py, narwhals/series.py, narwhals/stable/v1/__init__.py, tests/expr_and_series/is_between_test.py
=> feat: expressify `lower_bound` and `upper_bound` in `is_between`

docs/pandas_like_concepts/boolean.md, docs/pandas_like_concepts/column_names.md, docs/pandas_like_concepts/pandas_index.md, docs/pandas_like_concepts/user_warning.md
- Closes #386 
It seems that it was already mostly used except for the pandas concepts section
=> docs: use `IntoDataFrameT`/`IntoFrameT` in docs

narwhals/_dask/expr.py, narwhals/_dask/utils.py, tests/frame/select_test.py, tests/utils.py
closes #1685 
We may need to update the PySpark `returns_scalar` bits based on this refactor
=> fix: Dask was raising for scalar vs Series binary operations

narwhals/_pandas_like/group_by.py, narwhals/_pandas_like/utils.py, tests/conftest.py, tests/expr_and_series/arithmetic_test.py, tests/expr_and_series/cast_test.py, tests/expr_and_series/convert_time_zone_test.py, tests/expr_and_series/dt/datetime_attributes_test.py, tests/expr_and_series/dt/timestamp_test.py, tests/expr_and_series/is_finite_test.py, tests/expr_and_series/replace_time_zone_test.py, tests/expr_and_series/str/to_uppercase_to_lowercase_test.py, tests/frame/to_numpy_test.py, tests/frame/to_pandas_test.py, tests/group_by_test.py, tests/series_only/to_numpy_test.py, tests/series_only/to_pandas_test.py
- Semi-related PR #1625 
Narwhals failed to preserve pyarrow backed datatypes with Modin-native backed DataFrames. This issue was first noticed in the aforementioned PR and subsequent MRE
```python
>>> import modin.pandas as mpd
>>> s = mpd.Series([1.0, None]).convert_dtypes(dtype_backend='pyarrow')
>>> s
0       1
1    <NA>
dtype: int64[pyarrow]
>>> import narwhals as nw
>>> ns = nw.from_native(s, series_only=True)
>>> ns.cast(nw.Float64).to_native() # loses pyarrow backend info
0    1.0
1    NaN
dtype: float64
```
With this PR, we appropriately preserve the dtype back-end
```python
>>> import modin.pandas as mpd
>>> s = mpd.Series([1.0, None]).convert_dtypes(dtype_backend='pyarrow')
>>> s
0       1
1    <NA>
dtype: int64[pyarrow]
>>> import narwhals as nw
>>> ns = nw.from_native(s, …
```
=> enh modin dtype interoperability

CONTRIBUTING.md, tests/expr_and_series/sample_test.py, tests/expr_and_series/str/to_datetime_test.py, tests/group_by_test.py, tests/read_scan_test.py, tests/spark_like_test.py, tests/tpch_q1_test.py, tests/utils.py
i've removed several `collect`s from tests, so it can happen in `assert_data_equal` and there the environment variable can determine the engine
=> test: allow to run tests for Polars[gpu]

narwhals/_spark_like/utils.py
I guess it was not picked up in the CI because `numpy` version is > 2.0.
Should we have an extra test session with `numpy<2.0` and pyspark?
=> fix: always pass Column to pandas.spark.functions

docs/pandas_like_concepts/null_handling.md
- Iterates on https://github.com/narwhals-dev/narwhals/pull/1624
Adds reference to the `is_nan` specificity in the null handling page.
=> docs: update null handling page with `is_nan` reference

narwhals/_arrow/series.py, narwhals/_pandas_like/utils.py, tests/expr_and_series/reduction_test.py
- Related issue #1711 
- Closes #1711 
When performing a scalar reduction on an empty DataFrame, Polars, pandas, and PyArrow generated disparate result sets with default options. For example, when computing the sum of an empty column (via Narwhals)
- Polars returns a value of 0
- pandas raises a ValueError (on reconstruction of the Series, computationally it also produces 0 as the scalar)
- PyArrow returns null (default scalarreduction options requires at least 1 observed value to produce observed result)
pandas & PyArrow backends now produce output that is consistent with Polars.
Furthermore, there is a difference in the result set when using `.select` vs `.with_columns` where the former may return a value even if the the input was empty whereas the latter will return an empty DataFrame …
=> fix: scalar reductions on empty inputs

narwhals/dataframe.py, narwhals/stable/v1/__init__.py
- Related issue https://github.com/narwhals-dev/narwhals/pull/1466#pullrequestreview-2470894106
Runs `nw.LazyFrame` docstrings examples on Polars and Dask only.
=> docs: let `nw.LazyFrame` docstrings examples run on Polars and Dask only

narwhals/_pandas_like/utils.py, tests/expr_and_series/is_nan_test.py
=> fix: Catch cuDF warning for concat with empty elements, and ComputeError for non-float is_nan

narwhals/_arrow/series.py, narwhals/_arrow/utils.py, narwhals/_dask/expr.py, narwhals/_pandas_like/series.py, narwhals/expr.py, narwhals/series.py, tests/expr_and_series/clip_test.py
=> feat: Expressify `clip` arguments

narwhals/_arrow/dataframe.py, narwhals/_arrow/series.py, narwhals/_dask/dataframe.py, narwhals/_duckdb/dataframe.py, narwhals/_ibis/dataframe.py, narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/series.py, narwhals/_polars/dataframe.py, narwhals/_polars/series.py, narwhals/_spark_like/dataframe.py, narwhals/dependencies.py, narwhals/translate.py, narwhals/utils.py, pyproject.toml, tests/expr_and_series/clip_test.py
=> feat: validate library minimum version in compliant objects

narwhals/_dask/utils.py, narwhals/_pandas_like/utils.py, narwhals/expr.py, narwhals/stable/v1/__init__.py, narwhals/utils.py, pyproject.toml, tests/expr_and_series/arithmetic_test.py, tests/expr_and_series/binary_test.py, tests/expr_and_series/lit_test.py, tests/expr_and_series/operators_test.py, tests/frame/select_test.py, tests/series_only/cast_test.py, tests/tpch_q1_test.py
=> fix: nw.lit(date, dtype=nw.Date), loosen Dask minimum back to 2024.8

narwhals/_dask/expr.py, narwhals/_expression_parsing.py, narwhals/_spark_like/expr.py, pyproject.toml
I saw this code repeated multiple times, I think we can put it in a function :)
=> chore: refactor root_names and output_names tracking

narwhals/expr.py, narwhals/stable/v1/__init__.py
- Closes #1000  and closes #1500 
Pretty sure something is still missing somewhere but arguably this PR closes the two linked issues
=> docs: `Expr` method' docstrings

tests/expr_and_series/replace_time_zone_test.py
…e_zone_none`
- Related issue #1745 
- Closes #1745
=> test: remove `cudf` from `tests/expr_and_series/replace_time_zone_test.py::test_replace_time_zone_none[cudf]`

pyproject.toml, tests/expr_and_series/rolling_mean_test.py, tests/expr_and_series/rolling_sum_test.py, tests/expr_and_series/rolling_var_test.py
=> fix: fix license classifier

narwhals/_duckdb/expr.py, narwhals/_duckdb/namespace.py, narwhals/_duckdb/utils.py, tests/expr_and_series/when_test.py, tpch/execute.py
=> feat: implement when/then/otherwise for DuckDB

narwhals/_arrow/expr.py, narwhals/_arrow/series.py, narwhals/_dask/expr.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/series.py, narwhals/_spark_like/expr.py, narwhals/expr.py, narwhals/series.py, tests/expr_and_series/is_between_test.py, tests/spark_like_test.py
=> docs: fix `is_between` type hint in signature

narwhals/_duckdb/expr.py, tests/expr_and_series/n_unique_test.py, tests/expr_and_series/unary_test.py, tests/group_by_test.py, tpch/execute.py
=> feat: implement `n_unique` for DuckDB

narwhals/_duckdb/dataframe.py, tests/frame/join_test.py, tpch/execute.py
=> feat: semi-join for duckdb

narwhals/_duckdb/dataframe.py, tests/frame/join_test.py, tests/frame/sort_test.py
=> fix: duckdb join was failing if column names contained spaces

narwhals/_duckdb/expr.py, tests/expr_and_series/str/replace_test.py
- Related issue #1728 
Turns out all duckdb regex functions support a limited set of regex options that are documented here:
https://duckdb.org/docs/sql/functions/regular_expressions.html but not on their text functions page here https://duckdb.org/docs/sql/functions/char.html#regexp_replacestring-pattern-replacement.
Adding the global `'g'` option prevents the regexp from returning after the first match :)
=> feat: duckdb replace_all with regex

docs/api-reference/dataframe.md, docs/api-reference/series.md, narwhals/_arrow/dataframe.py, narwhals/_arrow/series.py, narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/series.py, narwhals/_polars/dataframe.py, narwhals/_polars/series.py, narwhals/dataframe.py, narwhals/series.py, tests/frame/to_polars_test.py, tests/series_only/to_polars_test.py, utils/check_api_reference.py
=> feat: add `DataFrame` and `Series` `to_polars`

narwhals/expr.py, narwhals/stable/v1/__init__.py, narwhals/utils.py, tests/expr_and_series/gather_every_test.py, tests/expr_and_series/head_test.py, tests/expr_and_series/sample_test.py, tests/expr_and_series/sort_test.py, tests/expr_and_series/tail_test.py
One step closer to `narwhals.stable.v2`
These are some operations which we won't be able to support in the lazy layer at all, and I think it would be confusing to have some Expr methods which aren't available at all for lazyframes (which would be different to `Expr.unique`, which could be supported if followed by an aggregation, or `Expr.cum_sum`, which could be supported if `order_by` is passed)
Further, I just don't think any of these expressions are very useful...people call head/tail/sort/sample on dataframes, not typically on individual expressions..
For the cases where people need them, they can use DataFrame or Series operations
=> feat: deprecate Expr.head, Expr.tail, Expr.sort, Expr.gather_every, Expr.sample (but keep them in stable.v1)

narwhals/_arrow/dataframe.py, narwhals/_arrow/utils.py, narwhals/_dask/dataframe.py, narwhals/_duckdb/dataframe.py, narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/utils.py, narwhals/_spark_like/dataframe.py, tests/frame/filter_test.py
- Closes #1786 
For lazy backends:
- duckdb raises: `duckdb.duckdb.BinderException`
- pyspark raises: `pyspark.errors.exceptions.captured.AnalysisException: [INVALID_WHERE_CONDITION]`
- dask raises `pd.errros.IndexingError`
at compute time. So polars is the only one allowing filtering with a scalar boolean
=> fix: raise on shape mismatch in filter

.github/workflows/downstream_tests.yml, utils/generate_backend_completeness.py
=> ci: downstream test for formulaic

narwhals/_arrow/expr.py, narwhals/_arrow/expr_name.py, narwhals/_arrow/group_by.py, narwhals/_dask/expr.py, narwhals/_dask/expr_name.py, narwhals/_dask/group_by.py, narwhals/_duckdb/group_by.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/expr_name.py, narwhals/_pandas_like/group_by.py, narwhals/_spark_like/group_by.py, narwhals/exceptions.py, tests/expr_and_series/name/keep_test.py, tests/expr_and_series/name/map_test.py, tests/expr_and_series/name/prefix_test.py, tests/expr_and_series/name/to_lowercase_test.py, tests/expr_and_series/name/to_uppercase_test.py, tests/group_by_test.py
I propose to add a error for the (very) common error message about anonlymous expressions.
Ideally I would like to move this a level up (since we raise it for every backend) but I get all sorts of mypy error if I do that. e.g. `mypy` thinks `root_names` could still be `None`
=> feat: add `AnonymousExprError`

narwhals/_duckdb/expr.py, narwhals/_duckdb/expr_name.py, narwhals/_spark_like/expr.py, narwhals/_spark_like/expr_name.py, tests/conftest.py, tests/expr_and_series/name/keep_test.py, tests/expr_and_series/name/map_test.py, tests/expr_and_series/name/prefix_test.py, tests/expr_and_series/name/suffix_test.py, tests/expr_and_series/name/to_lowercase_test.py, tests/expr_and_series/name/to_uppercase_test.py
=> feat: pyspark and duckdb `Expr.name` namespace

narwhals/_spark_like/utils.py, narwhals/utils.py
=> chore: refactor `isinstance_or_issubclass` to allow tuples

narwhals/_spark_like/group_by.py, tests/group_by_test.py
=> feat: pyspark group by `n_unique` and no aggregation

narwhals/_spark_like/expr.py, tests/expr_and_series/over_test.py
=> feat: add `.over` method for `SparkLikeExpr`

narwhals/_spark_like/expr.py, narwhals/_spark_like/expr_dt.py, tests/expr_and_series/dt/datetime_attributes_test.py
- Related issue #1714 
Added the following functions:
- `date`
- `year`
- `month`
- `day`
- `hour`
- `minute`
- `second`
- `millisecond`
- `microsecond`
- `nanosecond`
- `ordinal_day`
- `weekday`
=> feat: add `Expr.dt` methods to `PySpark`

narwhals/_arrow/namespace.py, narwhals/_dask/namespace.py, narwhals/_duckdb/namespace.py, narwhals/_pandas_like/namespace.py, narwhals/_pandas_like/utils.py, tests/expr_and_series/when_test.py
=> fix: when/then/otherwise output name was not consistent across backends

narwhals/expr.py, narwhals/stable/v1/__init__.py, tests/expr_and_series/arg_true_test.py
Similar to #1791 
This one both changes length and is order-dependent. Plus, it's currently only being tested for eager backends anyway. Best to clean it up
The only usage we have in the wild of it is Formulaic where they do `Series.arg_true`, where I can indeed see it being useful
=> feat: Deprecate Expr.arg_true (but keep Series.arg_true, and keep both available in stable.v1)

narwhals/_pandas_like/namespace.py, narwhals/_pandas_like/series.py, narwhals/_pandas_like/series_list.py
=> chore: simplify internal renaming in _pandas_like/series.py

narwhals/_arrow/dataframe.py, narwhals/_arrow/utils.py, narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/utils.py, narwhals/dataframe.py, narwhals/functions.py, tests/expr_and_series/when_test.py, tests/frame/filter_test.py
=> chore: validate expressions shape at narwhals/expr.py level

narwhals/_arrow/selectors.py, narwhals/_dask/selectors.py, narwhals/_pandas_like/selectors.py, narwhals/selectors.py, tests/selectors_test.py
=> fix: raise on selectors addition

narwhals/_duckdb/utils.py, tests/expr_and_series/cast_test.py
=> patch: fix duckdb `narwhals_to_native_dtype` for `Int32` and `UInt32`

narwhals/_arrow/expr.py, narwhals/_arrow/series.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/series.py, narwhals/_polars/expr.py, narwhals/_polars/series.py, narwhals/expr.py, narwhals/series.py, narwhals/stable/v1/__init__.py, narwhals/utils.py, tests/expr_and_series/ewm_test.py, tests/expr_and_series/rolling_mean_test.py, tests/expr_and_series/rolling_std_test.py, tests/expr_and_series/rolling_sum_test.py, tests/expr_and_series/rolling_var_test.py
=> fix: rename ewm and rolling `min_periods` to `min_samples` for polars 1.21 compatibility

.github/workflows/mkdocs.yml
I was wonder how this happened - _how pyspark and dask disappeared_ - and I assumed it's due to the fact that with imports on top of the file, we cannot run the modules to inspect classes safely.
We might want to use uv and caching this as well - pyspark and dask are a bit heavier
=> docs: fix api completness generation in CI

narwhals/_polars/namespace.py, tests/selectors_test.py
=> fix: `nw.selectors.by_dtype(nw.Datetime)` was excluding tz-aware for Polars

narwhals/_arrow/dataframe.py, narwhals/_dask/dataframe.py, narwhals/_dask/utils.py, narwhals/_duckdb/dataframe.py, narwhals/_duckdb/utils.py, narwhals/_expression_parsing.py, narwhals/_pandas_like/dataframe.py, narwhals/_spark_like/dataframe.py, narwhals/_spark_like/utils.py
Currently if we do:
```py
@nw.narwhalify
def func(df):
return df.with_columns(df=nw.col("a")+1)
```
with any backend except polars, we get an error:
> TypeError: evaluate_into_exprs() got multiple values for argument 'df'
This PR fixes this issue
=> fix: allow any name in expression parsing

.github/workflows/downstream_tests.yml, narwhals/_dask/group_by.py, narwhals/_duckdb/expr.py, narwhals/_duckdb/expr_name.py, narwhals/_duckdb/namespace.py, narwhals/_duckdb/selectors.py, narwhals/_duckdb/utils.py, narwhals/_pandas_like/series.py, narwhals/_spark_like/expr.py, narwhals/_spark_like/expr_name.py, narwhals/_spark_like/expr_str.py, narwhals/_spark_like/group_by.py, narwhals/_spark_like/namespace.py, narwhals/_spark_like/selectors.py, narwhals/_spark_like/utils.py, narwhals/typing.py, tests/conftest.py, tests/expr_and_series/operators_test.py
=> fix: address `&` / `|` operator errors for PySpark / chore: use F.lit in maybe_evaluate for pyspark, like we do for duckdb

narwhals/_spark_like/dataframe.py, narwhals/_spark_like/expr.py, narwhals/_spark_like/group_by.py, narwhals/_spark_like/utils.py, pyproject.toml, tests/expr_and_series/lit_test.py, tests/expr_and_series/reduction_test.py, tests/stable_api_test.py
=> fix: support various reductions in pyspark

narwhals/_duckdb/dataframe.py, narwhals/_duckdb/expr.py, narwhals/_duckdb/expr_dt.py, narwhals/_duckdb/expr_list.py, narwhals/_duckdb/expr_name.py, narwhals/_duckdb/expr_str.py, narwhals/_duckdb/namespace.py, narwhals/_duckdb/selectors.py, narwhals/_duckdb/utils.py, narwhals/utils.py, tests/expr_and_series/lit_test.py, tests/expr_and_series/sum_horizontal_test.py, tpch/execute.py
Very similar to the recent PySpark PR #1870
=> feat: support more scalar operations for duckdb, Increase width for ipython

narwhals/_duckdb/expr.py, narwhals/_duckdb/expr_name.py, narwhals/_duckdb/namespace.py, narwhals/_duckdb/selectors.py, narwhals/_spark_like/expr.py, narwhals/_spark_like/expr_name.py, narwhals/_spark_like/namespace.py, narwhals/_spark_like/selectors.py
=> chore: remove unused `_depth` from `DuckDBExpr` and `SparkLikeExpr`

narwhals/_spark_like/dataframe.py, narwhals/_spark_like/expr.py, narwhals/_spark_like/expr_dt.py, narwhals/_spark_like/expr_name.py, narwhals/_spark_like/expr_str.py, narwhals/_spark_like/namespace.py, narwhals/_spark_like/selectors.py, narwhals/_spark_like/utils.py
=> feat: move robust literal handling for PySpark

.github/workflows/mkdocs.yml, narwhals/_spark_like/dataframe.py, narwhals/_spark_like/expr.py, narwhals/_spark_like/expr_dt.py, narwhals/_spark_like/expr_name.py, narwhals/_spark_like/expr_str.py, narwhals/_spark_like/group_by.py, narwhals/_spark_like/namespace.py, narwhals/_spark_like/selectors.py, narwhals/_spark_like/utils.py, narwhals/dependencies.py, narwhals/translate.py, narwhals/utils.py, pyproject.toml, tests/conftest.py, tests/expr_and_series/is_finite_test.py
At the moment there's quite a few bugs failing for SQLFrame. But it's a start
Plus, it means:
- we can build the API completeness pages without needing PySpark installed
- we'll later have a way to run PySpark tests via SQLFrame in newer Python versions
- it may open the door for #1419 
=> feat: start (silently) adding support for SQLFrame

narwhals/_spark_like/dataframe.py, narwhals/_spark_like/expr.py, narwhals/_spark_like/expr_list.py, narwhals/_spark_like/utils.py, tests/expr_and_series/list/len_test.py, tests/frame/explode_test.py, tests/utils.py
=> feat: spark like `.list` namespace and lazyframe `.explode`

narwhals/_duckdb/group_by.py
duckdb auto-infers the groups in `aggregate`, so can remove this string-hacking (in general, the less manual string construction we do, better, though in some places it's inevitable)
=> chore: simplify duckdb group-by

narwhals/dataframe.py, narwhals/stable/v1/__init__.py, tests/frame/lazy_test.py
=> feat: enable `ModuleType` and `str` for backend in `.lazy()` method

narwhals/expr.py
Copilot helped me to shorten the docstrings
I then went through and fixup out the outputs, and sometimes fixed up the examples too
Aside from reducing size, I think like this they're more to-the-point
We could then have some follow-up PRs to diversity the examples a bit to showcase different libraries
=> docs: shorten docstring examples in narwhals/expr.py

narwhals/dataframe.py
Resolves an issue mentioned in (https://discord.com/channels/1235257048170762310/1237430779584446546/1335943538352848928)
**Every site** that `LazyFrame` was specialised (`LazyFrame[<some>]`) it created a warning for `pyright`/`Pylance`.
The simplest explanation is you need to use a different `TypeVar` when subclassing to preserve the generic behavior.
It doesn't matter that `_FrameT` and `FrameT` are functionally equivalent.
Also `_FrameT` is never exposed to the user, or anywhere AFAICT - so I just prefixed the existing name.
**Before** / **After**
=> fix(typing): Ensure `LazyFrame` has a unique `TypeVar`

narwhals/utils.py, tests/expr_and_series/all_horizontal_test.py
Fixes #1897
- Closes #1897
- New tests would fail on `main`, but I'm getting a different error than when I raised (#1897)
- Original issue was the expression could only be used once, hence the repeated statements
=> fix: Always collect `Iterator[IntoExpr]` in `utils.flatten`

narwhals/translate.py
- Related issue #1928
Resolves 4x `pyright` warnings.
I was planning to look at fixing (#1928) but these needed to be addressed first
=> fix(typing): Use correct `TypeVar`/`Union` pairs in `from_native`

narwhals/translate.py
Mentioned in https://github.com/narwhals-dev/narwhals/pull/1935#issuecomment-2634298106
Resolves a similar issue as (#1935)
<details><summary>Warning (very long message)</summary>
<p>
> Overloaded implementation is not consistent with signature of overload 1
>   Type "(narwhals_object: DataFrame[IntoFrameT@to_native] | LazyFrame[IntoFrameT@to_native] | Series[IntoSeriesT@to_native], *, strict: bool | None = None, pass_through: bool | None = None) -> (IntoFrameT@to_native | Any)" is not assignable to type "(narwhals_object: DataFrame[IntoDataFrameT@to_native], *, pass_through: Literal[False] = ...) -> IntoDataFrameT@to_native"
>     Parameter 1: type "DataFrame[IntoDataFrameT@to_native]" is incompatible with type "DataFrame[IntoFrameT@to_native] | LazyFrame[IntoFrameT@to_native] | …
=> fix(typing): Use `IntoDataFrameT` in `to_native`

narwhals/dataframe.py
As discussed in the last call
This took some effort, but I think it's worth keeping package size under control. Seeing the docstrings like this, i also think they generally look better, my fault for having suggested such long docstrings in the first place
=> docs: Make DataFrame and LazyFrame docstrings shorter and more concise

narwhals/_arrow/dataframe.py, tests/frame/is_duplicated_test.py
=> fix: raise NotImplementedError for DataFramte.is_duplicated for PyArrow when there is more than one column

.github/workflows/downstream_tests.yml, narwhals/_ibis/dataframe.py
Plotly moved the tests outside the library folder.
Noticed the CI failure in #1955
=> ci: fix plotly tests location

narwhals/series.py
Resolves a few of these messages:
> Argument of type "str" cannot be assigned to parameter "level" of type "Literal['full', 'lazy', 'interchange']" in function "__init__"
The same is already in `BaseFrame`
https://github.com/narwhals-dev/narwhals/blob/c5748be5770a42d0915b124cde272a4d69faf512/narwhals/dataframe.py#L63-L65
aaaand in `DataFrame`:
https://github.com/narwhals-dev/narwhals/blob/c5748be5770a42d0915b124cde272a4d69faf512/narwhals/dataframe.py#L440-L446
=> fix(typing): add missing `Series._level` annotation

CONTRIBUTING.md
- Closes #1943
All other changes are unrelated via `markdownlint`
=> docs: add docstring guidelines to CONTRIBUTING.md

narwhals/dataframe.py, narwhals/stable/v1/__init__.py, tests/frame/get_column_test.py, tests/frame/getitem_test.py
I am so sorry @MarcoGorelli , I was a bit to quick to press "Ready for Review" 😭
This is a follow up of #1958
=> fix: missing `__getitem__` type fixes

narwhals/_pandas_like/series.py, narwhals/_pandas_like/utils.py, narwhals/functions.py, narwhals/schema.py, narwhals/stable/v1/__init__.py, narwhals/typing.py, tests/frame/schema_test.py
Will close #1912
- Closes #1912
- Started with porting `nw.functions._from_dict_impl`
- Extended `Schema` w/ `._version`
=> feat: add `Schema.to_(arrow|pandas|polars)`

narwhals/dataframe.py
Comment was missing the target
Removes the last `pyright` warning in `dataframe.py`
=> chore(typing): fix `_from_compliant_dataframe` type ignore

narwhals/functions.py, narwhals/series.py
Mentioned https://github.com/narwhals-dev/narwhals/pull/1969#issuecomment-2645867682
- Ignored invalid `pa.chunked_array` stubs
- Avoid reassigning `dtype`
- Add inline annotation to avoid inferrence of `Iterator[str | None]`
=> chore(typing): fix remaining `functions`, `series` warnings

narwhals/series.py
- Towards #1942 
- Is this an overkill? It almost cuts in half the file lines
- Reason to always go to `to_native()` is mainly ArrowSeries repr not being great when ELLIPSIS are required to pass the doctest
=> RFC, chore: shrink `series` module docstrings

narwhals/_arrow/dataframe.py, narwhals/_arrow/series.py, narwhals/_arrow/utils.py, narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/series.py, narwhals/_pandas_like/utils.py, narwhals/_polars/dataframe.py, narwhals/_polars/series.py, narwhals/dataframe.py, narwhals/dependencies.py, narwhals/functions.py, narwhals/series.py, narwhals/stable/v1/__init__.py, narwhals/typing.py, narwhals/utils.py
Closes #1972
- Closes #1972
Resolves warnings that look like this:
```py
narwhals/_pandas_like/dataframe.py:858: error: Missing type parameters for generic type "ndarray"  [type-arg]
```
On `main`, this accounts for **25** warnings:
=> chore(typing): add `np.ndarray` aliases

narwhals/_polars/dataframe.py, narwhals/_polars/series.py, narwhals/_polars/utils.py, narwhals/exceptions.py, tests/expr_and_series/is_nan_test.py, tests/expr_and_series/median_test.py, tests/expr_and_series/replace_strict_test.py, tests/frame/drop_test.py, tests/frame/explode_test.py, tests/frame/filter_test.py, tests/frame/pivot_test.py, tests/frame/select_test.py
Unify exceptions, and re-raise Polars ones as Narwhals ones
This doesn't unify _everything_...but I think it's a nice step forwards, and should be ~~totally backwards-compatible~~ mostly backwards-compatible (unless anyone catches Polars exceptions specifically in tests)
Towards #1373
=> feat: catch Polars exceptions, unify exception raising more

narwhals/_expression_parsing.py, narwhals/dataframe.py, narwhals/expr.py, narwhals/expr_cat.py, narwhals/expr_dt.py, narwhals/expr_list.py, narwhals/expr_name.py, narwhals/expr_str.py, narwhals/functions.py, narwhals/group_by.py, narwhals/selectors.py, narwhals/stable/v1/__init__.py, narwhals/utils.py, tests/expr_and_series/order_dependent_lazy_test.py, tests/expr_and_series/unique_test.py, utils/check_api_reference.py
First step towards #1848 
No noticeable difference in perf when running this locally
Theoretically, I'd expect it to make things not-worse, as we're not only looping through `args` once to construct `ExprMetadata`, as opposed to 4 times
But the main reason to do this is to aim towards #1848 , after which, implementations at the compliant level should become much simpler and easier to reason about
=> chore: Expr metadata refactor

narwhals/_arrow/dataframe.py, narwhals/_dask/dataframe.py, narwhals/_dask/utils.py, narwhals/_duckdb/dataframe.py, narwhals/_duckdb/utils.py, narwhals/_expression_parsing.py, narwhals/_ibis/dataframe.py, narwhals/_pandas_like/dataframe.py, narwhals/_polars/dataframe.py, narwhals/_spark_like/dataframe.py, narwhals/_spark_like/utils.py, narwhals/dataframe.py, narwhals/expr.py, narwhals/group_by.py, narwhals/typing.py
I'm hoping to get to the point where we don't even need `ExprKind`, or any logic to do broadcasting, at the compliant level
I think we're not that far off
We may need to introduce something like `CompliantNamespace.broadcast_exprs` and then determine at the Narwhals level when to call it
=> chore: determine whether to use compliant_frame.aggregate at narwhals level

narwhals/_arrow/dataframe.py, narwhals/_arrow/series.py, narwhals/_duckdb/dataframe.py, narwhals/utils.py
```
shape: (9, 7)
┌───────────────────────────────┬──────┬────────┬───────────────────────────────┬──────┬───────────────┬──────────┐
│ file                          ┆ line ┆ column ┆ message                       ┆ hint ┆ code          ┆ severity │
│ ---                           ┆ ---  ┆ ---    ┆ ---                           ┆ ---  ┆ ---           ┆ ---      │
│ str                           ┆ i64  ┆ i64    ┆ str                           ┆ str  ┆ str           ┆ str      │
╞═══════════════════════════════╪══════╪════════╪═══════════════════════════════╪══════╪═══════════════╪══════════╡
│ narwhals/utils.py             ┆ 192  ┆ -1     ┆ Unused "type: ignore" comment ┆ null ┆ unused-ignore ┆ error    │
│ narwhals/utils.py             ┆ 204  ┆ -1     ┆ Unused "type: ignore" comment ┆ …
```
=> chore(typing): remove unused ignores

narwhals/_duckdb/utils.py, narwhals/utils.py
- Related issue #1961
- I've typed only up to 3-tuple, based on existing usage of the function
- Noticed this was needed to resolve a lot of issues in `_arrow.utils`
https://github.com/narwhals-dev/narwhals/blob/fd8ccac0c66af1a459c8a1ab0954018f91eb172a/narwhals/_pandas_like/utils.py#L653
=> chore(typing): add overloads to `isinstance_or_issubclass`

narwhals/translate.py, narwhals/utils.py, tests/frame/schema_test.py, tests/translate/from_native_test.py
In the `narwhals.from_native` function, `sqlframe` had to be explicitly checked before the `is_compliant*` checks due to false positives from `hasattr(sqlframe_df, "__narwhals_dataframe__")`.
1. Instead we can use `inspect.getattr_static` (thanks for the suggestion @dangotbanned) to avoid this addition and we can move the `sqlframe` specific code to be in line with the other backends.
2. I also added a test to ensure `sqlframe` cases are handled properly.
3. I removed a test that will break in the future, this test was passing due to a side effect caused by `hasattr` on a `pandas` DataFrame enabling the use of nonhashable values as column names (raised as an issue in pandas https://github.com/pandas-dev/pandas/issues/60925)
=> fix: sqlframe false positives in compliance checks

narwhals/utils.py
In #2011 @dangotbanned pointed out that `try/except` is expensive in Python<3.11 and opted to use a sentinel to avoid those statements.
This codepath is triggered 3 times for every call to `from_native` so it will be regularly hit multiple times by end users so this could be worth doing.
=> perf: avoid try/except in _hasattr_static

narwhals/utils.py
=> chore(typing): resolve time unit/zone `set` invariance

pyproject.toml
- Related issue #2017
@FBruzzesi : I'm not sure if you meant (in the issue) that we should detect automatically the dependencies that we want to skip...? In case we only need to skip ibis, this does it. 
Per the link you shared about `norecursedirs` : "Default patterns are '*.egg', '.*', '_darcs', 'build', 'CVS', 'dist', 'node_modules', 'venv', '{arch}'. Setting a `norecursedirs` replaces the default."
=> tests: Allow to run pytest narwhals --doctest-modules without ibis

narwhals/_duckdb/expr.py, tests/expr_and_series/unary_test.py
duckdb natively returns population skewness, while polars and all other return sample skewness. This PR add the correction factor to match the outputs
Discovered while running sqlframe with duckdb backend
=> fix: adjust duckdb population skewness by correction factor to get sample skewness

narwhals/functions.py, narwhals/stable/v1/__init__.py
Current `dict[str, Any]` will reject `Mapping[str, Sequence[Any]]`.
I noticed this in `altair`, where I needed to cast to `dict[str, Any]`:
- https://github.com/vega/altair/blob/ddda22c50f7265728dcec26afec02d6d0dbda189/altair/datasets/_reader.py#L362-L366
- https://github.com/vega/altair/blob/ddda22c50f7265728dcec26afec02d6d0dbda189/altair/datasets/_cache.py#L182
For reference, [`polars.from_dict`](https://docs.pola.rs/api/python/stable/reference/api/polars.from_dict.html) uses `Mapping` but with some constraints on the value type
=> chore(typing): relax `from_dict` to use `Mapping`

narwhals/functions.py, narwhals/stable/v1/__init__.py
- Related PR #2022
- Similar to #2022
- There's more variation between backends here, so `pandas` and `pyarrow` still convert `Sequence` -> `list` to be safe
- https://docs.pola.rs/api/python/stable/reference/api/polars.from_numpy.html
- https://github.com/zen-xu/pyarrow-stubs/blob/d97063876720e6a5edda7eb15f4efe07c31b8296/pyarrow-stubs/__lib_pxi/table.pyi#L551-L558
- https://github.com/pandas-dev/pandas/blob/6bcd30397d67c3887288c7a82c2c235ce8bc3c7f/pandas/_typing.py#L155
=> chore(typing): relax `from_numpy` to use `Mapping`, `Sequence`

narwhals/_spark_like/utils.py, tests/expr_and_series/cast_test.py
There are multiple reason for this PR to happen 😁
- Eventually I would like to support `Schema.to_pyspark`
- For some integration it might be useful to have: 
- `nw.struct` emulating [`pl.struct`](https://docs.pola.rs/api/python/dev/reference/expressions/api/polars.struct.html)
- `.struct.unnest()` and/or `Frame.unnest`
- Closes #1743
I am having a hard time testing this 🤔
=> feat: support casting to and from spark-like structs

narwhals/functions.py, narwhals/stable/v1/__init__.py
- #1942
- #1912
Mentioned in https://github.com/narwhals-dev/narwhals/pull/2023#issuecomment-2661401420.
I made an attempt at (https://github.com/narwhals-dev/narwhals/pull/2024#discussion_r1957339080) and (https://github.com/narwhals-dev/narwhals/pull/2024#discussion_r1957339709) - but ended up at almost the same LOC 🤦‍♂️
=> refactor: reuse `Schema.to_<backend>()` in `from_numpy`

narwhals/dtypes.py, tests/dtypes_test.py
We get the `TypeError` for free:
```py
import narwhals as nw
>>> nw.Array(nw.Int64)
TypeError: Array.__init__() missing 1 required positional argument: 'shape'
```
And your IDE can let you know statically:
=> refactor: remove `Array` shape default

narwhals/_arrow/namespace.py, narwhals/_dask/namespace.py, narwhals/_pandas_like/namespace.py
=> perf: Avoid evaluating expr twice in mean_horizontal

.github/workflows/downstream_tests.yml, narwhals/_duckdb/expr.py, narwhals/_spark_like/dataframe.py, tests/frame/collect_test.py
=> fix: PySpark was raising during `collect` when it contained no rows and a void dtype column

narwhals/_arrow/expr.py, narwhals/_dask/expr.py, narwhals/_duckdb/expr.py, narwhals/_pandas_like/expr.py, narwhals/_spark_like/expr.py, narwhals/expr.py
Using `nw.lit` for parsing literals does introduce some unneeded complexity, as we need to create a temporary 1-row series and then broadcast it. For such a common operation (e.g. `1 - nw.col('a')`) we can keep it simpler by just keeping the `1` as a Python scalar
=> chore: refactor right-hand-side arithmetic to not use lit

narwhals/_expression_parsing.py
- Will always be the same result on every call to the inner `evaluate_output_names`
- Unsure how frequent it would be called, but noticed in (https://github.com/narwhals-dev/narwhals/pull/2035#discussion_r1959770117)
Unrelated polars nightly failure (https://github.com/narwhals-dev/narwhals/actions/runs/13392572259/job/37403539233?pr=2040)
=> chore(perf): move `combine_evaluate_output_names` check

.github/workflows/check_tpch_queries.yml, .github/workflows/downstream_tests.yml, .github/workflows/downstream_tests_slow.yml, .github/workflows/pytest.yml, .github/workflows/random_ci_pytest.yml, .github/workflows/typing.yml
Very minor PR
The `marimo` tests currently run for every python version in the `hatch` matrix. I guess in the same env since we inject `path = ".venv"` right? 🤔
Adding colors that help when reading the logs 😇
=> chore: add colors in CI and run `marimo` only in selected python version

narwhals/_arrow/utils.py, narwhals/_duckdb/utils.py, narwhals/_pandas_like/utils.py, narwhals/_polars/utils.py, narwhals/_spark_like/utils.py, narwhals/dtypes.py
Mentioned in
- https://github.com/narwhals-dev/narwhals/pull/1991#discussion_r1957328569
- https://github.com/narwhals-dev/narwhals/pull/1807#discussion_r1956331625
- I started with an implementation for `Datetime`, when used in `_polars` only
- Was expecting this to be a more complex task, but realised I could use the same idea as https://github.com/vega/altair/blob/f61a22e4fb0fb0822e7e3fb440b716d93a261474/altair/expr/__init__.py#L23
This gives you a read-only default for:
```py
Datetime.time_unit
```
Which is unaffected by the instance-level version:
```py
dtype = Datetime("ms")
dtype.time_unit
```
I imagined this would also be useful `Duration`:
https://github.com/narwhals-dev/narwhals/blob/43d072b41b8d4098c89b6798da46199e31368513/narwhals/dtypes.py#L527
Originally thought this would …
=> fix(RFC): Use metaclass for safe `DType` attr access

narwhals/_arrow/namespace.py, narwhals/_arrow/selectors.py, narwhals/_dask/namespace.py, narwhals/_dask/selectors.py, narwhals/_duckdb/namespace.py, narwhals/_duckdb/selectors.py, narwhals/_pandas_like/namespace.py, narwhals/_pandas_like/selectors.py, narwhals/_spark_like/namespace.py, narwhals/_spark_like/selectors.py, narwhals/utils.py
- Related issue #1942
There's still a lot more than could be shared between backends.
Thought I'd check in to see if ideas like this are desirable
=> refactor: deduplicate `*.selectors`

narwhals/_arrow/expr.py, narwhals/_arrow/namespace.py, narwhals/_arrow/selectors.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/selectors.py
follow-up to #2057 - there's a lot of `kwargs` we're passing around that we don't need
i'd generally like to refactor that whole mechanism (we'll need it for when we want to support `rolling_mean(n).over(group, order_by=id)`), but for a start we can remove them when they're not needed
=> chore: remove `kwargs` from `selector` function

narwhals/typing.py
- Mentioned in https://discord.com/channels/1235257048170762310/1272835922924273694/1342486928250900570
All implementors of the protocol already define this, meaning `CompliantExpr` can now match `_FullContext`
https://github.com/narwhals-dev/narwhals/blob/4dda548fc36ebcef3bb70e8d4581de1774879060/narwhals/utils.py#L77-L100
=> chore(typing): add `CompliantExpr._version`

narwhals/_dask/expr.py, narwhals/_dask/expr_name.py, narwhals/_dask/group_by.py, narwhals/_dask/namespace.py, narwhals/_dask/selectors.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/namespace.py, narwhals/_pandas_like/selectors.py
I don't like how currently we're muddying the waters between "expressifiable arguments" and "kwargs", which leads us to having to pass `ddof` as an expressifiable argument in `std` and `var`
I'd like to start by separating the concepts, and not passing `ddof` as an expressifiable argument
=> chore: remove more `kwargs` from dask, dont treat `ddof` as expressifiable arg

narwhals/functions.py, narwhals/stable/v1/__init__.py, tests/read_scan_test.py
=> enh: Deprecate `native_namespace` in favour of `backend` in `read_csv`

narwhals/_arrow/expr.py, narwhals/_dask/expr.py, narwhals/_pandas_like/expr.py, narwhals/_polars/expr.py, narwhals/_spark_like/expr.py, narwhals/expr.py, tests/expr_and_series/over_test.py, tests/group_by_test.py
=> fix: disallow non-elementary operations in .over for pandas

narwhals/_arrow/expr.py, narwhals/_arrow/expr_name.py, narwhals/_arrow/group_by.py, narwhals/_arrow/namespace.py, narwhals/_expression_parsing.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/expr_name.py, narwhals/_pandas_like/group_by.py, narwhals/_pandas_like/namespace.py, narwhals/_pandas_like/selectors.py, narwhals/_spark_like/utils.py, narwhals/group_by.py, tests/group_by_test.py
More separation between expressifiable kwargs and call kwargs
This doesn't go all the way (yet) but does reduce passing around kwargs when it's not necessary
=> chore: remove unused kwargs in `_pandas_like` and `_arrow`

.github/workflows/downstream_tests.yml, narwhals/expr.py
=> chore: use Expr._from_callable

narwhals/_arrow/namespace.py, narwhals/_pandas_like/namespace.py
- https://github.com/narwhals-dev/narwhals/pull/2087#discussion_r1968034436
- [`ef85eda` (#2064)](https://github.com/narwhals-dev/narwhals/pull/2064/commits/ef85eda6599d0a0fce261c35416983756fa456e5)
- https://github.com/narwhals-dev/narwhals/actions/runs/13483136123/job/37670892891?pr=2064
This change is a pre-emptive fix for an issue that would appear after annotating `CompliantExpr.__call__(df: <...>)`:
https://github.com/narwhals-dev/narwhals/blob/372f1eb17ff05457b7b8fb9caa1f46da1ae3cd7d/narwhals/typing.py#L119
Hoping to merge this and (#2087) to get the changes out of (#2064).
Should make the review for (#2064) a lot simpler 🙂
=> chore(typing): Fix `(Pandas|Arrow)(When|Then)`

narwhals/typing.py
We could probably do a similar thing for the `Union` aliases.
Still looks the same in VSCode:
=> refactor(typing): Use a forward ref for `IntoCompliantExpr`

narwhals/_spark_like/dataframe.py, tests/frame/unpivot_test.py
- Related issue #2082 : this doesn't fixes it, but adds a test for it.
Adds support to `unpivot` when `index=None` and `on is not None`
=> fix: `pyspark` unpivot with index `None`

narwhals/_expression_parsing.py, narwhals/dataframe.py, narwhals/expr.py, narwhals/expr_cat.py, narwhals/stable/v1/__init__.py, tests/frame/select_test.py
As discussed in some other issues
=> chore: rename changes_length to filtration

narwhals/_arrow/namespace.py, narwhals/_dask/namespace.py, narwhals/_pandas_like/namespace.py, narwhals/_spark_like/utils.py
A full broadcast is inevitable for the `then` value, but for the `otherwise` value we can avoid it
=> perf: avoid full broadcast for otherwise_value in when/then/otherwise

narwhals/_arrow/namespace.py, narwhals/_dask/namespace.py, narwhals/_duckdb/namespace.py, narwhals/_pandas_like/namespace.py, narwhals/_spark_like/namespace.py, narwhals/typing.py, narwhals/utils.py
- Mentioned in (https://github.com/narwhals-dev/narwhals/pull/2058#discussion_r1964137667)
- Originally (https://github.com/narwhals-dev/narwhals/pull/2064/commits/028098e4b5091f73fca2f812830d54f109875777) and (https://github.com/narwhals-dev/narwhals/pull/2064/commits/c597ba7c2b06b1d1db29e9b7f254aa3be47b5d86)
Previously, a new function was created in each of these locations - but it didn't bind any arguments - so there was no benefit to using a `lambda`
=> perf: Avoid redefining `lambda` in `*Namespace.all`

narwhals/functions.py
- Was planning to replace with `nw.typing.FrameT`, but noticed there was no usage
- Also lets us move some imports into `TYPE_CHECKING`
=> chore(typing): remove unused, ignored `TypeVar`

narwhals/stable/v1/__init__.py, narwhals/stable/v1/typing.py, tests/expr_and_series/dt/timestamp_test.py, tests/translate/from_native_test.py
- #1412
- #1930
- https://narwhals-dev.github.io/narwhals/backcompat/#breaking-changes-carried-out-so-far
- Hoping to see if I can reproduce whatever downstream errors were seen in (https://github.com/narwhals-dev/narwhals/pull/1412#issuecomment-2492258956)
- The issue appears to be the same as (#1930)
- Didn't show up for `v1.(Data|Lazy)Frame` because they use a different `TypeVar` to their parent
=> feat(typing): Backport generic `Series` to `v1`

docs/api-reference/dataframe.md, narwhals/_arrow/dataframe.py, narwhals/_pandas_like/dataframe.py, narwhals/_polars/dataframe.py, narwhals/dataframe.py, tests/frame/columns_test.py
- Closes #2101
- See (https://github.com/narwhals-dev/narwhals/pull/2104#discussion_r1971956027)
=> feat: Adds `DataFrame.iter_columns`

docs/backcompat.md, narwhals/dataframe.py, narwhals/expr.py, narwhals/stable/v1/__init__.py, tests/expr_and_series/arg_true_test.py, tests/expr_and_series/gather_every_test.py, tests/expr_and_series/head_test.py, tests/expr_and_series/sample_test.py, tests/expr_and_series/sort_test.py, tests/expr_and_series/tail_test.py, tests/frame/gather_every_test.py, tests/stable_api_test.py
=> chore: deprecate `LazyFrame.gather_every` in main namespace (but maintain it in stable.v1)

narwhals/dataframe.py, tests/frame/filter_test.py
=> fix: Allow exprs in `.filter` constraints

narwhals/_arrow/dataframe.py, narwhals/_dask/dataframe.py, narwhals/_duckdb/dataframe.py, narwhals/_expression_parsing.py, narwhals/_pandas_like/dataframe.py, narwhals/_polars/dataframe.py, narwhals/_polars/series.py, narwhals/_spark_like/dataframe.py, narwhals/typing.py, narwhals/utils.py
- Originally in (#2064)
- See `mypy` errors fixed in (https://github.com/narwhals-dev/narwhals/commit/c11dc9566c5097a3be4675a36565128aef0986f3)
- Will eventually support (https://github.com/narwhals-dev/narwhals/pull/2104#discussion_r1971956027)
=> chore(typing): Generic `CompliantDataFrame`

docs/api-reference/narwhals.md, narwhals/__init__.py, narwhals/_arrow/namespace.py, narwhals/_dask/namespace.py, narwhals/_duckdb/namespace.py, narwhals/_pandas_like/namespace.py, narwhals/_spark_like/namespace.py, narwhals/functions.py, narwhals/stable/v1/__init__.py, tests/expr_and_series/exclude_test.py
- Closes https://github.com/narwhals-dev/narwhals/issues/2083
This PR adds `nw.exclude` and unit tests.
=> feat: Adds `nw.exclude`

narwhals/dataframe.py, narwhals/dtypes.py, narwhals/expr_cat.py, narwhals/expr_dt.py, narwhals/expr_list.py, narwhals/expr_name.py, narwhals/expr_str.py
* expr_dt
* expr_cat
* dataframe
* dtypes
* exp_str - fix slice-
* expr_list
* expr_name
=> docs: more concise docstrings(#2068)

narwhals/dtypes.py
- Related issue https://github.com/narwhals-dev/narwhals/issues/1077
This PR adds an example for the Field dtype. (Basically, the same as the Struct example, but accessing showing the fields)
=> docs: Add API example docs for Field dtype

tests/expr_and_series/dt/timestamp_test.py, tests/utils.py
=> test: enhance xfail markers with specific reasons in timestamp_test.py

narwhals/_arrow/expr.py, narwhals/_arrow/namespace.py, narwhals/_dask/expr.py, narwhals/_dask/namespace.py, narwhals/_duckdb/expr.py, narwhals/_duckdb/namespace.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/namespace.py, narwhals/_spark_like/expr.py, narwhals/_spark_like/namespace.py, narwhals/utils.py
Follow-up on [comment](https://github.com/narwhals-dev/narwhals/pull/2122#discussion_r1976370057)
=> refactor: allow callable in `CompliantExpr.from_column_names` to reuse for `CompliantNamespace.<all|col|exclude>`

narwhals/_arrow/namespace.py, narwhals/_expression_parsing.py
- https://github.com/astral-sh/ruff/pull/16131
- https://github.com/narwhals-dev/narwhals/pull/2028#discussion_r1957854827
- https://docs.python.org/3/library/itertools.html#itertools.chain.from_iterable
- Even if there were no performance benefit, I find this much easier to read than nested comprehensions
- There are likely a lot more places we could do this
- Kinda difficult to search for
=> refactor: Use `chain.from_iterable` more

narwhals/_arrow/group_by.py, narwhals/_dask/expr.py, narwhals/_dask/group_by.py, narwhals/_expression_parsing.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/group_by.py, pyproject.toml, tests/expr_and_series/over_test.py, tests/expr_and_series/rank_test.py
This simplifies a lot on the pandas side, and unlocks `.over` for dask
On the downside, for some very old versions of pandas (pre 1.1), some tests would fail...but tbh those versions are so old i'm not overly bothered. pandas 1.0 is >5 years old...
=> feat: support anonymous expressions in `over` context for pandas-like, support `over` for multi-partitioned dask

narwhals/_pandas_like/expr.py, tests/expr_and_series/over_test.py
=> feat: support reversed cumulative expressions in `over` for pandas-like

utils/generate_zen_content.py
No longer causing a commotion https://github.com/narwhals-dev/narwhals/pull/2119#issuecomment-2697736818
```log
PS C:\Users\danie\Documents\GitHub\narwhals> mkdocs serve
⣿⣿⣿⣿⣿⠘⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿ THE ZEN OF NARWHALS
⣿⣿⣿⣿⣿⠠⢹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿ Keep it simple
⣿⣿⣿⣿⣿⡀⡄⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿ Move slowly and keep things working
⣿⣿⣿⣿⣿⡇⡼⡘⠛⠿⠿⠿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿ A good API is an honest one
⣿⣿⣿⡿⣫⡄⠾⣣⠹⣿⣿⣿⣶⣮⣙⠻⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿ Yes, that needs documenting
⣿⣿⢋⣴⣿⣷⣬⣭⣾⣿⣿⣿⣿⣿⣿⣿⣦⡙⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿ People learn better from examples
⣿⢃⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⡌⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿   than from explanations⠀
⡏⠀⢰⠄⢻⣿⣿⣿⣿⡿⠋⢉⠻⣿⣿⣿⣿⣿⣿⡜⣿⣿⡿⢁⢻⣿⣿⣿⣿⣿ If in doubt, better to say 'no'
⡇⣌⣀⣠⣾⣿⣿⣿⣿⣇⠶⠉⢁⣿⣿⣿⣿⣿⣿⣧⡹⣿⡇⣿⣧⠻⠿⠿⠿⠿   than to risk causing a commotion⠀
⢡⣆⢻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⡙⣿⣿⡇⣿⣿⣿⣿⠟⣋⣭⣛⠻⣋⣴⣿ If …
```
=> ci: fix doc build for `win32`

.github/workflows/downstream_tests.yml, README.md, docs/ecosystem.md
[darts#2661](https://github.com/unit8co/darts/pull/2661) just got merged
Darts entire test suite takes a bit too much for our use case - Narwhals is used in `TimeSeries` class, that's what I am adding as test here
=> ci: Add darts to downstream tests

narwhals/typing.py, tests/translate/from_native_test.py
Closes #2111
- Related issue https://github.com/narwhals-dev/narwhals/pull/2110#discussion_r1973726417
- Closes #2111
Of the possible common methods, this avoid `np.ndarray` matching - as well as builtins.
- `filter`
- `unique`
- `value_counts`
- `equals`
- `take` (numpy)
- `to_numpy`
- `__array__` (numpy)
- `__len__` (numpy)
- `__iter__` (numpy)
=> fix(typing): Narrow `NativeSeries` Protocol

narwhals/_arrow/expr.py, narwhals/_arrow/series.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/series.py, narwhals/series.py
Technically breaking, but I don't think it should affect anyone - if the downstream tests pass maybe we can silently get this through
=> fix!: align `Series.filter` param name with Polars

.github/workflows/extremes.yml, .github/workflows/pytest.yml, narwhals/_duckdb/expr_str.py, narwhals/_duckdb/utils.py, narwhals/_pandas_like/series_str.py, narwhals/_pandas_like/utils.py, narwhals/_spark_like/utils.py, narwhals/expr_str.py, narwhals/series_str.py, tests/expr_and_series/str/to_datetime_test.py, tests/utils.py
=> fix: parse timezone-aware datetime strings as UTC consistently across backends

narwhals/utils.py, tests/utils_test.py
- https://github.com/pandas-dev/pandas-stubs/commit/6db30fc168beb804e18583a5ad2774987fab5397
- https://github.com/narwhals-dev/narwhals/actions/runs/13747014405/job/38443181887
- https://github.com/narwhals-dev/narwhals/actions/runs/13749535089/job/38448716053?pr=2149
- https://github.com/pandas-dev/pandas-stubs/pull/1115
Resolves `mypy` warnings that started appearing yesterday - after the stubs were updated.
Great to see your work upstream paying off @MarcoGorelli :tada:
=> chore(typing): remove unused `pandas-stubs` ignores

tests/expr_and_series/struct_/field_test.py
=> ci: unxfail sqlframe

narwhals/_spark_like/dataframe.py, narwhals/_spark_like/group_by.py
- #2185
**Temporarily** ignoring new typing errors that appeared after https://github.com/eakmanrq/sqlframe/releases/tag/v3.24.0
=> chore(typing): Resolve `sqlframe>=3.24.0` errors

.github/workflows/pytest.yml, .github/workflows/typing.yml, CONTRIBUTING.md, narwhals/_spark_like/dataframe.py, narwhals/_spark_like/expr.py, narwhals/_spark_like/expr_dt.py, narwhals/_spark_like/expr_str.py, narwhals/_spark_like/expr_struct.py, narwhals/_spark_like/group_by.py, narwhals/_spark_like/namespace.py, narwhals/_spark_like/selectors.py, narwhals/_spark_like/typing.py, narwhals/_spark_like/utils.py, narwhals/dependencies.py, narwhals/translate.py, pyproject.toml, tests/conftest.py, tests/translate/from_native_test.py, tests/utils.py
=> type: Use SQLFrame instead of PySpark to type `_spark_like` internally

narwhals/_arrow/group_by.py, narwhals/_arrow/namespace.py, narwhals/_arrow/utils.py, narwhals/functions.py, narwhals/stable/v1/__init__.py, tests/expr_and_series/concat_str_test.py, tests/expr_and_series/lit_test.py
=> fix: don't downcast `large_string` to `string` unnecessarily in `concat_str` for PyArrow

.github/workflows/extremes.yml, docs/api-reference/lazyframe.md, narwhals/_dask/dataframe.py, narwhals/_dask/namespace.py, narwhals/_duckdb/dataframe.py, narwhals/_spark_like/dataframe.py, narwhals/dataframe.py, tests/expr_and_series/len_test.py, tests/frame/clone_test.py, tests/frame/select_test.py, tests/frame/with_columns_test.py
closes #2205
This doesn't break any downstream tests, and `narwhals.LazyFrame` isn't widely used (yet 🤞 ) so I think it's OK to be slightly more aggressive with changes there
We can always yank / revert if anyone complains and go through the usual process
=> feat!: remove require at least one expression be passed to lazyframe select and lazyframe.with_columns, remove lazyframe.clone

narwhals/functions.py, narwhals/stable/v1/__init__.py, tests/from_numpy_test.py
=> chore: Deprecate `native_namespace` in favour of `backend` in `from_numpy`

narwhals/functions.py, narwhals/stable/v1/__init__.py, tests/read_scan_test.py
=> chore: Deprecate `native_namespace` in favour of `backend` in `read_parquet`

narwhals/functions.py, narwhals/stable/v1/__init__.py, tests/read_scan_test.py
=> chore: Deprecate `native_namespace` in favour of `backend` in `scan_parquet`

narwhals/functions.py, narwhals/stable/v1/__init__.py, tests/read_scan_test.py
=> chore: Deprecate `native_namespace` in favour of `backend` in `scan_csv`

narwhals/functions.py, narwhals/stable/v1/__init__.py, tests/from_pycapsule_test.py
- Related issue #1888
- `from_arrow` needed to be re-written to avoid the deprecation warning on `v1`
=> chore: Deprecate `native_namespace` in favour of `backend` in `from_arrow`

narwhals/_arrow/utils.py, narwhals/_pandas_like/utils.py, tests/frame/with_columns_test.py
=> feat: Raise uniform error when passing Series of different lengths to `with_columns`

tests/expr_and_series/cast_test.py
Given that we check specifically for pandas implementation in:
https://github.com/narwhals-dev/narwhals/blob/ac4ee8ab79c397608ba8d39f82a5a7195f7e2e57/narwhals/_pandas_like/utils.py#L595-L599
we should have xfailed cudf from the beginning
=> patch: xfail `cast_test.py::test_cast_time` for cudf

noxfile.py
nox-2025.2.9 failed with:
```
ValueError: ("'reuse_venv' must be in ['no', 'yes', 'never', 'always'] (got True)", Attribute(name='reuse_venv', default=NOTHING, validator=<optional validator for <in_ validator with options ['no', 'yes', 'never', 'always']> or None>, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type="None | Literal['no', 'yes', 'never', 'always']", converter=None, kw_only=True, inherited=False, on_setattr=None, alias='reuse_venv'), ['no', 'yes', 'never', 'always'], True)
```
=> Fix `noxfile.py` syntax for nox-2025.2.9

narwhals/_dask/dataframe.py, narwhals/_dask/group_by.py, narwhals/_duckdb/dataframe.py, narwhals/dataframe.py, tests/frame/unique_test.py
If this affects anyone, we could backport `maintain_order` as a no-op to `stable.v1`
- https://github.com/narwhals-dev/narwhals/pull/2232#discussion_r2001877791
- https://github.com/narwhals-dev/narwhals/pull/2232#discussion_r2003019826
=> feat!: remove `maintain_order` from `LazyFrame.unique`, as it was never supported

.github/workflows/check_docs_build.yml, .github/workflows/check_tpch_queries.yml, .github/workflows/downstream_tests.yml, .github/workflows/extremes.yml, .github/workflows/pytest.yml, .github/workflows/random_ci_pytest.yml, .github/workflows/typing.yml, CONTRIBUTING.md, Makefile, noxfile.py, pyproject.toml
I propose moving all the dev dependencies from `optional-dependencies` to [`dependency-groups`](https://packaging.python.org/en/latest/specifications/dependency-groups/). I think this is a bit cleaner what do you think? :)
uv related resources:
- https://docs.astral.sh/uv/concepts/projects/dependencies/#dependency-groups
- https://docs.astral.sh/uv/reference/cli/#uv-pip-install--group
=> chore: move dev dependencies to `dependency-groups`

tests/expr_and_series/arithmetic_test.py, tests/expr_and_series/dt/ordinal_day_test.py, tests/expr_and_series/dt/total_minutes_test.py, tests/expr_and_series/rolling_var_test.py, tests/frame/collect_test.py, tests/from_dict_test.py, tests/translate/from_native_test.py
- Related issue #1726
Split and/or skip tests requiring `polars` when they are unavailable. Whenever that was a low-hanging fruit, also imports of `pandas` and `pyarrow` were made optional.
=> test: Fix yet more tests to work without polars (pandas, pyarrow)

narwhals/_arrow/dataframe.py, narwhals/_compliant/__init__.py, narwhals/_compliant/dataframe.py, narwhals/_compliant/selectors.py, narwhals/_compliant/typing.py, narwhals/_dask/dataframe.py, narwhals/_duckdb/dataframe.py, narwhals/_expression_parsing.py, narwhals/_pandas_like/dataframe.py, narwhals/_polars/dataframe.py, narwhals/_spark_like/dataframe.py, narwhals/utils.py
- #2232
- #2230
- #2130
- `CompliantLazyFrame.native` will exist after (#2232) merges
- Made sense to do this *before* `CompliantGroupBy` (#2230)
- Then that can just depend on `.native`
=> chore: Add `CompliantDataFrame.native`

.github/workflows/downstream_tests.yml, pyproject.toml
I noticed the same problem we had for `tea-tasting` for `validoopsie`. If we don't add a `pytest` config, `pytest` will try to use the one of `narwhals`
Plus reordered the dependency groups as in @dangotbanned comment https://github.com/narwhals-dev/narwhals/pull/2238#discussion_r2003306918. 
It is the same ordering as in the [packaging docs](https://packaging.python.org/en/latest/specifications/dependency-groups/#dependency-group-include) with the `groups-include` at the end
=> chore: downstream CI cleanup (`validoopsie` and `pointblank`) and re-order dependency groups

.github/workflows/extremes.yml, .github/workflows/pytest.yml, Makefile, narwhals/_duckdb/dataframe.py, narwhals/_duckdb/expr.py, narwhals/_duckdb/typing.py, narwhals/_duckdb/utils.py, narwhals/_spark_like/expr.py, narwhals/dependencies.py, pyproject.toml, tests/expr_and_series/cum_sum_test.py, tests/expr_and_series/over_test.py, tests/expr_and_series/reduction_test.py, tests/expr_and_series/rolling_sum_test.py, tests/expr_and_series/str/to_datetime_test.py, tests/expr_and_series/sum_horizontal_test.py, tests/frame/select_test.py, tests/stable_api_test.py
=> feat: support window operations for DuckDB

narwhals/_arrow/expr.py, narwhals/_pandas_like/expr.py, tests/expr_and_series/is_last_distinct_test.py
closes https://github.com/narwhals-dev/narwhals/issues/2268
=> fix: safety assertion was being thrown for Expr.is_last_distinct with over and _order_by by pandas and pyarrow

narwhals/_compliant/group_by.py, narwhals/_compliant/namespace.py, narwhals/_compliant/typing.py
- #2266 
- #2261 
Was just waiting for this commit to land first (https://github.com/narwhals-dev/narwhals/pull/2261/commits/3b81fbe209d52c3b510851bf33f64e76fbc43e01)
=> chore(typing): Move `DepthTracking*` typing

tests/frame/join_test.py
=> ci: skip test_join_duplicate_column_names on old polars

narwhals/_dask/dataframe.py, narwhals/_duckdb/dataframe.py, narwhals/_pandas_like/dataframe.py, narwhals/_polars/dataframe.py, narwhals/_spark_like/dataframe.py
=> chore: Update `._native_frame` refs

CONTRIBUTING.md, tests/expr_and_series/cum_count_test.py, tests/expr_and_series/cum_max_test.py, tests/expr_and_series/cum_min_test.py, tests/expr_and_series/cum_prod_test.py, tests/expr_and_series/cum_sum_test.py, tests/expr_and_series/over_test.py, tests/utils.py
I noticed that some `expected` dicts didn't have the whole data. Not sure if it was intentional but I think it is safer this way. If we don't want certain columns to be checked we could still `drop` them before the assert.
What do you think?
=> test: ensure `expected` data has every column of the`result` data

narwhals/functions.py, tests/expr_and_series/cum_prod_test.py, tests/read_scan_test.py
[SQLFrame#349](https://github.com/eakmanrq/sqlframe/pull/349) added support to pass options in reader and there is already a release out 🙌🏼
=> feat(sqlframe): Allow options in `scan_parquet` function

narwhals/_interchange/series.py, narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/namespace.py, narwhals/_pandas_like/series.py, narwhals/_pandas_like/utils.py, narwhals/_polars/expr.py, narwhals/_polars/series.py, narwhals/_polars/utils.py, narwhals/utils.py
- #2230
- #2290
- I've left out `PandasLikeSeries*Namespace`
- Planning to do a bigger change to align with `Arrow*`
- See #2130
=> chore: Update `._native_series` refs

pyproject.toml
- Fixes https://github.com/narwhals-dev/narwhals/pull/2296#issuecomment-2754336489
- #2286
No longer getting the failures from missing `product` in `sqlframe`
=> ci: Remove `sqlframe` pin from `--group typing`

narwhals/_arrow/series.py, narwhals/_arrow/utils.py, narwhals/_duckdb/expr.py, narwhals/_pandas_like/series.py, narwhals/_spark_like/expr.py
=> perf: Avoid unnecessary calls in `Expr.clip` method

narwhals/_arrow/series.py, narwhals/_arrow/utils.py, narwhals/_compliant/series.py, narwhals/_expression_parsing.py, narwhals/_pandas_like/series.py, narwhals/_pandas_like/utils.py, tests/expr_and_series/mode_test.py
closes #2273
This is definitely not THE solution, we need to find a better way of preserving the `_broadcast` attribute in some cases
=> fix: Expr.mode broadcasting

narwhals/_arrow/dataframe.py, narwhals/_compliant/dataframe.py, narwhals/_pandas_like/dataframe.py, narwhals/_polars/dataframe.py, narwhals/_translate.py, narwhals/functions.py, narwhals/stable/v1/__init__.py
- #2283
- #2302
- Part of #2116
=> refactor: Add `CompliantDataFrame.from_dict`

.github/workflows/downstream_tests.yml, narwhals/expr.py, tests/expression_parsing_test.py
We currently allow `nw.col('a').mean().over(order_by='i')`, but probably shouldn't because the `order_by` has no effect there and is a sign of a user-error
=> feat: disallow `.over(order_by=...)` for non-order-dependent operations (as it signals a user error)

narwhals/_polars/expr.py
- #2305
- #2230
- #1942 
Missed during the linked PRs/issues, but noticed in (#2312)
=> chore: Tidy up `PolarsExpr`

narwhals/_polars/utils.py
- Related issue #2192
I noticed a new one in (#2192) and thought I'd get them all in one sweep
=> chore(typing): Resolve `_polars.utils` dtype ignores

narwhals/_duckdb/expr.py, narwhals/expr.py, tests/expression_parsing_test.py
`rank` shouldn't have been classed as "window function"
it doesn't depend on the physical order of the data
in fact, it's forbidden to call `rank` with `over(order_by=...)`
=> fix: change rank ExprKind to transform

narwhals/_duckdb/dataframe.py, narwhals/_duckdb/expr.py
If we use the Python  API more, we can get more validation (and possibly safety from injections?) than if we use hand-written sql
=> chore: use Python API more in DuckDB

narwhals/_compliant/expr.py, narwhals/_pandas_like/expr.py, tests/expr_and_series/rolling_std_test.py, tests/expr_and_series/rolling_var_test.py
=> ci: fixup cudf test failures, support rolling_std/rolling_var/rolling_mean for pandas in grouped context

narwhals/typing.py, narwhals/utils.py
Noticed during (https://github.com/narwhals-dev/narwhals/pull/2324/commits/8143b37b3251d4f1f882cd2151d0a1fa72a27cfe)
There were **3** issues at play:
- `v1.dtypes` needs to be in the branch *after* `dtypes`
- `v1` dtypes are a subtype of `main`
- The reverse isn't true
- Importing both modules as `dtypes`, but not aliasing one of them
- Using a *mutable* class for `DTypes`, rather than *"immutable"* `@property`(s) in a `Protocol`
=> chore(typing): Fix `DTypes` typing

narwhals/_compliant/expr.py, narwhals/_polars/expr.py, narwhals/_polars/namespace.py, narwhals/_polars/series.py
- https://github.com/narwhals-dev/narwhals/pull/2325#issuecomment-2770524042
- [`39382c5` (#2283)](https://github.com/narwhals-dev/narwhals/pull/2283/commits/39382c5fc58475bd4d1da3f3c63fa8322e24aab7)
- #2236
- #2119
=> chore: Make `Polars(Expr|Series)` compliant

narwhals/_spark_like/dataframe.py, tests/frame/unpivot_test.py
=> fix: unpivot was unnecessary failing for PySpark/SQLFrame when neither `on` nor `index` were passed

narwhals/functions.py, narwhals/stable/v1/__init__.py, tests/frame/invalid_test.py
- Noticed during #2337
- Did something similar in https://github.com/narwhals-dev/narwhals/pull/2283#discussion_r2014022110
- Using a constrained `TypeVar`, like in `polars`
- Marking as *"fix"*, since (335ed0531faee5abcdb3735b4d6004ed761a7d4b) now warns on a failure case
=> refactor(typing): Simplify `concat` signature

narwhals/_arrow/expr.py, narwhals/_compliant/expr.py, narwhals/_compliant/typing.py, narwhals/_compliant/when_then.py, narwhals/_dask/expr.py, narwhals/_duckdb/expr.py, narwhals/_expression_parsing.py, narwhals/_pandas_like/expr.py, narwhals/_spark_like/expr.py, narwhals/utils.py
- https://github.com/narwhals-dev/narwhals/pull/2326#discussion_r2023590983
Follow-up to (https://github.com/narwhals-dev/narwhals/pull/2326#discussion_r2023590983)
=> chore: Use `_compliant.typing` aliases in more places

mkdocs.yml
- https://github.com/narwhals-dev/narwhals/issues/1943#issuecomment-2637599110
- https://mkdocstrings.github.io/python/usage/configuration/signatures/#separate_signature
The signature that was a heading *before*, becomes the final overload
=> docs: Use `separate_signature: true`

tests/conftest.py, tests/series_only/hist_test.py, tests/utils.py
Will close #2346
<details><summary>Description (copied from issue)</summary>
<p>
When I initially tried to fix this in (https://github.com/narwhals-dev/narwhals/pull/2232#discussion_r2001807332) - most of the **795** errors were from tests using `IntoFrame`/`IntoDataFrame`.
https://github.com/narwhals-dev/narwhals/blob/d2a9f423688c14e524d28e7d282bfa5de3c888be/tests/utils.py#L45-L46
AFAICT, none of these constructors should need to use a `TypeAlias` that mentions `nw.DataFrame` or `nw.LazyFrame`.
They all return a **native** object
<details><summary><code>conftest.py</code></summary>
<p>
https://github.com/narwhals-dev/narwhals/blob/d2a9f423688c14e524d28e7d282bfa5de3c888be/tests/conftest.py#L72-L222
</p>
</details> 
https://github.com/narwhals-dev/narwhals/blob/d2a9f423688c14e524d28e7d282bf …
=> test(typing): Narrow  `Constructor`, `ConstructorEager` aliases

narwhals/functions.py, narwhals/stable/v1/__init__.py, narwhals/translate.py, narwhals/typing.py, tests/translate/from_native_test.py
Will close #2343
- Closes #2343
- Changing `IntoSeries` gets us *most* of the way there
- Settled on a bit of a creative solution
=> fix(typing): Narrow `TypeVar` used in `Series`

narwhals/_arrow/series.py, narwhals/_arrow/typing.py, narwhals/_arrow/utils.py
- #2350
Follow-up to https://github.com/narwhals-dev/narwhals/pull/2350#issuecomment-2782903099
Original error(s) were trying to warn about dividing a `Scalar` by an `Array`.
But, with the new typing - we don't *artificially* introduce a `Scalar` as a possibility on the left-hand-side
=> chore(typing): Preserve containers in `cast_for_truediv`

docs/api-reference/typing.md, narwhals/_arrow/dataframe.py, narwhals/_arrow/expr.py, narwhals/_arrow/namespace.py, narwhals/_arrow/series.py, narwhals/_compliant/dataframe.py, narwhals/_compliant/expr.py, narwhals/_compliant/namespace.py, narwhals/_compliant/series.py, narwhals/_dask/dataframe.py, narwhals/_dask/expr.py, narwhals/_dask/namespace.py, narwhals/_duckdb/dataframe.py, narwhals/_duckdb/expr.py, narwhals/_duckdb/namespace.py, narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/expr.py, narwhals/_pandas_like/namespace.py, narwhals/_pandas_like/series.py, narwhals/_polars/dataframe.py, narwhals/_spark_like/dataframe.py, narwhals/_spark_like/expr.py, narwhals/_spark_like/namespace.py, narwhals/dataframe.py, narwhals/expr.py, narwhals/functions.py, narwhals/series.py, narwhals/stable/v1/__init__.py, narwhals/typing.py
Closes #2359
- Closes #2359
- Parent issue: #2337
- Completes *most of* (#2337)
- Copying over the docs revealed they're a bit inconsistent
- Think that's inherited though
- Aligned some in (https://github.com/narwhals-dev/narwhals/pull/2352/commits/fb2abc8dbb18ef4141ab79b10210a5035865eafa)
=> feat(typing): Add `polars` literal aliases

narwhals/_compliant/namespace.py, narwhals/_dask/namespace.py, narwhals/_duckdb/namespace.py, narwhals/_spark_like/namespace.py, narwhals/functions.py, narwhals/stable/v1/__init__.py, tests/frame/concat_test.py, tests/series_only/hist_test.py
=> feat!: disallow `concat(..., how="horizontal")` for `LazyFrame`

narwhals/_arrow/series.py, narwhals/_pandas_like/series.py, narwhals/_polars/series.py, tests/series_only/hist_test.py
1. All narwhals hist behavior should follow Polars 1.27
2. Add histogram fastpaths for no data, or singly binned hists for perf and smooth differences across backends  
3. Slim down the hypothesis testing, as spurious errors would pop up due to floating point precision differences for the compute backends.
=> Fix: Align ``Series.hist`` with new Polars behaviour

.github/workflows/check_tpch_queries.yml, narwhals/_duckdb/dataframe.py, narwhals/_duckdb/expr.py, narwhals/_duckdb/utils.py, tests/frame/unique_test.py
Use Python API for instead of handwritten SQL
This does meaning raising the minimum duckdb required version for `unique` with `subset` specified, but I think that's OK
=> chore!: use Python API more for DuckDB support

tests/expr_and_series/gather_every_test.py, tests/expr_and_series/head_test.py, tests/expr_and_series/sample_test.py, tests/expr_and_series/sort_test.py, tests/expr_and_series/tail_test.py, tests/frame/gather_every_test.py, tests/frame/join_test.py, tests/frame/schema_test.py
Towards v2
The idea is:
- in tests which use both `v1` and main APIs, alias the v1 one to `nw_v1`
Later:
- always use the main API for tests
- make separate `v1_test.py` and `v2_test.py` which test methods which we overwrite from the stable apis 
=> chore: use nw_v1 / nw naming consistently in tests

narwhals/_arrow/dataframe.py, narwhals/_arrow/series.py, narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/series.py, narwhals/dataframe.py, narwhals/utils.py
urrgh, I noticed there's some parts where we're iterating over objects which are used to filter/select rows, which we should never be doing
=> perf: Only use first element to sniff types in sequences in `__getitem__` and `filter`

CONTRIBUTING.md
The syntax for installing from `optional-dependencies` vs. `dependency-groups` is different, so the old instructions for e.g. `typing` no longer work. Everything suggested to be installed for the `test` and `typing` groups, along with installing pre-commit, is already done via the `local-dev` group too.
By the way, pip's current release v25.0.1 doesn't _yet_ support dependency groups, but [the upcoming 25.1.0 release will](https://pip.pypa.io/en/latest/user_guide/#dependency-groups), using identical syntax. So in the near future these commands should work for both uv and pip.
=> docs: Update installation guide to reflect use of `dependency-groups`

narwhals/dependencies.py, tests/dependencies/is_numpy_scalar_test.py
Closes #2394
- Closes #2394
- Still keeping this utility internal
- We didn't see an issue, as it was always used on the same branch as an `int` guard
=> fix: Use `np.generic` in `is_numpy_scalar`

narwhals/dtypes.py
- Related issue #1077
- Closes #1077
Added docstring examples for last two dtypes missing them:
- Int128 (polars, pyarrow + duckdb)
- UInt128 (pandas df + duckdb, maybe the only backend supporting this dtype?)
I used the other dtypes as an example to follow, but I'm happy to make any changes if these don't match what you're looking for!
=> docs: add docstrings examples for Int128 and UInt128

narwhals/utils.py
- https://github.com/narwhals-dev/narwhals/pull/2325#discussion_r2051112276
- https://github.com/narwhals-dev/narwhals/pull/2384#discussion_r2041188135
https://github.com/narwhals-dev/narwhals/pull/2325#discussion_r2051439200
> [#2325 (comment)](https://github.com/narwhals-dev/narwhals/pull/2325#discussion_r2051112276)
> 
> @FBruzzesi lol that's my bad for making a suggestion without an IDE in [#2325 (comment)](https://github.com/narwhals-dev/narwhals/pull/2325#discussion_r2051112276)
> 
> `is_list_of` wasn't supposed to have the `type` part in the return 🤦‍♂️:
> 
> ```python
> # def is_list_of(obj: Any, tp: type[_T]) -> TypeIs[list[type[_T]]]:
> def is_list_of(obj: Any, tp: type[_T]) -> TypeIs[list[_T]]:
> ```
> 
> Will fix this shortly
=> chore(typing): Remove `type` from `is_list_of` return

narwhals/_spark_like/expr.py, narwhals/_spark_like/utils.py
First noticed in [#2417 comment](https://github.com/narwhals-dev/narwhals/pull/2417#discussion_r2054858516)
Depending on pyspark and python version I started to get the following warning:
> No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
=> patch: Avoid pyspark no partition for window ops warning

.pre-commit-config.yaml, narwhals/_arrow/namespace.py, narwhals/_arrow/series.py, narwhals/_arrow/series_dt.py, narwhals/_arrow/utils.py, narwhals/_compliant/selectors.py, narwhals/_dask/expr_dt.py, narwhals/_dask/utils.py, narwhals/_duckdb/dataframe.py, narwhals/_duckdb/utils.py, narwhals/_ibis/dataframe.py, narwhals/_interchange/dataframe.py, narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/namespace.py, narwhals/_pandas_like/series.py, narwhals/_pandas_like/series_dt.py, narwhals/_pandas_like/series_list.py, narwhals/_pandas_like/utils.py, narwhals/_polars/utils.py, narwhals/_spark_like/dataframe.py, narwhals/_spark_like/utils.py, narwhals/utils.py
=> chore: Add `Version.dtypes`, remove `import_dtypes_module`

narwhals/_arrow/dataframe.py
We don't need to convert to `list` since a `dict` is [supported](https://arrow.apache.org/docs/17.0/python/generated/pyarrow.Table.html#pyarrow.Table.rename_columns)
While adding this, I noticed we used [ `pa.Table.column_names`](https://arrow.apache.org/docs/python/generated/pyarrow.Table.html#pyarrow.Table.column_names) here, but not in `ArrowDataFrame.columns`.
Wasn't clear why (#350) chose to use `schema.names`.
Searching for other usage led me to `to_dict` where I spotted a nice rewrite 😎
=> perf: Add `pa.Table` rename fastpath for `>=17`

.github/workflows/pytest-pyspark.yml, narwhals/_duckdb/expr.py, narwhals/_spark_like/expr.py, narwhals/expr.py, tests/expr_and_series/fill_null_test.py
=> feat: Allow non-null strategy in `fill_null` for DuckDB and SparkLike

narwhals/_arrow/dataframe.py, narwhals/_arrow/namespace.py, narwhals/_arrow/series.py, narwhals/_arrow/typing.py, narwhals/_arrow/utils.py, narwhals/_compliant/series.py, narwhals/_pandas_like/series.py, narwhals/_polars/series.py, narwhals/dependencies.py, narwhals/series.py
- Mainly trying to be consistent with the convention from (https://github.com/narwhals-dev/narwhals/blob/857b08ad270d723fe391277611a0d7d00df5fdef/narwhals/_compliant/typing.py)
- Use `*Any` for an alias to simplify `*[Any*]`
- Removes the `Arrow*` prefix
- That clashes with how our **compliant** classes are named
- The aliases are for **native** types
- Replaces all usage outside of `_arrow` with `pa.*`
- Shouldn't have been exposed, especially as they aren't available at runtime
=> chore(typing): Rename, unleak `_arrow.typing` aliases

narwhals/_pandas_like/utils.py, narwhals/_polars/utils.py, narwhals/dtypes.py, narwhals/utils.py, tests/dtypes_test.py, tests/utils_test.py
Closes #2412
- #2414
- https://github.com/narwhals-dev/narwhals/pull/2414#issuecomment-2823734330
Related to the name change from `_Delayed*` -> `_Deferred`.
I think that's a more common term for a lazy operation. When I see *delay*, it makes me think of time delay instead
- https://peps.python.org/pep-0749/
- https://github.com/ibis-project/ibis/blob/bd926f0fbda023124453b824aa24dc4a50e27d72/ibis/common/deferred.py
- https://discuss.python.org/t/backquotes-for-deferred-expression/70577
=> perf: Optimize, generalize `_DelayedCategories` -> `_DeferredIterable`

narwhals/_dask/namespace.py, narwhals/_dask/utils.py
We don't need these name-preserving ops any more as aliases are set as late as possible anyway
=> chore: Remove name-preserving Dask operations

narwhals/_translate.py, tests/no_imports_test.py
=> perf: Avoid module-level `importlib.util.find_spec`

tests/expr_and_series/dt/truncate_test.py
I'll try adding a workflow to test this use case (separately).
=> test: make `polars` optional in `truncate_test`

narwhals/dataframe.py, tests/frame/join_test.py
- https://github.com/narwhals-dev/narwhals/pull/2000#discussion_r2076086401
=> chore: Ensure (`join|join_asof`) predicate lengths match

narwhals/dependencies.py, narwhals/translate.py, tests/translate/to_py_scalar_test.py
=> chore: Simplify `to_py_scalar`

docs/installation.md, narwhals/__init__.py, pyproject.toml
=> release: Bump version to 1.38.1

utils/bump_version.py
=> fix: Add `new_version.strip()` in `bump_version.py`, otherwise the tag will be invalid

narwhals/_compliant/group_by.py, tests/group_by_test.py
Like this we get
```sql
WITH "t27701520" AS (
SELECT
"penguins"."island_name" AS "_island_name_tmp",
ROUND("penguins"."height", 10) AS "_height_tmp_",
AVG("penguins"."weight") AS "weight"
FROM "penguins" AS "penguins"
JOIN "islands" AS "islands"
ON "islands"."name" = "penguins"."island_name"
GROUP BY
"penguins"."island_name",
ROUND("penguins"."height", 10)
)
SELECT
"t27701520"."_island_name_tmp" AS "island_name",
"t27701520"."_height_tmp_" AS "height",
"t27701520"."weight" AS "weight"
FROM "t27701520" AS "t27701520"
```
instead of
```sql
WITH "t36714377" AS (
SELECT
"penguins"."island_name" AS "island_name____________",
ROUND("penguins"."height", 10) AS "height____________",
AVG("penguins"."weight") AS "weight"
FROM "penguins" AS "penguins"
JOIN "islands" AS "islands"
ON "islands"."name" …
```
=> feat: Generate nicer-looking SQL when grouping by expressions

narwhals/functions.py, narwhals/stable/v1/__init__.py, narwhals/stable/v1/typing.py, narwhals/typing.py, tpch/__init__.py, tpch/_typing.py, tpch/queries/q1.py, tpch/queries/q10.py, tpch/queries/q11.py, tpch/queries/q12.py, tpch/queries/q13.py, tpch/queries/q14.py, tpch/queries/q15.py, tpch/queries/q16.py, tpch/queries/q17.py, tpch/queries/q18.py, tpch/queries/q19.py, tpch/queries/q2.py, tpch/queries/q20.py, tpch/queries/q21.py, tpch/queries/q22.py, tpch/queries/q3.py, tpch/queries/q4.py, tpch/queries/q5.py, tpch/queries/q6.py, tpch/queries/q7.py, tpch/queries/q8.py, tpch/queries/q9.py
closes #2537 
We do carve out an exception for this in https://narwhals-dev.github.io/narwhals/backcompat/#exceptions, and it doesn't look like it affects any downstream libraries
=> TYP: Make `FrameT` more precise

narwhals/_compliant/expr.py
=> chore: remove redundant storing of `scalar_kwargs` in `EagerExpr`

narwhals/_ibis/dataframe.py
- Related issue #2525
This is a quick fix
@MarcoGorelli @dangotbanned I think we start to have a few piece of the code base (such as this one) which can be abstracted for duckdb, ibis and spark-like (dask tbd). I am having a hard time to come up with a name for such compliant class, mostly because `EagerDataFrame` inherits from `CompliantLazyFrame` 😂 `LazyDataFrame` does not sound right for some reason.
=> chore: Cache ibis columns property

narwhals/_ibis/expr_dt.py, tests/expr_and_series/dt/truncate_test.py
=> chore: Remap '1q' to '3mo' in `IbisExpr.dt.truncate`

narwhals/_duckdb/dataframe.py, narwhals/_duckdb/expr.py, narwhals/_duckdb/expr_str.py, narwhals/_duckdb/namespace.py, narwhals/_duckdb/selectors.py, narwhals/_duckdb/typing.py, narwhals/_duckdb/utils.py
=> chore: use `Expression` instead of `duckdb.Expression` for typing

narwhals/_compliant/dataframe.py, narwhals/_compliant/expr.py, narwhals/_compliant/group_by.py, narwhals/_compliant/selectors.py, narwhals/_compliant/when_then.py, narwhals/_translate.py, narwhals/_typing_compat.py, narwhals/stable/v1/__init__.py, narwhals/utils.py
- Mentioned in (https://github.com/narwhals-dev/narwhals/pull/2391#issuecomment-2832442331)
- Needed again for (#2572)
**Module doc preview**
---
I was [originally expecting](https://github.com/narwhals-dev/narwhals/pull/2391#issuecomment-2832442331) we'd need to add some config for `ruff` and `mypy`. 
Haven't had any issues without it, so I'm not sure we need it?
=> chore: Add `_typing_compat` module

tests/translate/from_native_test.py
this just fixes the typing part, so please don't add the pyspark label (we can fix the pyspark test failures separately)
=> ci: fix typing for pyspark 4.0

narwhals/translate.py, tests/translate/get_native_namespace_test.py
=> fix: Include all backends in `get_native_namespace`

pyproject.toml
- Related https://github.com/narwhals-dev/narwhals/pull/2572#discussion_r2104768749
I discovered the hard way why this config was needed.
It avoids this (unused import) false positive on forward references used in `TypeVar`
=> chore(ruff): Add `tool.ruff.lint.typing-modules`

narwhals/_spark_like/dataframe.py, narwhals/_spark_like/expr_dt.py, narwhals/_spark_like/utils.py, tests/dtypes_test.py, tests/expr_and_series/dt/convert_time_zone_test.py, tests/expr_and_series/dt/replace_time_zone_test.py
intended as follow-up to #2590
=> enh: reflect connection time zone in Datetime for pyspark, support convert_time_zone and replace_time_zone

narwhals/stable/v1/__init__.py, tests/v1_test.py
=> chore: remove unnecessary `concat` in stable.v1

narwhals/_duckdb/series.py, narwhals/_ibis/series.py, narwhals/_interchange/dataframe.py, narwhals/_interchange/series.py, narwhals/translate.py, tests/frame/interchange_native_namespace_test.py, tests/frame/interchange_schema_test.py, tests/translate/from_native_test.py
=> api: remove support for dataframe interchange protocol from main namespace (but keep supported in `narwhals.stable.v1`

narwhals/expr.py, narwhals/series.py
=> docs: fix `replace_all` typo in `replace_strict` docstring

narwhals/_compliant/when_then.py, narwhals/_dask/expr.py, narwhals/_dask/namespace.py, narwhals/_duckdb/namespace.py, narwhals/_spark_like/namespace.py, narwhals/dependencies.py, narwhals/functions.py, tests/expr_and_series/when_test.py
- Related issue #2645 
This adds broadcasting behavior to the `when/then` pattern similar to Polars (see #2645) for our eager backends and dask.
The implementation for the Lazy backends will require #2652 unless we want to introduce some hacky workarounds (e.g. we may be able to do this by joining after an aggregation to "broadcast" results; however I haven't fully thought through how this would look in the codebase).
=> feat: when-then broadcasting

docs/backcompat.md, narwhals/functions.py, narwhals/stable/v1/__init__.py, tests/frame/interchange_schema_test.py, tests/stable_api_test.py, tests/v1_test.py
=> depr: Deprecate `nw.get_level` from main namespace

tests/expr_and_series/arithmetic_test.py
A few tests had this comment:
> ```
> # hypothesis complains if we add `constructor` as an argument, so this
> # test is a bit manual unfortunately
> ```
Not sure if I'm missing something but I was able to swap in the constructor_eager argument without an issue.
=> test: refactor arithmetic floordiv and mod

narwhals/_pandas_like/dataframe.py, narwhals/_pandas_like/utils.py, narwhals/_utils.py
Spotted by @dangotbanned, see [comment](https://github.com/narwhals-dev/narwhals/pull/2511#discussion_r2173209870)
=> chore: Remove pandas-like specific `check_column_names_are_unique` util

tests/get_dtype_backend_test.py
Closes #2759
- Related #2744
- Closes #2759
https://github.com/narwhals-dev/narwhals/issues/2759#issuecomment-3016621477
> Oh right, so the issue is this line
> 
> https://github.com/rapidsai/cudf/blob/22d1b7c75e892f9136e11e47c09e7913910414ea/python/cudf/cudf/core/dtypes.py#L318-L319
> 
> ```py
> class CategoricalDtype(_BaseDtype):
> # ...
>     def construct_from_string(self):
>         raise NotImplementedError()
> ```
> When collecting the `Dtype`s here, I'm only suppressing `TypeError`
> 
> https://github.com/narwhals-dev/narwhals/blob/cd60c428ccb6bccf15d39084a9dba7737696e486/tests/get_dtype_backend_test.py#L117-L125
> 
> I picked `TypeError` because the `pandas` doc was pretty explicit about that error
> 
> 
https://github.com/pandas-dev/pandas/blob/2cc37625532045f4ac55b27176454bbbc9b …
=> test: Suppress `NotImplementedError` for `cuDF`

narwhals/_duckdb/dataframe.py, narwhals/_ibis/dataframe.py, narwhals/_utils.py
this just makes it a bit easier to get v2 started. we should generally assume MAIN behaviour, and make verison-based exceptions when necessary, rather than the other way round
=> chore: invert version.V1 conditions 

.github/workflows/downstream_tests.yml
Reverts narwhals-dev/narwhals#2725
Both libraries have addressed the issue.
Closes #2726
=> Revert "ci: pin scipy"

docs/api-reference/utils.md
Follow-up to https://discord.com/channels/1235257048170762310/1272835535190364283/1393547598568099881
> @dangotbanned 
> Was the inclusion of `Version` in the API docs intentional?
> 
> https://narwhals-dev.github.io/narwhals/api-reference/utils/#narwhals.utils.Version
> 
> I could see someone mistaking it's properties, and by extension *everything as deep as this* as public.
> 
> <img width="940" height="560" alt="image" src="https://github.com/user-attachments/assets/4c86f598-399b-4ed1-afc2-269928ce8bed" />
> 
> 
> But AFAIK, there isn't a user-facing need for `Version` being exposed :thinking:
> @marcogorelli
> i can't remember, but it probably doesn't need to be public
=> docs: Remove `utils.Version` from API Reference

narwhals/_pandas_like/group_by.py, tests/frame/group_by_test.py
i'm not super-keen on how `_select_results` has side-effects
=> chore: take `reset_index(inplace=True)` out of `_select_results`

narwhals/_pandas_like/group_by.py
@dangotbanned I don't want https://github.com/narwhals-dev/narwhals/pull/2680#discussion_r2192995084 to be forgotten
=> chore: Refactor `_apply_exprs_function` internal

narwhals/_pandas_like/series.py, tests/expr_and_series/rank_test.py
=> perf, fix: avoid using `assign` for `Series.rank` in pandas, fix `Series.rank` for nameless pandas Series

narwhals/_polars/dataframe.py, narwhals/_utils.py, narwhals/dataframe.py, narwhals/dtypes.py, narwhals/exceptions.py, tests/dtypes_test.py, tests/expr_and_series/cast_test.py, tests/frame/schema_test.py, tests/v1_test.py
=> enh: issue a performance warning for `LazyFrame.schema`

narwhals/_arrow/series.py, tests/series_only/scatter_test.py
=> fix: `scatter` was raising unnecessarily for pyarrow

narwhals/_duckdb/expr.py, narwhals/_ibis/expr.py, narwhals/_spark_like/expr.py, narwhals/_sql/expr.py
Please let me know if I should additionally do some of the checklist. I ran tests with `pytest tests/expr_and_series/exp_test.py` and the whole suite with `pytest`, both passed for me. Thanks!
=> chore: factor out exp() from SparkLike, DuckDB, and Ibis

narwhals/_arrow/series.py, narwhals/_pandas_like/series.py, tests/expr_and_series/clip_test.py
Spotted while narwhalifying great-tables
=> fix: `.clip` should not treat 0 and None as same

tests/modern_polars/pivot_test.py, tests/modern_polars/unpivot_test.py
Continuing work that started in #2177 which appears to have been inactive for a long period of time. The original work addressed `pivot_test`, and I have picked it up to add more end-to-end tests from modern Polars (#1945 ). 
Co-authored-by @tylerriccio33 (contributor of #2177 )
- Related issue #1945 
- Closes #2177 ?
=> test: Modern Polars end-to-end tests

docs/api-reference/dataframe.md, narwhals/dataframe.py, narwhals/stable/v1/__init__.py, tests/conftest.py, tests/frame/from_dict_test.py, tests/v1_test.py, utils/check_api_reference.py
- Part of #2116
- Figure out how (#2786) fits in
- Add `@overload`s on `backend`
- Like in `Namespace`
- Defer to `DataFrame.from_dict` in `nw.from_dict`
=> feat: Add `DataFrame.from_dict`

narwhals/_compliant/expr.py, narwhals/_dask/expr.py, narwhals/_sql/expr.py, narwhals/expr_name.py, tests/expr_and_series/name/map_test.py, tests/expr_and_series/name/prefix_test.py, tests/expr_and_series/name/suffix_test.py, tests/expr_and_series/name/to_lowercase_test.py, tests/expr_and_series/name/to_uppercase_test.py, tests/selectors_test.py, tests/series_only/is_ordered_categorical_test.py
=> feat!: Allow for chaining `.name` expressions, aligning with Polars' new aliasing behaviour

.github/workflows/pytest-pyspark.yml, narwhals/_expression_parsing.py, narwhals/_spark_like/__init__.py, narwhals/_sql/__init__.py
- Closes #2909 and closes #2840 
---
I am not sure if we should (and even can) keep the label triggers.
Another idea could be to have a cron once a week
=> ci: Run pyspark constructors via path

narwhals/_namespace.py
- Part of #2492
This wasn't the idea I had in mind in (https://github.com/narwhals-dev/narwhals/issues/2492#issuecomment-3089103410)
But was a simple enough to avoid ([`PLR0911`](https://docs.astral.sh/ruff/rules/too-many-return-statements/))
=> refactor: Reduce returns in `Namespace.from_native_object`

narwhals/_pandas_like/dataframe.py, tests/frame/from_arrow_test.py
- Noticed while looking into #2879
- Related #2891
Upstream:
- https://github.com/modin-project/modin/pull/6806
- https://github.com/modin-project/modin/pull/7274
=> fix: Use updated `from_arrow` import for `modin`

narwhals/_polars/expr.py, narwhals/_polars/series.py, narwhals/_polars/utils.py
Building on these two
- (1) #2897
- (2) #2918
Going to be setting the groundwork for #2474
Basic idea is at the end of (https://github.com/narwhals-dev/narwhals/pull/2451#discussion_r2070128922)
Trying out with the `Expr|Series` namespaces, since they can can use a `TypeVar` in any case like this:
https://github.com/narwhals-dev/narwhals/blob/0052ca5c646b0f5f396e7f5efd682caaac2e45f6/narwhals/_polars/series.py#L735
https://github.com/narwhals-dev/narwhals/blob/0052ca5c646b0f5f396e7f5efd682caaac2e45f6/narwhals/_polars/expr.py#L412
=> refactor: Shrink `Polars*Namespace(s)`, but more

tests/expr_and_series/unique_test.py
Looks like this is working fine, i'm just concerned that we'd missed nulls out of this test completely
=> test: include nulls in `unique` test

tests/expr_and_series/list/unique_test.py, tests/frame/getitem_test.py
Closes #2948
- https://github.com/pandas-dev/pandas/issues/61311
- Closes #2948
=> test: unxfail `pandas[pyarrow]` series slice on nightly

narwhals/_pandas_like/utils.py, tests/dtypes_test.py, tests/expr_and_series/cast_test.py, tests/expr_and_series/list/len_test.py, tests/frame/explode_test.py
- Discovered in https://github.com/narwhals-dev/narwhals/commit/0c5b7d5616a6efc6dcfe34143b54181c7a56547d
- `pandas`-only has been enforced (by us) since #2113
I was writing a schema conversion test and was confused by the output.
`modin` just re-exports `pd.ArrowDtype` *as-is*, so maybe this was always working? 🤔
- https://github.com/modin-project/modin/blob/e3724b67c60eee972451ca10fee1c7496f7f3861/modin/pandas/__init__.py#L99
- https://modin.readthedocs.io/en/stable/supported_apis/utilities_supported.html#other-objects-structures
=> fix: Allow `modin[pyarrow]` to use more dtypes

narwhals/_arrow/utils.py, narwhals/_pandas_like/utils.py, tests/frame/from_dict_test.py
Closes #2851
- Closes #2851
- `polars` always supported it
- `pyarrow` never will
=> fix: Support passing `nw.Object` to pandas-like

narwhals/_arrow/utils.py, narwhals/_dask/utils.py, narwhals/_duckdb/expr.py, narwhals/_duckdb/namespace.py, narwhals/_duckdb/utils.py, narwhals/_ibis/utils.py, narwhals/_pandas_like/utils.py, narwhals/_polars/utils.py, narwhals/_spark_like/utils.py, narwhals/dtypes.py, tests/dtypes_test.py
- Should make this easier as well (#2486)
Incredibly simple feature, but made a big refactor possible (starting from 307047099f22d720935101714312323788003972)
Based on [`polars.DataType.base_type`](https://github.com/pola-rs/polars/blob/34595af53dbdcbde52ab062746a42aa725e321a4/py-polars/polars/datatypes/classes.py#L145-L159)
See (https://github.com/narwhals-dev/narwhals/pull/2969#discussion_r2266773501) for details
=> feat: Add `DType.base_type`

docs/api-reference/dtypes.md, narwhals/dtypes.py, tests/dtypes_test.py, utils/check_api_reference.py
- Part of #2965
- See 97628 links there!
Did some re-aligning with [upstream](https://docs.pola.rs/api/python/version/1/reference/datatypes.html) as well
<details><summary>Outdated</summary>
<p>
What's currently in the PR I'm considering a **starting point** to chisel away at.
I'm happy with the *what*, but the repetition is waaaay too much 😔
So I'm very open to suggestions (even if they're just a link to other docs) on ways we can present it better
</p>
</details> 
Pretty happy with the new `dtypes` page, we've now got the hierarchy documented and examples of how `__eq__` works.
The main changes are shown in (https://github.com/narwhals-dev/narwhals/pull/2999#issuecomment-3193620241)
- https://mkdocstrings.github.io/python/usage/configuration/members/
- …
=> docs: Include `DType` methods, properties in API Reference

.github/workflows/pytest.yml, narwhals/_spark_like/dataframe.py
- https://github.com/duckdb/duckdb/pull/18642
- https://github.com/narwhals-dev/narwhals/actions/runs/17096107509/job/48483947375
- https://discord.com/channels/1235257048170762310/1272835922924273694/1407676349925036052
> [!IMPORTANT]
> Originally named *fix: Handle `pa.RecordBatchReader` in `SparkLikeLazyFrame.collect`*
=> ci: Remove `duckdb` nightly from cov

tests/expr_and_series/rolling_var_test.py, tests/frame/invalid_test.py, tests/series_only/is_ordered_categorical_test.py, tests/translate/get_native_namespace_test.py, tests/utils.py, tests/utils_test.py
- #2944
- #2159
I have no idea what to title this PR 😂
During another PR I noticed some strange typing that *I think* was masking the problems resolved recently in the `from_native` overloads.
So, I've removed/corrected some annotations that had `Frame` or `IntoSeries`.
> [!IMPORTANT]
> We should not need to annotate *inline* when handling the return of a `narwhals` function
> That indicates an issue with **our** typing to fix
=> test(typing): Avoid masking fixed overloads

narwhals/_dask/expr.py
- Added in #3030
- https://github.com/narwhals-dev/narwhals/actions/runs/17204513065/job/48802070870?pr=3016
We don't have `dask` installed for typing CI, so this slipped through
Started getting this locally and in (#3016), where I needed `dask` (and `modin`) to verify the new fancy overloads 😅
```py
Success: no issues found in 429 source files
/narwhals/_dask/expr.py
/narwhals/_dask/expr.py:451:36 - error: Argument of type "NAType | float" cannot be assigned to parameter "other" of type "float" in function "mask"
Type "NAType | float" is not assignable to type "float"
"NAType" is not assignable to "float" (reportArgumentType)
1 error, 0 warnings, 0 informations
```
=> chore(typing): Ignore inferred type in `dask_expr.Series.mask`

narwhals/_duckdb/dataframe.py, narwhals/_duckdb/utils.py, tests/frame/unique_test.py
=> fix: duckdb `Lazyframe.unique` was raising when column name was "group"

narwhals/_plan/arrow/dataframe.py, narwhals/_plan/arrow/expr.py, narwhals/_plan/common.py, narwhals/_plan/protocols.py
- See for idea https://github.com/narwhals-dev/narwhals/pull/3068#discussion_r2312609903
- #3066
Will eventually be replacing most of this (so far only `cast` 😄):
https://github.com/narwhals-dev/narwhals/blob/c72c3e4f0000eb4bbb34ce03bdaad675db29a8c3/narwhals/_plan/protocols.py#L149-L200
And then something similar for this group as well:
https://github.com/narwhals-dev/narwhals/blob/c72c3e4f0000eb4bbb34ce03bdaad675db29a8c3/narwhals/_plan/protocols.py#L201-L222
=> refactor(expr-ir): Generate dispatch methods (wip)

narwhals/_plan/expr_expansion.py, narwhals/_plan/meta.py
- Child of #3066
- One of the bigger modules
- ~~Still can see some opps for squeezing out more~~ **Wow, quite a lot was hiding there** 😅
=> refactor(expr-ir): Shrink `expr_expansion`

narwhals/_compliant/series.py, narwhals/_expression_parsing.py, narwhals/_polars/expr.py, narwhals/_polars/series.py, narwhals/dataframe.py, narwhals/group_by.py, narwhals/series.py, narwhals/stable/v1/__init__.py, tests/frame/group_by_test.py
This had been annoying me for a while
We're using `CompliantNamespace.parse_into_expr`, which accepts Python scalars, in `{DataFrame,LazyFrame}.{select,with_columns}`, even though there we don't accept Python scalars
I think this simplifies things a little, and means we can do `.alias` within `flatten_and_extract` before going to the compliant level (which I think is not a bad thing, given that there we're still at the Narwhals level. this will also help in some follow-up / skunkworks)
=> chore: simplify parsing expressions in group-by

narwhals/_utils.py
- Full revert of #2731
- Not needed since #2969
Now, we only have 1 case which uses the 2x `@overload`(s).
I'm keeping the 3x as well for now, just in case that changes 🙂
=> refactor(typing): Remove now-unused `isinstance_or_issubclass` overloads

narwhals/_dask/dataframe.py, narwhals/_dask/expr.py, narwhals/_duckdb/dataframe.py, narwhals/_ibis/dataframe.py, narwhals/_polars/dataframe.py, narwhals/_spark_like/dataframe.py, narwhals/_utils.py, tests/utils_test.py
- Closes #3121
Added explicit prefix only on lazy backends operations since these are the ones that a user might be able to investigate in various way. Not really applicable in the eager case
=> feat: Add `prefix` argument to `generate_temporary_column_name`

.github/workflows/downstream_tests.yml, narwhals/_duckdb/dataframe.py, tests/frame/collect_test.py
The `uv sync` command was using pinned dependency versions from `uv.lock` instead of fetching the latest versions. This caused a hidden issue where tests were running against outdated dependencies - notably discovered with duckdb failing locally while CI tests passed.
Adding the `--upgrade` flag forces `uv sync` to fetch the latest versions of dependencies, ignoring the pinned versions in the lock file.
=> fix: add `--upgrade` flag to `uv sync --dev`
